### ISSUE TITLE
Feature Request: Plot a BlankBoard.

### ISSUE THREAD

**Issue by dengbo22** [facebookresearch/visdom#100]
Can we just plot a blank board, and alway use updateTrace to add new points or new lines?

**Comment by ajabri** [comment]
Hi @dengbo22 ,

Thanks for your message! The vis.line API indeed does require at least one point. You can, however, use the generic Plotly API to maintain such a "blankboard"
 object (https://github.com/facebookresearch/visdom#generic-plots).

**Comment by CeLuigi** [comment]
Hi @dengbo22 ,

Thanks for your help. However, the following code:
> import visdom
vis = visdom.Visdom()
> trace = dict(x=[1,2,3], y=[4,5,6], marker={'color': 'red', 'symbol': 104, 'size': "10"},
                    mode="markers+lines",  text=["one","two","three"], name='1st Trace')
> layout=dict(title="First Plot", xaxis={'title':'x1'}, yaxis={'title':'x2'})
> vis._send({'data': [trace], 'layout': layout, 'win': 'mywin'})

raises the error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1509, in _execute
>     result = method(*self.path_args, **self.path_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/visdom/server.py", line 248, in post
>     ptype = args['data'][0]['type']
> KeyError: 0
> ERROR:root:ERROR: 500: {'exc_info': (<type 'exceptions.KeyError'>, KeyError(0,), <traceback object at 0x7f187063d440>)}

Have any idea why?
Thanks

**Comment by GaiYu0** [comment]
@ajabri Could you explain how to use Plotly API to create a blank window in more detail? Thank you very much!

**Comment by ashwin-cognitiv** [comment]
I'm having a similar error. Did you find any fix?

**Comment by IssamLaradji** [comment]
+1. This would be very useful. I would also love to have a function that tells me whether a window exists to avoid overriding it when I am running independent experiments.

**Comment by ajabri** [comment]
Ah, I think there needs to be a 'type' field in each data entry:
```
trace = dict(x=[1,2,3], y=[4,5,6], type='line', marker={'color': 'red', 'symbol': 104, 'size': "10"},
```
This requirement should probably removed eventually.

**Comment by farleylai** [comment]
@CeLuigi Use vis.line() instead. vis._send() is internal and subject to change I guess.
```
vis.line(X=np.array([1,2,3]), Y=np.array([4,5,6]), opts=dict(xlabel='x1',ylabel='x2',title='First Plot', marker={'color': 'red', 'symbol': 104, 'size': "10"},mode="markers+lines", text=["one","two","three"], name='1st Trace'))
```

**Comment by malmaud** [comment]
Is some kind upserting API something you'd be interested in incorporating? Seems like the situation arises commonly if you are updating a graph after every step of an iterative algorithm. As it stands,  it's kind of inelegant to have to create some kind of dummy graph with a meaningless point before the algorithm runs.
