### ISSUE TITLE
Feature Request: Audio support

### ISSUE THREAD

**Issue by obust** [facebookresearch/visdom#101]
It would be nice if the API could support audio `vis.audio` along with the other basic visualization functions:

- `vis.image` : images
- `vis.text` : arbitrary HTML
- `vis.video` : videos
- `vis.svg` : SVG object
- `vis.save` : serialize state server-side

**Comment by ajabri** [comment]
Hi @obust ,

Agreed! This should be easy to implement, it is basically a more simple version of the video function. See https://www.w3schools.com/html/html5_audio.asp .

**Comment by JackUrb** [comment]
Implemented in https://github.com/facebookresearch/visdom/commit/590c790562a938442c48e69a5f8dec821ae75fc4
