### ISSUE TITLE
Input range interaction

### ISSUE THREAD

**Issue by obust** [facebookresearch/visdom#102]
Is there a way to add an input range associated to a plot with which we can interact.

A particularly useful use case in machine learning is to visualize model byproducts at different epochs during the training. For example, visualize images generated by a GAN at different epochs. It important to be able to do it within a single panes otherwise the plots proliferate and cluter the layout.

I am not too familiar with plotly but it seems like they support some user interface to some extent.

**Comment by ajabri** [comment]
Hi @obust ,

Thanks for your message! I agree that this kind of thing would be useful. It's worth noting that such a pane would not have to involve plotly. In a sense what you describe is a video, except in the use case you describe you probably don't want to deal with compression. I think such an image scrolling feature could be implemented with plain HTML. For plot interaction, we have an open issue, #25.
