### ISSUE TITLE
How can l make loss and accuracy curves for CNN using visdom ?

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [facebookresearch/visdom#103]
Hello,

l just discovered visdom. l get stuck at making loss and accuracy curves using it.

Thank you for your helps

**Comment by zengyu714** [comment]
Hey, 
maybe you can refer to [demo.py](https://github.com/facebookresearch/visdom/blob/master/example/demo.py), see the `# line plots` and `# line updates` part. 
I also write a simple [class](https://github.com/zengyu714/pytorch-utils/blob/master/easy_visdom.py) based on the demo.
Hope these could help you.

**Comment by lvdmaaten** [comment]
Please only use the issues tracker to report issues, bugs, and feature requests.
