### ISSUE TITLE
The updateTrace cannot update two line in the same win

### ISSUE THREAD

**Issue by xjtu-zeng** [facebookresearch/visdom#104]
I want to draw two line in the same **_win_**, but I cannot use the updateTrace to update the two line in one win, Is my code error or does not support such function?

**Comment by xjtu-zeng** [comment]
`vis.line(X = np.array([1,2,3]), Y = np.array([[1,2,3], [2,3,4], [3,4,5]]),  win="line1")
`
![newplot 1](https://user-images.githubusercontent.com/15373554/27385664-f9d5cdf8-56c5-11e7-8cfe-2abb7d198785.png)

Wrong update Code:
`vis.updateTrace(X = np.array([[4],[4],[4]]), Y = np.array([[4],[5],[6]]), win="line1")
`
`vis.updateTrace(X = np.array([4,4,4]), Y = np.array([4,5,5]), win="line1")
`




Any other methods?

**Comment by lvdmaaten** [comment]
Doesn't this do what you want?

```
import numpy as np
import visdom
vis = visdom.Visdom()
vis.line(X = np.array([1,2,3]), Y = np.array([[1,2,3], [2,3,4], [3,4,5]]), win="line1")
vis.line(X = np.array([[4,4,4]]), Y = np.array([[4,5,6]]), win="line1", update="append")
```
Note that you can replace a value in `Y` by `None` if you don't want to plot a point on the corresponding line at a particular `X` value.
