### ISSUE TITLE
AttributeError: 'Visdom' object has no attribute 'quiver'

### ISSUE THREAD

**Issue by C8LUKA** [facebookresearch/visdom#105]
hi, when I install visdom in my ubuntu system, I try to run the demo.py example.and I got this:
AttributeError: 'Visdom' object has no attribute 'quiver'
I thought maybe I didn`t install quiver, so I pip install the quiver. then I try again, it still the same question:
AttributeError: 'Visdom' object has no attribute 'quiver'
Is any package I didn`t install?

**Comment by ajabri** [comment]
Hi @C8LUKA ,

Thanks for your message! This is because we haven't pushed a new version to PyPi yet since quiver was added for python. If you need quiver, you can install from source. I'll push a new version in the next few days.

**Comment by C8LUKA** [comment]
well @ajabri ,
thanks for you response, "you can install from source" You means I should try to python setup.py install?
but I did it ,it still not work

**Comment by lvdmaaten** [comment]
Closing this issue as the missing functionality was added: https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L900
