### ISSUE TITLE
example/demo.py: video writer could not be opened

### ISSUE THREAD

**Issue by bishesh** [facebookresearch/visdom#106]
The video example does not work.
I get the following error: 

``
 File "visdom_demo.py", line 28, in <module>
    viz.video(tensor=video)
  File "/home/bk17/anaconda3/envs/pytorch/lib/python3.6/site-packages/visdom/__init__.py", line 420, in video
    assert writer.isOpened(), 'video writer could not be opened'
AssertionError: video writer could not be opened
``

I'm using the [video](http://media.w3.org/2010/05/sintel/trailer.ogv) mentioned in the code comments as the input file.
The installed opencv version is 3.2.0

**Comment by lvdmaaten** [comment]
Did you ever manage to get video reading / writing via OpenCV to work on your setup? The code that does not appear to work for you is here: https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L422-L435

Unfortunately, the issue is hard to debug for us without a repro. It is most likely some issue with your setup.

**Comment by bishesh** [comment]
Sorry, missed this for a while and then later was waiting to test OpenCV set-up properly before posting.
The problem is with the choice of codec in fourcc variable in the code you linked above. Would it be possible to support other codecs (like letting user choose it) ?
```python
fourcc = cv2.VideoWriter_fourcc(
                    chr(ord('T')),
                    chr(ord('H')),
                    chr(ord('E')),
chr(ord('O'))
```
I tried a simple test code in my set-up and it works for certain codecs but not with the one used in visdom:
```python
import cv2
import torch
import numpy
t = torch.zeros(10,100,100,3)
t1 = torch.ones(100,100,3)
for idx in range(t.size()[0]):
    if idx % 3 == 0:
        t[idx,:,:,:] = t1
fw, fh = t.size()[1], t.size()[2]
fourcc = cv2.VideoWriter_fourcc(*'MJPG') # works
#fourcc = cv2.VideoWriter_fourcc(*'XVID') # Does not work
# fourcc = visdom fourcc also does not work

out = cv2.VideoWriter('../results/output.avi',fourcc, 2.0, (fw, fh))
assert out.isOpened(), 'video writer could not be opened'

for idx in range(t.size()[0]):
    out.write(t[idx,:,:,:].numpy())
out.release() 
```

**Comment by bishesh** [comment]
Quickly checked the guidelines for sending a PR. Seems like I would have to update both the Lua and python code. I am not familiar with Lua at all and not able to invest time to learn it ATM.  
I can try if I just need to change the python interface

**Comment by JackUrb** [comment]
@GregorKoehler - We haven't revisited this, though we'd be happy to accept a PR that adds an optional flag to the python version of the `video` function for other codecs.
