### ISSUE TITLE
Python example works but not lua

### ISSUE THREAD

**Issue by junhocho** [facebookresearch/visdom#11]
installed as required but found lua examples are not working

```
| visdom http request failed: host or service not provided, or not known
| visdom http request failed: host or service not provided, or not known
| visdom http request failed: host or service not provided, or not known
| visdom http request failed: host or service not provided, or not known
...
```

But python code works fine and can see in port 8097.

**Comment by lvdmaaten** [comment]
Are you sure the server name (`localhost`?) and port (8097?) you used to initialize the Lua client are correct?

I cannot reproduce this issue: the Lua and Python client both appear to work fine for me (I can even use both with the same server simultaneously).

**Comment by SSeanHsu** [comment]
I got the same question. Python code works fine, but not lua

**Comment by SSeanHsu** [comment]
@lvdmaaten I type `python -m visdom.server` to star server. After that I open a new terminal typing `th example/demo2.lua`. But I got nothing but infinite `visdom http request failed: host or service not provided, or not known`

**Comment by SSeanHsu** [comment]
@junhocho Did you succeed?

**Comment by bongmo** [comment]
I solved this problem by adding 'vis.ipv6 = false' after initialization.

**Comment by junhocho** [comment]
Sorry still not working. Uninstalled and installed again, not still working. Maybe I should try more. Also can not understand @bongmo 's solution.

**Comment by junhocho** [comment]
I just tried another 2 linux machines. Same failure
```
pip install visdom  # Installs in ./anaconda3/lib/python3.6
luarocks install visdom
python -m visdom.server
python demo.py  # Works
th demo1.lua # All three linux machines are not working
```

**Comment by SSeanHsu** [comment]
@bongmo Still not working. But I am pleasant to see guys working on it.

**Comment by bongmo** [comment]
@junhocho @SSeanHsu Would you please test following code? and I made ~/.ssh/config file with LocalForward 127.0.0.1:8097 127.0.0.1:8097

require 'image'
vis = require 'visdom'()
vis.ipv6 = false -- in my case vis.ipv6 was true
vis:text{text = 'Hello, world!'}
vis:image{img = image.fabio()}

**Comment by SSeanHsu** [comment]
@bongmo Awesome! Your code works. Thanks a lot.

**Comment by lvdmaaten** [comment]
I updated the `README.md` accordingly: https://github.com/facebookresearch/visdom/commit/feb3bd847635c0e0bbc47f2a9909fe7711607bc6

Closing this issue for now. Feel free to re-open it if the work-around does not work for you.
