### ISSUE TITLE
visdom shows nothing

### ISSUE THREAD

**Issue by y406539259** [facebookresearch/visdom#111]
I am very confused that I tried the demo.py but showed nothing at http://localhost:8097
The server has received the message but shows nothing, the web explorer only shows  blue background, It has no other windows.

y406539259@BILL-172:~$ python -m visdom.server
It's Alive!
INFO:tornado.access:304 GET / (127.0.0.1) 5.03ms
INFO:tornado.access:304 GET / (::1) 3.56ms
INFO:tornado.access:304 GET / (222.201.139.49) 3.57ms
INFO:tornado.access:304 GET /favicon.png (222.201.139.49) 2.84ms
INFO:tornado.access:200 POST /events (::1) 1.37ms
INFO:tornado.access:200 POST /events (::1) 2.56ms
INFO:tornado.access:200 POST /events (::1) 1.79ms
INFO:tornado.access:200 POST /events (::1) 1.20ms
INFO:tornado.access:200 POST /events (::1) 0.79ms
INFO:tornado.access:200 POST /events (::1) 1.08ms
INFO:tornado.access:200 POST /events (::1) 1.69ms
INFO:tornado.access:200 POST /events (::1) 1.47ms
INFO:tornado.access:200 POST /update (::1) 1.51ms
INFO:tornado.access:200 POST /events (::1) 1.01ms
INFO:tornado.access:200 POST /events (::1) 0.99ms
INFO:tornado.access:200 POST /events (::1) 0.91ms
INFO:tornado.access:200 POST /events (::1) 0.69ms
INFO:tornado.access:200 POST /events (::1) 0.60ms
INFO:tornado.access:200 POST /events (::1) 9.94ms
INFO:tornado.access:200 POST /events (::1) 6.87ms
INFO:tornado.access:200 POST /events (::1) 1.26ms
INFO:tornado.access:200 POST /events (::1) 0.92ms
INFO:tornado.access:200 POST /events (::1) 0.71ms
INFO:tornado.access:200 POST /update (::1) 0.89ms
INFO:tornado.access:200 POST /update (::1) 0.62ms
INFO:tornado.access:200 POST /update (::1) 1.09ms
INFO:tornado.access:200 POST /events (::1) 1.12ms
INFO:tornado.access:200 POST /events (::1) 0.92ms
INFO:tornado.access:200 POST /events (::1) 1.33ms
INFO:tornado.access:200 POST /events (::1) 0.60ms
INFO:tornado.access:200 POST /events (::1) 0.61ms
INFO:tornado.access:200 POST /events (::1) 0.65ms
INFO:tornado.access:200 POST /close (::1) 0.78ms
INFO:tornado.access:200 POST /events (::1) 0.67ms
INFO:tornado.access:304 GET / (::1) 3.81ms
INFO:tornado.access:304 GET / (127.0.0.1) 2.62ms
INFO:tornado.access:304 GET / (222.201.139.49) 3.58ms
INFO:tornado.access:304 GET /favicon.png (222.201.139.49) 3.68ms
INFO:tornado.access:304 GET / (222.201.139.49) 3.55ms
INFO:tornado.access:200 GET /favicon.png (222.201.139.49) 3.33ms
INFO:tornado.access:304 GET / (127.0.0.1) 3.01ms
INFO:tornado.access:304 GET / (127.0.0.1) 3.74ms
INFO:tornado.access:304 GET / (::1) 3.33ms
INFO:tornado.access:304 GET / (127.0.0.1) 3.35ms

**Comment by zengyu714** [comment]
Same on python3.6, it used to be OK.

**Comment by ysfalo** [comment]
Same on python2.7 ubuntu 14,04

**Comment by ajabri** [comment]
Hmm. Can you surface the Developer Console in your browser and post any error messages that show up on the browser end? With Chrome you can get this in 'View'->'Developer'->'Javascript Console'.

**Comment by zengyu714** [comment]
> (index):24 GET https://cdn.rawgit.com/STRML/react-grid-layout/0.14.0/dist/react-grid-layout.min.js net::ERR_CONNECTION_TIMED_OUT
> (index):28 GET https://cdn.rawgit.com/plotly/plotly.js/master/dist/plotly.min.js net::ERR_CONNECTION_TIMED_OUT

This time-out error could be solved by  **proxy**, and then `visdom` is normal again.
Thank @ajabri  for providing a way to check errors.

Thanks to the GREAT Firewall in China. 👎

**Comment by y406539259** [comment]
process.env.ENV is not defined, assuming 'prod' env

GET https://cdn.rawgit.com/STRML/react-grid-layout/0.14.0/dist/react-grid-layout.min.js net::ERR_CONNECTION_TIMED_OUT 116.56.143.172/:24
GET https://cdn.rawgit.com/plotly/plotly.js/master/dist/plotly.min.js 
net::ERR_CONNECTION_TIMED_OUT 116.56.143.172/:28

Uncaught ReferenceError: ReactGridLayout is not defined 
    at Object.<anonymous> (http://116.56.143.172:8097/static/js/main.jsv=1dec7545b53a21bc0a4c9df11e24c8fc:1:11583)
    at t (http://116.56.143.172:8097/static/js/main.js?v=1dec7545b53a21bc0a4c9df11e24c8fc:1:107)
    at Object.<anonymous> (http://116.56.143.172:8097/static/js/main.jsv=1dec7545b53a21bc0a4c9df11e24c8fc:1:227)
    at t (http://116.56.143.172:8097/static/js/main.js?v=1dec7545b53a21bc0a4c9df11e24c8fc:1:107)
    at http://116.56.143.172:8097/static/js/main.js?v=1dec7545b53a21bc0a4c9df11e24c8fc:1:194
    at http://116.56.143.172:8097/static/js/main.jsv=1dec7545b53a21bc0a4c9df11e24c8fc:1:199

WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips

**Comment by yukang2017** [comment]
Would you please give some instructions on how to use proxy to solve this? @zengyu714

**Comment by yukang2017** [comment]
Would you please give some instructions on how to use proxy to solve this? @zengyu714

**Comment by zengyu714** [comment]
That is, use your VPN.

2017-08-10 11:29 GMT+08:00 yukang2017 <notifications@github.com>:

**Comment by zengxianyu** [comment]
I don't think it can be solved by VPN. Sometimes I use VPN, and visdom works; sometimes I don't use VPN, and Visdom works. But sometimes I use VPN, and Visdom do not work.

**Comment by zengxianyu** [comment]
I don't think it can be solved by VPN. Sometimes I use VPN, and visdom works; sometimes I don't use VPN, and Visdom works. But sometimes I use VPN, and Visdom do not work. @zengyu714 

btw, it seems that you and me have a same name 'zeng yu' :smiley:

**Comment by yukang2017** [comment]
@zengxianyu 
change py/__init__.py,line 206 server='http://localhost' to 
server='127.0.0.1'
then resetup visdom using:
python setup.py install

It works for me without VPN

**Comment by zengxianyu** [comment]
It does not work for me :cry: @yukang2017

**Comment by yukang2017** [comment]
When using it, go to the address : 127.0.0.1:8097 instead of http://localhost:8097.
@zengxianyu

**Comment by zengxianyu** [comment]
Still doesn't work for me :rofl: I've left for tensorboard

**Comment by y406539259** [comment]
The reason is the web browser can not find plotly and react-gird-layout through internet
My idea is download these two packages and change the search path of them in index.html of visdom.

So I downloaded 
1, plotly.js: https://github.com/plotly/plotly.js
2, react-gird-layout: https://github.com/STRML/react-grid-layout

And put them in 
python2.7/site-packages/visdom/static/js/

And I added the search path of them in: 
python2.7/site-packages/visdom/static/index.html 

So the web browser can find them locally. 

    
    <script src="https://unpkg.com/react@15/dist/react.min.js"></script>
    <script src="https://unpkg.com/react-dom@15/dist/react-dom.min.js"></script>
    <script src="https://unpkg.com/classnames@2.2.5"></script>
    <script src="https://unpkg.com/layout-bin-packer@1.2.2"></script>
    <script src={{ static_url("js/react-grid-layout-master/dist/react-grid-layout.min.js") }}></script>

    
    <script type="text/javascript" async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_SVG"></script>

    
    <script src={{ static_url("js/plotly.js-master/dist/plotly.min.js") }}></script>


Finally, it works and do not need to use a VPN.

**Comment by SilvesterHsu** [comment]
@zengyu714 I met many issues concerning `visdom` since March. This is one of it. Sometimes I am lucky to load the page, sometimes I got blank blue page. But I had never been considering this as an error. Presently, I add CDS into proxy rules, it works fine now.

**Comment by Allloginsbusy** [comment]
I have same problem, but I have a proxy on own machine. I tried to copy locally js libs, but see  this logs on js console.
WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
MathJax.js:32:5
Ошибка карты кода: request failed with status 404
URL ресурса: http://127.0.0.1:8097/static/fonts/layout_bin_packer?v=6c46683ed70fbb1443caf3531243836d
URL карты кода: layout-bin-packer.js.map
[Подробнее]
Ошибка карты кода: request failed with status 404
URL ресурса: http://127.0.0.1:8097/static/js/react-grid-layout.min.js?v=062d847cc21a7fc3df5557aa91b4dbf5
URL карты кода: react-grid-layout.min.js.map
[Подробнее]
Ошибка карты кода: request failed with status 404
URL ресурса: https://unpkg.com/layout-bin-packer@1.2.2
URL карты кода: layout-bin-packer.js.map
[Подробнее]
Ошибка карты кода: request failed with status 404
URL ресурса: http://127.0.0.1:8097/static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219
URL карты кода: bootstrap.min.css.map
How I can solve this problem?

**Comment by lvdmaaten** [comment]
Please manually download and install the dependencies per the instructions in https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md

**Comment by ningyanuta** [comment]
Sometimes, when there is a proxy setup in environment, it will make visdom only display a blue screen. I found that setting os.environ['http_proxy'] = '' solves this case. Hope this could help.

**Comment by JackUrb** [comment]
@masoodmortazavi does anything appear in the javascript console or the python server logs when you're running into this issue?

**Comment by masoodmortazavi** [comment]
Comparing the already-downloaded javascript files in the pip installation in Python virtual environment with those specified in visdom's "download.sh" on this git repository, and then using wget over proxy to download missing javascripts into the corresponding folder, fixed the problem. (There should be no OS level http proxy or https proxy settings. This does cause problems. The javascripts should be downloaded with wget -- just like specified on download.sh -- but with proxy settings set up for the wget process that does each download individually.)

**Comment by masoodmortazavi** [comment]
> @masoodmortazavi does anything appear in the javascript console or the python server logs when you're running into this issue?
visdom server simply waits to download missing javascript when no system level proxy is available. I did mention how I fixed this issue in the message I just posted.

**Comment by iamrdofficial** [comment]
I tried all the above-mentioned solutions but still, the error is not getting solved. What else should I do?

**Comment by lvdmaaten** [comment]
Are you sure there is no proxy between your visdom server and the code generating the visualization, or between the server and the machine on which you are looking at the visdom dashboard? Behavior like this is most commonly caused by some proxy configuration blocking traffic.

Do you see any errors in the JavaScript Console? (In Chrome: View -> Developer -> JavaScript Console.)

**Comment by iamrdofficial** [comment]
Yes I do see errors.

**Comment by lvdmaaten** [comment]
Can you please copy-paste the errors you see here?

**Comment by iamrdofficial** [comment]
Uncaught  :2019/extensions/MathMenu.js?V=2.7.1:2 
Uncaught SyntaxError: Unexpected number
MathZoom.js:2 Uncaught SyntaxError: Unexpected number
I am getting these two errors in the javascript console.

**Comment by huangmozhilv** [comment]
> Sometimes, when there is a proxy setup in environment, it will make visdom only display a blue screen. I found that setting os.environ['http_proxy'] = '' solves this case. Hope this could help.

This works for my Mac, python 3.6, torch 1.0, visdom 0.1.8.9

**Comment by leopardyao** [comment]
hello, I am in a company internet and with a proxy.
windows 10+ visdom 0.1.8.9
With proxy set up, I was able to successfully downloaded necessary static files, but getting the warnings when run vimserver from command line:
WARNING:tornado.access:404 GET /static/js/layout-bin-packer.js.map (::1)
WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map

if checked develop tools , it also shows 
DevTools failed to load SourceMap: Could not load content for http://localhost:8097/static/js/layout-bin-packer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:8097/static/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

click into the above http will show tornado web.py 404 problem.

--------------
I understand this might be due to some proxy or how should I fix them? What are js.map or css.map file do i really need to find and download them?

thanks

**Comment by leopardyao** [comment]
Visdom : blue screen (or with white tool bar but I cannot see anything plot in screen)
hello, I am in a company internet and with a proxy.
windows 10+ visdom 0.1.8.9
With proxy set up, I was able to successfully downloaded necessary static files, but getting the warnings when run vimserver from command line:
WARNING:tornado.access:404 GET /static/js/layout-bin-packer.js.map (::1)
WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map

if checked develop tools , it also shows
DevTools failed to load SourceMap: Could not load content for http://localhost:8097/static/js/layout-bin-packer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:8097/static/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

click into the above http will show tornado web.py 404 problem.

I understand this might be due to some proxy but how should I fix them? 
what i have tried , but is not working:
(1) replace my downloaded static folder with some offline downloaded static folder posted by other people. not working
(2) following above comments set os.environ['http_proxy'] = ''   (I put it in server.py)

What are js.map or css.map file do i really need to find and download them?

thanks

**Comment by JackUrb** [comment]
@leopardyao The contents of your image suggest that visdom is now running correctly. If you run the demo you should either see plots or potentially errors in the server logs if not.

**Comment by leopardyao** [comment]
> @leopardyao The contents of your image suggest that visdom is now running correctly. If you run the demo you should either see plots or potentially errors in the server logs if not.

Thanks JackUrb.
It turns out it is still the proxy issue.  Following the suggestions by ningykan, **I removed my http_proxy setting in env variables** and now it is working. (although sometimes it may need to restart the computer).

I am curious why this happens? After downloading all necessary static files, why Proxy setting still matters for visdom? As a few people are having the issues, can we add this as an option in future versions when staring visdom server from  the command?
Thanks!

**Comment by neverstopZyy** [comment]
> Visdom : blue screen (or with white tool bar but I cannot see anything plot in screen)
> hello, I am in a company internet and with a proxy.
> windows 10+ visdom 0.1.8.9
> With proxy set up, I was able to successfully downloaded necessary static files, but getting the warnings when run vimserver from command line:
> WARNING:tornado.access:404 GET /static/js/layout-bin-packer.js.map (::1)
> WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map
> 
> if checked develop tools , it also shows
> DevTools failed to load SourceMap: Could not load content for http://localhost:8097/static/js/layout-bin-packer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load SourceMap: Could not load content for http://localhost:8097/static/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> 
> click into the above http will show tornado web.py 404 problem.
> 
> I understand this might be due to some proxy but how should I fix them?
> what i have tried , but is not working:
> (1) replace my downloaded static folder with some offline downloaded static folder posted by other people. not working
> (2) following above comments set os.environ['http_proxy'] = '' (I put it in server.py)
> 
> What are js.map or css.map file do i really need to find and download them?
> 
> thanks
> 
> --Editted on 05/18--
> I searched on google and downloaded the _.map files in my css/js folders now the 404 warnings are gone, besides some unexpected number syntax error from math_ (are these errors important? I found in some other post it is not relevant)
> 
> I can see the white menu bar though ( view, enviroment bar)
> however, I still cannot see anything plot, nor can I change the enviroment.
> ![image](https://user-images.githubusercontent.com/35131627/82218235-2a09b700-994e-11ea-84ef-eb945456b792.png)
> ![image](https://user-images.githubusercontent.com/35131627/82218313-4ad20c80-994e-11ea-920b-45f1aaf52a36.png)

Hi! I get into the same trouble. Could you please tell me how to find some offline downloaded static folder to replace the online one?

**Comment by HLBayes** [comment]
maybe you need to update a newer version of visdom package.
