### ISSUE TITLE
Plot data with respect to time

### ISSUE THREAD

**Issue by gyang1011** [facebookresearch/visdom#112]
Hello,

I would like to plot data with respect to time in real time. The x-axis should be a time step and it increases over time. The y-axis is the data at the specific time step. 

I tried to use updateTrace( ) function to achieve that. How do I update the X with time steps?

**Comment by lvdmaaten** [comment]
I think the easiest way to achieve this is by repeatedly calling `line()` with the new data `X` as input, and setting the `update` argument to `'append'`.

**Comment by ajabri** [comment]
In other words, you need to maintain your own X timestep data.
