### ISSUE TITLE
Feature Request: saving plots, history slider

### ISSUE THREAD

**Issue by tachim** [facebookresearch/visdom#114]
Hi all, very nice software, we're using this internally at my company. Two questions:

1. Are there any plans for supporting saving a dashboard to disk visually in PDF format? Right now I just use save to PDF which chops up some of the plots.

2. Any plans to support "history" in the plots similarly to how tensorboard does it? E.g. to be able to scroll back and forth in time for an image pane.

**Comment by ajabri** [comment]
Hi @tachim 

Thanks for your message, we are glad you are finding visdom useful. 

1. I've been looking at the possibility of rendering the dashboard without an actual browser, e.g. headless rendering. Unfortunately, there is not yet a nice way of serializing the frontend to something viewable offline later (at least not nicer than saving to PDF).

2. I think you mean something like #25. I definitely agree that this would be nice to have. There may be a simple solution using the `text` pane with arbitrary HTML. This is still a TODO.

**Comment by JackUrb** [comment]
Closing as 1 is the same issue as #232 which has more recent updates on that issue and 2 is the same request as #25 (which is actually almost ready as of #260)
