### ISSUE TITLE
Feature request: Function returns if a window exists

### ISSUE THREAD

**Issue by ASpeiser** [facebookresearch/visdom#116]
I want to monitor progress of different scripts in one window using line plots. So the idea is that the script that is run first uses viz.line and then additional scripts use viz.updateTrace to add lines to the same window. However right now I don't see a straight forward way to check if a window exists and should be updated,  or if a new window needs to be created.

**Comment by lvdmaaten** [comment]
Each time you want to update the plot, simply call `line()` with the same name (for instance, the name of the experiment you're monitoring) as input into the `win` argument and set `update` to `append`.

**Comment by ASpeiser** [comment]
Updating the plot works fine but I don't think it solves my problem. 

I'll try to make my issue more clear:

Lets say I run the same script twice to train two networks (with different seeds) and I want to monitor their loss in the same plot. 
When I first run it it uses `line()` to create a new window, and then I use `updateTrace` (or `line` with append) to monitor the loss.

If I run the script again again and it uses `line()` with the same window name it would overwrite the window.
Instead I just want to do `updateTrace` to add a new line to the existing window. 

So I just want a way to do:

```
if check_if_win_exists(winow_name):
     updateTrace(winow_name) 
else:
     line(winow_name)
```

**Comment by lvdmaaten** [comment]
I see. Yeah, I suppose it would make sense to add such a function. I'm not sure when we'll have time to get to it, but it should be an easy addition so please feel free to send a PR implementing this.

**Comment by IssamLaradji** [comment]
Hi @ASpeiser,  did you manage to find/write a function that returns `True` if the window exists ?

**Comment by IssamLaradji** [comment]
This is my current workaround, which seems to work fine for my needs:
```python
def vplot(Y, X, title, xlabel, ylabel, name, win):
    msg = vis.updateTrace(Y=Y, X=X, name=name, win=win)

    if msg == 'win does not exist':
       options = dict(title=title ,  xlabel=xlabel,  ylabel=ylabel,  legend=[name])
       vis.line(X=X, Y=Y ,opts=options, win=win) 
```

**Comment by JackUrb** [comment]
Hi @ASpeiser @IssamLaradji, we just added this functionality in 99e675c41a4f95732ecdf355b125777ae3152be6. You should be able to call `viz.win_exists` with the window ID to see if it exists on the server yet.
