### ISSUE TITLE
HTTPConnectionPool for python

### ISSUE THREAD

**Issue by onlytailei** [facebookresearch/visdom#12]
When I try 
```
import visdom
import numpy as np
vis = visdom.Visdom()
vis.text('Hello, world!')
vis.image(np.ones((10, 10, 3)))
```
I got this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 170, in _send
    data=msg
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa5b40f3690>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
Actually the first time I launched the web successfully. But after that it cannot work anymore even I restart the computer.

**Comment by onlytailei** [comment]
Sorry... Forget to start the server....

**Comment by lvdmaaten** [comment]
You should run the `python -m visdom.server` command from your terminal, not in the python REPL. Make sure the server is running, so start in it a separate terminal window (potentially using `screen` or `tmux`)

**Comment by udion** [comment]
I started the server using ```python -m visdom.server -p 7777``` and was able to open it in the browser, 
![image](https://user-images.githubusercontent.com/18963158/34072189-d554f58e-e2a8-11e7-9f52-237f98d6852e.png)
![image](https://user-images.githubusercontent.com/18963158/34072194-e6af99d8-e2a8-11e7-82b0-d639a5617000.png)

but when trying 
```
import visdom, numpy as np
vis = visdom.Visdom()
vis.text('hello')
```
I get the following error:
![image](https://user-images.githubusercontent.com/18963158/34072178-9336a18e-e2a8-11e7-9d12-0b7eca4d84b6.png)
![image](https://user-images.githubusercontent.com/18963158/34072183-aa784c9e-e2a8-11e7-9bf2-7c842822b3e9.png)

please help

**Comment by lvdmaaten** [comment]
You should make your client connect to the correct port: `vis = visdom.Visdom(port=7777)`.

**Comment by udion** [comment]
Thanks,
also while running the demo script I get an error
![image](https://user-images.githubusercontent.com/18963158/34072406-04c2bb86-e2ad-11e7-9b17-3ee4a9dfaa84.png)
is this attribute not available yet through pip (I installed visdom using pip)

**Comment by JackUrb** [comment]
Hi @udion - Yeah I haven't updated the pip package just yet, sorry! Doing so now

**Comment by zhaopanpan73** [comment]
when I start the server.then it happens
![image](https://user-images.githubusercontent.com/31726025/48207422-90059d80-e3ab-11e8-9926-0e6b13ba9086.png)
I don't know what the "scripts" refers to ?

**Comment by JackUrb** [comment]
Every time the server runs it checks to see if it needs to download additional scripts for the frontend and then it does the downloads. This is normal behavior.

**Comment by zhaopanpan73** [comment]
@JackUrb  But my computer can't connect to the internet by school's config. In this situation,what should I do to make the server run properly

**Comment by JackUrb** [comment]
@zhaopanpan73 You can download the scripts elsewhere using the `download.sh` script, and then copy them over to the proper locations.
