### ISSUE TITLE
Text Scrolling

### ISSUE THREAD

**Issue by shubhamjain0594** [facebookresearch/visdom#120]
![screen shot 2017-07-24 at 5 27 37 pm 1](https://user-images.githubusercontent.com/5080900/28522549-0630fba6-7096-11e7-9162-87b658ab948b.png)
Currently content in vis.text if larger than window, then window needs to be dragged and resized. 

But instead we can have scrollable (in both x and y) window for text. So whenever content is larger than window, scroll is much better option than resizing windows. 

If this sounds reasonable then I can send a PR for this. 

On sidelines, pip package is not updated with latest additions to this package. Filter and zoom in additions are tremendously helpful. So can you let us know how is the release cycle for visdom.

**Comment by ajabri** [comment]
Hi @shubhamjain0594 

Totally sounds reasonable. This was actually added by someone at some point but incorrectly such that it added scroll bars to all pane types. 
https://github.com/facebookresearch/visdom/commit/49c374af1ae021345378c0b5538f34e7487b2aa7

Please feel free to submit a pull request! And yes, I'll push a new release to pip, thanks for the reminder.

**Comment by KeyKy** [comment]
@shubhamjain0594 could you tell me how to plot text with '\n' in your picture?

**Comment by shubhamjain0594** [comment]
@KeyKy I have used table above. But for plotting `\n`, just replace it with `<br>`.
