### ISSUE TITLE
Unexpected tickmax/tickmin behavior

### ISSUE THREAD

**Issue by psmaragdis** [facebookresearch/visdom#124]
This following piece of code creates a plot that is scaled from 0 to 0.5 in the y-axis, despite the use of the ```ytickmax``` option being set to 1.  This problem is also there if I omit ```ytickmin```, and is similar when I use the x-axis equivalents.

```
vis.line( array( [0,.5]), array( [0,.5]), 
    opts=dict(  
                ytickmin=0,
                ytickmax=1,
    ))
```

If I change ```ytickmin``` to a nonzero value then ```ytickmax``` works as expected.

```
vis.line( array( [0,.5]), array( [0,.5]), 
    opts=dict(  
                ytickmin=0.001,
                ytickmax=1,
    ))
```

**Comment by JackUrb** [comment]
Fixed in https://github.com/facebookresearch/visdom/pull/160
