### ISSUE TITLE
sometimes can not open the localhost link in my browser 

### ISSUE THREAD

**Issue by zengxianyu** [facebookresearch/visdom#128]
Visdom is a excellent tool to visualize when training a model, and I've been using it for months. 

However, recently, I often cannot open the localhost link to the Visdom server in my browser. The browser keep saying "connecting", and the visdom.server shows below information: 

INFO:tornado.access:200 GET /env/main (127.0.0.1) 1.83ms
INFO:tornado.access:200 GET /static/js/main.js?v=4b72317f763632006def9236be6408b4 (127.0.0.1) 2.35ms
INFO:tornado.access:200 GET /static/css/style.css?v=32ef18660f59fd1d0097e08d8f46b7af (127.0.0.1) 0.48ms
INFO:tornado.access:304 GET /env/main (127.0.0.1) 1.08ms
INFO:tornado.access:200 GET /env/main (127.0.0.1) 1.14ms
INFO:tornado.access:200 GET /static/js/main.js?v=4b72317f763632006def9236be6408b4 (127.0.0.1) 0.62ms
INFO:tornado.access:200 GET /static/css/style.css?v=32ef18660f59fd1d0097e08d8f46b7af (127.0.0.1) 0.46ms
INFO:tornado.access:304 GET /env/main (127.0.0.1) 1.50ms
INFO:tornado.access:304 GET /env/main (127.0.0.1) 1.60ms
INFO:tornado.access:200 GET /env/main (127.0.0.1) 1.35ms
INFO:tornado.access:200 GET /static/js/main.js?v=4b72317f763632006def9236be6408b4 (127.0.0.1) 0.53ms
INFO:tornado.access:200 GET /static/css/style.css?v=32ef18660f59fd1d0097e08d8f46b7af (127.0.0.1) 0.47ms
INFO:tornado.access:304 GET /env/main (127.0.0.1) 1.19ms
INFO:tornado.access:304 GET / (127.0.0.1) 1.28ms
INFO:tornado.access:304 GET /favicon.png (127.0.0.1) 1.25ms
INFO:tornado.access:304 GET / (127.0.0.1) 1.22ms

I tried reinstall Visdom, but this dose not solve this problem. 

Are there any solution?

Thanks in advance.

**Comment by zhxt0** [comment]
I encountered the same problem

**Comment by zengxianyu** [comment]
my workaround is turning to tensorboard

**Comment by ajabri** [comment]
I think the issue is related to the loading of JS dependencies. Can you open the developer console and share any error messages found there? In Chrome you can do this by `View`->`Developer`->`Javascript Console`.

**Comment by zengxianyu** [comment]
@ajabri Here's the error messages:
```
react-grid-layout.min.js Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
plotly.min.js Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
main.js?v=4b72317f763632006def9236be6408b4:1 Uncaught ReferenceError: ReactGridLayout is not defined
    at Object.<anonymous> (main.js?v=4b72317f763632006def9236be6408b4:1)
    at t (main.js?v=4b72317f763632006def9236be6408b4:1)
    at Object.<anonymous> (main.js?v=4b72317f763632006def9236be6408b4:1)
    at t (main.js?v=4b72317f763632006def9236be6408b4:1)
    at main.js?v=4b72317f763632006def9236be6408b4:1
    at main.js?v=4b72317f763632006def9236be6408b4:1
```

**Comment by lvdmaaten** [comment]
Yes, so for some reason, visdom cannot download the Javascript dependencies. Are you behind some kind of proxy that prevents traffic to the internet? Can you access https://cdn.rawgit.com/plotly/plotly.js/master/dist/plotly.min.js in your browser?

**Comment by zengxianyu** [comment]
Thank you all

The reason is the web browser can not find javascript dependencies through internet. Like y406539259 said [in this issue](https://github.com/facebookresearch/visdom/issues/111#issuecomment-321743890), downloading packages or using proxy can solve this problem
