### ISSUE TITLE
how to plot multiple line with different number points on one window?

### ISSUE THREAD

**Issue by cddlyf** [facebookresearch/visdom#130]
In `visdom.line` function, it only accept X and Y of size "N*M" . It means  each line must have the same length, but it is not the case in many scenarios. exp. training errors and validation errors.  Could you tell me how to implement this feature? or it has already implemented.

**Comment by lvdmaaten** [comment]
You can fill missing values in the NxM matrix with `nan`s and they will not be plotted.
