### ISSUE TITLE
Blank blue screen

### ISSUE THREAD

**Issue by oleggrinch** [facebookresearch/visdom#133]
Hi, I'm working on remote server.
I start visdom with

```
vis = visdom.Visdom(server='http://10.0.4.165',port = 8097)
vis.text('Hello, world!')
vis.image(np.ones((3, 10, 10)))
```

Server responses smth like

> INFO:tornado.access:200 POST /events (10.0.4.165) 0.69ms
> INFO:tornado.access:304 GET / (10.0.6.242) 4.36ms
> INFO:tornado.access:304 GET /favicon.png (10.0.6.242) 2.64ms

but http://10.0.4.165:8097 remains blank

Any ideas on what's going wrong? Thanks!

**Comment by xqms** [comment]
Also experiencing this issue here. It seems that the CDN that visdom is using (http://unpkg.com) is down or has some problems. For example, see what is delivered instead of the react.js library: https://unpkg.com/react@15.6.1/dist/react.min.js

I think we should remove the dependency on external CDNs - what exactly do we gain?

**Comment by lvdmaaten** [comment]
This seems to be working again now (it does for me)?

The reason for having the dependency like this is that we cannot distribute code by others as part of the repository. The right way to fix it would presumably be to have the install scripts download the dependencies and copy them somewhere in the install directory.

**Comment by MartinKolarik** [comment]
Lots of people have been complaining about *random* 404 and 503 unpkg responses recently. You can always use jsDelivr instead, which works in a similar way but is more reliable: https://cdn.jsdelivr.net/npm/react@15.6.1/dist/react.min.js

**Comment by SelvamArul** [comment]
Not solved yet. still facing the same issue.

**Comment by xqms** [comment]
> The reason for having the dependency like this is that we cannot distribute code by others as part of the repository.

@lvdmaaten I'm not a lawyer, but I think all open source licenses allow redistribution as long as you also include the license file and copyright notice. I think that would be the simplest solution.

**Comment by lvdmaaten** [comment]
Even if the license may allow it, Facebook does not want to re-distribute code.

**Comment by SelvamArul** [comment]
@lvdmaaten Shall I work on a patch to download the required files to the py/static/css or js directories as a part of setup.py file and modify  index.html file to use the local files?

**Comment by lvdmaaten** [comment]
@SelvamArul That would be great!

**Comment by heurainbow** [comment]
same problem, any solution now?

**Comment by lvdmaaten** [comment]
Solved by https://github.com/facebookresearch/visdom/commit/2d121340c863c3bbb4ab36de972faf4ea24c5509
