### ISSUE TITLE
[FeatureRequest] Keep plots order, or sort plots

### ISSUE THREAD

**Issue by t-ae** [facebookresearch/visdom#134]
Now I'm studying image generation task.
I plot images every fixed train epochs, like below.
![screenshot from 2017-08-17 07-33-19](https://user-images.githubusercontent.com/12446914/29388263-e7d3daa2-831e-11e7-8c50-47785e81b669.png)
But sometime (especially when I change the environment) the order is messed up.
![screenshot from 2017-08-17 07-33-31](https://user-images.githubusercontent.com/12446914/29388251-de2d6054-831e-11e7-897e-f9910c935216.png)
I'm glad if the order is not collapsed, or I can sort them by their titles.

**Comment by ajabri** [comment]
Hi @t-ae 

We've also found this to be annoying internally :) An easy fix is to add a sort button that sorts by a field called 'content_id'. I'll try to get that done some time soon.

**Comment by kuc2477** [comment]
Is there any progress in this feature?
