### ISSUE TITLE
Old context get lost when too many WebGL contexts exist

### ISSUE THREAD

**Issue by tommy-qichang** [facebookresearch/visdom#137]
Hi,
When I use visdom, there are two things really annoying. One is the order of the plot is messed up(as #134 mentioned). Another one is old context get lost when too many WebGL contexts exist, even after sorting the plot. I save few 3d scatter plots every epoch, and I found the plots from past epoch disappeared even if I filter the plot and just allow few plot to show.
<img width="1241" alt="disappeared plot" src="https://user-images.githubusercontent.com/19438484/29496191-d0dd60e6-859b-11e7-87c4-9cf5264a2dbd.png">

I think I can fix this part next few weeks if you think it's necessary. 

Thanks.
Qi

**Comment by lvdmaaten** [comment]
The WebGL issue presumably happens because each Plotly plot has its own
renderer? There is supposedly an ongoing effort to address this issue
[here](https://github.com/plotly/plotly.js/issues/949). I'm not sure there
is an easy way to fix this in visdom?

**Comment by tommy-qichang** [comment]
Thanks for your timely reply, Ivdmaaten,

I think there are several ways to accelerate the process. I just quickly checked the implementation in Visdom. When filtering the plots, Visdom simply hides the other grid. I think if there are too many Plotly plots, it's reasonable to disable the older plots. However, if we filter and narrow down the number of results, Visdom should refresh the whole layout and just render few nodes. 
<img width="1323" alt="screen shot 2017-08-20 at 12 37 24 pm" src="https://user-images.githubusercontent.com/19438484/29496627-5a28fa60-85a4-11e7-957b-15d2407b3f17.png">

Side notes, it's very strange plot.ly use SVG instead of WebGL to render the plot. I use Chrome which should support WebGL. 
<img width="907" alt="screen shot 2017-08-20 at 12 33 19 pm" src="https://user-images.githubusercontent.com/19438484/29496629-6d30e3c0-85a4-11e7-9bbf-b5a25e4421cf.png">

**Comment by JackUrb** [comment]
Closing this issue as more on the plotly side than visdom - even if we did disable plots on filter, how would we select which ones to re-enable moving forward? Using multiple envs seems to be the correct approach to prevent loss of context in visdom. 

If somebody comes up with a good solution/behavior for this issue I'd be happy to accept a PR that implements their solution, otherwise we'll await plot.ly
