### ISSUE TITLE
Saving as png resizes plot

### ISSUE THREAD

**Issue by magnusja** [facebookresearch/visdom#139]
Hey there,

whenever I save my plots as a png file, the plot gets resized and sometimes this results in the legend occluding the actual plot.

![image](https://user-images.githubusercontent.com/1659457/29737139-da3109c4-89bd-11e7-9ad6-e54680ca8097.png)

**Comment by lvdmaaten** [comment]
This logic is implemented in Plotly, not in visdom: https://github.com/plotly/plotly.js/blob/5da37913cb2d52ed3ad9b161b66f361a142ca1e1/src/components/modebar/buttons.js#L48,L70

So you would have to report this issue on Plotly's Github issue tracker.
