### ISSUE TITLE
options.columnnames not working

### ISSUE THREAD

**Issue by allenye0119** [facebookresearch/visdom#140]
According to [README.md](https://github.com/facebookresearch/visdom/blob/master/README.md), bar plot (and some other plot types) has a `columnnames` option, but when I try it, it doesn't has any affect on the plot. And then I found out that in [demo.py](https://github.com/facebookresearch/visdom/blob/973caab69699172d554f26a58a964c6034d6016e/example/demo.py#L130), `rownames` is used instead of `columnnames`, and it seems to achieve what `columnnames` should do. This makes me confused. Did I misunderstand anything?

**Comment by lvdmaaten** [comment]
The use of `rownames` appears correct in the demo you mention: the labels correspond to rows in the matrix `X`.

**Comment by allenye0119** [comment]
The problem that I encountered is that when `X` of `vis.bar` is a 1-D array, setting `options.columnnames` doesn't seem to set the label on x-axis, but setting `options.rownames` does. However, according to the documentation, setting `options.columnnames`  should do the job. Also, `options.rownames` isn't even documented.

**Comment by lvdmaaten** [comment]
Yes, the `README.md` is incorrect here. Pull request: https://github.com/facebookresearch/visdom/pull/142

Thanks for flagging this!
