### ISSUE TITLE
nothing shows up on the local client

### ISSUE THREAD

**Issue by MangoChao** [facebookresearch/visdom#141]
when i run the python example code on jupyter notebook ,nothing shows up on the client and there is no error. i'm running python3.5.2 on windows, with visdom 0.1.5 pip installed.
i'm running the code:
```
import visdom
import numpy as np
vis = visdom.Visdom()
vis.text('Hello, world!')
vis.image(np.ones((3, 10, 10)))
```
the putput is `'pane_356f8b50f9580a'`. it seems to be correctly creating a pane, but there is nothing showing up on http://localhost:8097/. and the visdom server gave:
```
It's Alive!
INFO:tornado.access:304 GET / (::1) 3.01ms
INFO:tornado.access:304 GET /favicon.png (::1) 1.00ms
INFO:tornado.access:200 POST /events (::1) 0.00ms
INFO:tornado.access:200 POST /events (::1) 1.00ms
```
any idea about what's wrong?
thanks

**Comment by lvdmaaten** [comment]
Is this specific to running from Jupyter notebook? That is, does it work when you use visdom from the Python CLI or a Python script?

Is this happening on all browsers? Does the JavaScript Console show any errors?

**Comment by ajabri** [comment]
Can you surface the Developer Console in your browser and post any error messages that show up on the browser end? With Chrome you can get this in 'View'->'Developer'->'Javascript Console'.

**Comment by hellozgy** [comment]
I get the same problem, I have tried the chrome and the firefox. I open the Javascript Console and the error info is like this:
react-grid-layout.min.js Failed to load resource: net::ERR_NAME_NOT_RESOLVED
Uncaught ReferenceError: ReactGridLayout is not defined
    at Object.<anonymous> (main.js:1)
    at t (main.js:1)
    at Object.<anonymous> (main.js:1)
    at t (main.js:1)
    at main.js:1
    at main.js:1

**Comment by NickYi1990** [comment]
same problem here, nothing show up~

**Comment by ChuXiaokai** [comment]
same problem here :(

**Comment by praveenofpersia** [comment]
One thing that might be worth checking on the client is if your browser can connect to (load-pages/fetch-scripts from) the internet. `visdom` relies on some external resources (like react) which needs to be fetched from the web/CDNs using URIs.
(Make sure your proxy (if any) is set correctly in the browser etc. )

**Comment by ajabri** [comment]
Yes, please check out #111 .

**Comment by MangoChao** [comment]
@lvdmaaten @ajabri @praveenofpersia Thank you very much, it works now. It's the same issue as [#111](https://github.com/facebookresearch/visdom/issues/111) and [#128](https://github.com/facebookresearch/visdom/issues/128). The  Developer Javascript Console shows that **the browser can not fetch the following external javascript dependencies from the web**: 
```
https://cdn.rawgit.com/STRML/react-grid-layout/0.14.0/dist/react-grid-layout.min.js
https://cdn.rawgit.com/plotly/plotly.js/master/dist/plotly.min.js
```
**This problem can be solved by downloading the packages or using proxy, like y406539259 said in [#111](https://github.com/facebookresearch/visdom/issues/111). **

Get the `plotly.min.js` and `react-grid-layout.min.js` files from [plotly.js](https://github.com/plotly/plotly.js/tree/master/dist) and [react-gird-layout](https://github.com/STRML/react-grid-layout/tree/master/dist). 
Put them in `where_you_install_visdom/visdom/static/js/`. 
Add/Change  the search path of them in `where_you_install_visdom/visdom/static/index.html`, like this:
```
<!-- Other deps -->
......
<script src={{ static_url("js/react-grid-layout.min.js") }}></script>

<!-- Plotly -->
<script src={{ static_url("js/plotly.min.js") }}></script>
```
The web browser can fetch them locally now.

Thank you all!

**Comment by MangoChao** [comment]
#111 #128
