### ISSUE TITLE
Shape of X in updateTrace

### ISSUE THREAD

**Issue by allenye0119** [facebookresearch/visdom#143]
Is there a reason why when updating a line plot with multiple lines, we have to repeat the value of X so that it matches the shape of Y:
`vis.line(X = np.array([[4,4,4]]), Y = np.array([[4,5,6]]), win="line1", update="append")`
while creating a line plot with multiple lines, we can simply do
`vis.line(X = np.array([1]), Y = np.array([[1,2,3]]), win="line1")`?

**Comment by lvdmaaten** [comment]
The logic for doing the "broadcast" of `X` is not implemented [here](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L618;L620). Something akin to [this](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L628;L629) should be executed there. Feel free to submit a PR implementing this!

**Comment by allenye0119** [comment]
OK, I'll submit a PR in one or two days.

**Comment by JackUrb** [comment]
This was fixed in a separate issue but never closed, closing now. Thanks for the PR!
