### ISSUE TITLE
Disable global scrolling while on an image

### ISSUE THREAD

**Issue by dzimmerer** [facebookresearch/visdom#145]
The whole window moves, while trying to zoom in on an image.

This is really very annoying  and sometimes leads to very unwanted results.

(Sadly I'm no react wizard so I cant do anything about it on my own =''( (except from disabling scrolling and setting the image width and height to 100% which I think is also a good solution) )

**Comment by lvdmaaten** [comment]
Thanks for reporting! I will land a fix for this soon.
