### ISSUE TITLE
Do not globally enable logger.INFO messages

### ISSUE THREAD

**Issue by skelleher** [facebookresearch/visdom#146]
server.py enables INFO messages for the root logger:

`logging.getLogger().setLevel(logging.INFO)
`

This, in turn, enables INFO messages for every included module.  
This is super-annoying because every call to Visdom prints tornado messages to STDOUT:

```
INFO:tornado.access:200 POST /update (::1) 1.03ms
INFO:tornado.access:200 POST /update (::1) 1.03ms
INFO:tornado.access:200 POST /update (::1) 1.95ms
INFO:tornado.access:200 POST /update (::1) 1.01ms
```
Because server.py is a separate process, users can't even disable the logging from our code; we have to modify server.py.

Visdom should probably take logger level from the command line args or a config file, and default to silence.

**Comment by lvdmaaten** [comment]
Agreed. I will send out a fix soon.
