### ISSUE TITLE
env json file

### ISSUE THREAD

**Issue by skrish13** [facebookresearch/visdom#151]
Where does the env json file exist? i can only find the `main.json` in `$HOME/.visdom/`. What about the json file of other environments? I dont save them explicitly, should I save them explicitly inorder to delete them? Even then where does it get stored by deafult and under what name?

Thanks in advance :)

**Comment by lvdmaaten** [comment]
All the env JSON files should get saved into the same folder (which is `~/.visdom` by [default](https://github.com/facebookresearch/visdom/blob/master/py/server.py#L93)). The name of the env equals the name of the file.

If you delete an env file in this folder, you may have to reload the server / reload visdom in your browser for the changes to take effect.

**Comment by skrish13** [comment]
Yes, I think what you said works when I **save** an environment. But if I don't save it manually (by clicking on `save` button) then there's no concept of **deleting** it? Is it because it doesnt save automatically? If it does, i don't find it in `$HOME/.visdom/` but i do find when manually saved (by clicking `save` button)

So, in that case I have one doubt, What does reloading the **server** do? (not webpage). Will it load only the environments from a `path` (Ex: `$HOME/.visdom`) and all unsaved environments are gone?

**Comment by lvdmaaten** [comment]
Yes, I think unsaved environments ought to disappear if you don't save them.

**Comment by skrish13** [comment]
Cool. Thanks a lot :D. I will try it once my machine gets free. Closing it now :) ,will reopen in-case I find anything wrong.
