### ISSUE TITLE
how to plot multi lines text with '\n'

### ISSUE THREAD

**Issue by KeyKy** [facebookresearch/visdom#154]
viz.text plot multi lines in one line.

**Comment by ajabri** [comment]
You can use '<br>' (as usual with HTML).

**Comment by daavoo** [comment]
You can replace `\n`with `<br> ` and it will work.

From the vis.text section of the Readme:

`This function prints text in a box. You can use this to embed arbitrary HTML. It takes as input a text string. `

**Comment by KeyKy** [comment]
Thanks!
