### ISSUE TITLE
how to programmatically check if the visdom server is running?

### ISSUE THREAD

**Issue by jkarimi91** [facebookresearch/visdom#156]
Is there a way to do this?

**Comment by lvdmaaten** [comment]
I don't think there is any other way of doing this than by sending a plot and monitoring the response obtained in https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L242

Feel free to add a `check_connection` that creates an empty plot and closes it again to check the connection.

**Comment by jkarimi91** [comment]
@lvdmaaten is there some sort of documentation for contributing, other than `CONTRIBUTING.md`;  I am having issues developing locally despite the instructions in the md file. 

As noted in the my [SO post][1],  I have:
  1.  locally cloned a fork of the repo
  2. made modifications under a new branch (which is built off `master`)
  3. building the new branch within a `conda` env:
```
$ which pip
/home/jkarimi91/Apps/anaconda2/envs/visdom/bin/pip
$ pip install -e .
```

Running pip list shows that the module installed successfully:
```
visdom (0.1.4, /home/jkarimi91/Projects/visdom)
```

However, when I try to import the module, I receive an import error:
```
$ which python
/home/jkarimi91/Apps/anaconda2/envs/visdom/bin/python
$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import visdom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named visdom
>>> 
```

[1]: https://stackoverflow.com/questions/46516822/import-error-after-pip-install-e

**Comment by jkarimi91** [comment]
Expect a PR soon, the python side is complete but not the torch side; I have been unable to successfully setup torch on my machine. I opened an issue on the torch7 issue tracker and am waiting to hear back.

**Comment by JackUrb** [comment]
Hi @jkarimi91, as of 1753e20f4ba805cb94d3646d472c53bc8d990a2a we've converted the Lua code to be a wrapper around the python code, so the python code is certainly more valuable.

**Comment by jkarimi91** [comment]
Thanks @JackUrb; expect a PR tomorrow.

**Comment by jkarimi91** [comment]
This functionality was added in https://github.com/facebookresearch/visdom/commit/0d1e78bc6b99cabb9861ccbd598bfe978b59399f. You can now call `viz.check_connection()` to see if the server is connected.

**Comment by Roulbac** [comment]
Checking connection before starting a server needs a Visdom object to be able to call viz.check_connection(), yet instantiating a Visdom object needs an already running server.
Any chance of making the check_connection a static method?

**Comment by JackUrb** [comment]
It would be possible to create a static version of the check_connection method that takes in the arguments that the current version is able to pull from the existing object, using the defaults if none are given, however I feel this is a different use case from what the current method tries to do. I'd be open to a PR that implements a static `check_server_active` or something with documentation for why it exists and is distinct from `check_connection` though.

**Comment by Roulbac** [comment]
I worked my way around it with this small snippet, maybe it will be of some help

`    def socket_is_used(self):
        is_used = False
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            s.bind((self.hostname, self.port))
        except socket.error:
            is_used = True
        finally:
            s.close()
        return is_used
`
