### ISSUE TITLE
Update mesh plot in a single window

### ISSUE THREAD

**Issue by weikaichenusc** [facebookresearch/visdom#157]
Hi!

Is there any function that supports updating mesh plot in a single window (similar to updateTrace) instead of creating a new window for mesh plot every time? It could be very useful if we wanna check out the status of synthesized mesh output.
Thanks a lot!

**Comment by ajabri** [comment]
You can do this by using the same `win` id when you make the mesh plot call.

**Comment by weikaichenusc** [comment]
Got it! It works, thanks!
Btw, how to tune the default view angle of the mesh plot?

**Comment by lvdmaaten** [comment]
I may have missed it, but Plotly doesn't seem to have an option for that at the moment: https://plot.ly/python/reference/#mesh3d

**Comment by chenweikai** [comment]
Okay, got it! Thanks!
