### ISSUE TITLE
Add colors at the vertex level

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [facebookresearch/visdom#159]
Is there anyway to add color at the vertex or face level instead of defining a global color for the entire mesh?

**Comment by JackUrb** [comment]
Given the current [plot.ly library](https://plot.ly/javascript/3d-mesh/) there is no clean way to implement something like this. Both `mesh` and `mesh3d` either only take a singular color or they use a 'colorscale' (which we currently don't support with mesh, but which you can access by creating a [generic plot](https://github.com/facebookresearch/visdom#generic-plots)). 

Colorscales provide the ability to give parts of the mesh color based on "intensity", where intensity of a point on the face is somehow determined based on the distance between vertices and the intensity of those vertices. This intensity scale is linear, and the color changes are linear as well. This might be able to do what you want in the simple case say by providing an intensity of 1 for the 3 vertices of a triangular face and 0 to everything else, then setting the colorscale such that the one face is given one color and everything else gets another, such as with this:
```
data = dict(
    type="mesh3d",
    x=[0, 1, 2, 0],
    y=[0, 0, 1, 2],
    z=[0, 2, 0, 1],
    i=[0, 0, 0, 1],
    j=[1, 2, 3, 2],
    k=[2, 3, 1, 3],
    intensity=[0, 0, 0, 1],
    colorscale=[
      [0, 'rgb(255, 0, 0)'], 
      [0.01, 'rgb(0, 255, 0)'],
      [1, 'rgb(0, 255, 0)']
    ]
)
```
which results in a green tetrahedron with one red face, however for doing anything more complicated than the simple cases it might not be possible to force colorscale to do what you want.

**Comment by ThibaultGROUEIX** [comment]
Hi Thanks a lot ! Getting colorscale to do what I wanted was too hard, but with your help, I manage to color different parts of the mesh by splitting it like 👍 
``` colors =[
    'rgb(255, 0, 0)',
    'rgb(0, 255, 0)',
    'rgb(0, 0, 255)',
    'rgb(255, 255, 0)',
    'rgb(255, 0, 255)'
]
for i in range(nb_primitives):
    data.append(
        dict(
        type="mesh3d",
        x=X[2500*i:2500*(i+1),0].tolist(),
        y=X[2500*i:2500*(i+1),1].tolist(),
        z=X[2500*i:2500*(i+1),2].tolist(),
        i=faces[0:len(faces)/nb_primitives,0].tolist(),
        j=faces[0:len(faces)/nb_primitives,1].tolist(),
        k=faces[0:len(faces)/nb_primitives,2].tolist(),
        color = colors[i]
        )
    )
layout=dict(title="First Plot", xaxis={'title':'x1'}, yaxis={'title':'x2'})

vis._send({'data': data,'layout': layout, 'win': 'mywin'}) ```
