### ISSUE TITLE
Issue with pip install -e .

### ISSUE THREAD

**Issue by pokey** [facebookresearch/visdom#16]
When I try to install visdom for local development, I get the following error when running `example/demo.py`:

```
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    from visdom import Visdom
ModuleNotFoundError: No module named 'visdom'
```

When I rename the directory `py` to `visdom`, this error goes away.

**Comment by lvdmaaten** [comment]
I can reproduce this behavior. It appears to be a `pip` issue: https://github.com/pypa/pip/issues/3

We will look into how we can solve this more elegantly (but for now, your work-around seems to work).

**Comment by ajabri** [comment]
Note that you can also do:
```
cd /path/to/visdom
python setup.py install
```
