### ISSUE TITLE
update='append' add line

### ISSUE THREAD

**Issue by mencattini** [facebookresearch/visdom#17]
I have this two lines:
![ema1](https://cloud.githubusercontent.com/assets/16821049/24050461/29f054fa-0b2f-11e7-9e12-cae8e2b32fb0.png)
![ema2](https://cloud.githubusercontent.com/assets/16821049/24050466/2dcdd5de-0b2f-11e7-9639-0dfd30dd5d09.png)

I try to plot them together with:
```python
win = vis.line(ema_1, np.arange(size_time))
vis.line(ema_2, np.arange(size_time), win=win,update='append')
```
And I get this plot:
![ema3](https://cloud.githubusercontent.com/assets/16821049/24050554/77c6e5e0-0b2f-11e7-96b6-9ebb5742cff3.png)

There is the two curves I expected and one more.
Did I something wrong?

Thanks

**Comment by lvdmaaten** [comment]
The `append` option adds new values to the existing lines, but cannot currently be used to add new lines. What is happening in your example is that the data is treated as a single line; hence the "jump" when you go from the first to the second line.

At this point, I think your best option is to create a new plot:
```
size_time = 10
ema_1 = np.arange(size_time) / 2
ema_2 = np.arange(size_time)
win = vis.line(ema_1, np.arange(size_time))
X = np.transpose(np.vstack((ema_1, ema_2)))
Y = np.transpose(np.vstack((np.arange(size_time), np.arange(size_time))))
win2 = vis.line(X=Y, Y=X)
```
We're looking into fixing this issue in a more principled way; thanks for reporting!

**Comment by mencattini** [comment]
Your solution works.
Thanks for the solution and the answer.
