### ISSUE TITLE
`NotADirectoryError` when starting server after installing from source

### ISSUE THREAD

**Issue by pltrdy** [facebookresearch/visdom#170]
Hi,

Using `Python 3.6.1 |Anaconda custom (64-bit)`:
```
git clone https://github.com/facebookresearch/visdom.git
cd visdom
python setup.py install
python -m visdom.server
```
returns:
```
Traceback (most recent call last):
  File "/home/pltrdy/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pltrdy/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pltrdy/anaconda3/lib/python3.6/site-packages/visdom-0.1.5-py3.6.egg/visdom/server.py", line 622, in <module>
  File "/home/pltrdy/anaconda3/lib/python3.6/site-packages/visdom-0.1.5-py3.6.egg/visdom/server.py", line 576, in download_scripts
  File "/home/pltrdy/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/home/pltrdy/anaconda3/lib/python3.6/site-packages/visdom-0.1.5-py3.6.egg/visdom'

```
---
It was working when I installed using pip, but then I can't run `example/demo.py` because there was no `Visdom.check_connection`.

**Comment by lvdmaaten** [comment]
I'm no expert on Python installers, but did you try `cd visdom && pip install -e .` rather than running `python setup.py install`?

**Comment by pltrdy** [comment]
It's even worse: 
`Error while finding module specification for 'visdom.server' (ModuleNotFoundError: No module named 'visdom')`

**Comment by JackUrb** [comment]
@pltrdy I'm investigating what might've happened now

**Comment by pltrdy** [comment]
(note that I just removed and installed using pip, nothing critical, just sharing this problem)

**Comment by JackUrb** [comment]
Alright I think I've come to the core of the problem, going to push a fix soon. After moving to setuptools from distutils the installation flow from source is a little different from what is currently in the docs. 

If you want to get ahead of the fix, change `zip_safe` in `setup.py` to False, then use `easy_install .` from within the visdom directory rather than `pip`
