### ISSUE TITLE
Problem with moving env's .json files

### ISSUE THREAD

**Issue by skrish13** [facebookresearch/visdom#172]
I take the <>.json file and transfer it to another machine's ~/.visdom/<>.json. And restart visdom in the new machine, it should work right? It doesn't.

Right now it shows the env but theres no plots/panes inside it. Its blank blue empty environment....

Would like a fast response. Thanks :)

**Comment by JackUrb** [comment]
Hi @skrish13, are you seeing any errors in your browser's javascript console or in the terminal you're running the server in? I'm not quite sure where the env contents are getting lost

**Comment by skrish13** [comment]
I don't see any errors on the terminal. Not sure about javascript console. Opened the json file to check, it has all the contents... 

One thing which i see now (and not before) is 

> "INFO:root:Application Started"

Earlier it was just simple "It's Alive!" (if i remember correctly? maybe I'm wrong)

**Comment by JackUrb** [comment]
It's likely on the javascript side if you're not seeing any server errors. Can you open the js console on the window you're using visdom in? You can get there using right click -> inspect element and then clicking console.

**Comment by skrish13** [comment]
Yes, it says something like this. (For all the panes)

> unrecognized command Object { title: "", i: 0, contentID: "3588a45b62d118", content: Object, command: "pane", type: "plot", id: "train_loss" }

And also this. with a cross on the left most side and highlighted in red (same as above)

> GET http://172.173.174.40:8097/static/css/bootstrap.min.css.map

**Comment by JackUrb** [comment]
Ah okay I see the issue - I'll need to push a fix, but the command "pane" was deprecated in  99e675c41a4f95732ecdf355b125777ae3152be6 and I hadn't considered it might break cross-compatibility between versions. The new machine is definitely running a newer version of visdom than the old one. I'm going to push a fix that addresses this and restores backwards compatibility. In the meantime, if you replace every occurrence of `command: "pane"` with `command: "window"` in the .json file on the new machine (via find-replace) you should be able to see the contents properly. Sorry about the break!

**Comment by skrish13** [comment]
Ah okay. Yes, the json was created with an older version on visdom. Both machines are on same (master) version only but.

**Comment by skrish13** [comment]
Hey @JackUrb is it fixed? if not should i keep this issue open?

**Comment by JackUrb** [comment]
This is indeed fixed, thanks @skrish13 for noticing the issue in the first place
