### ISSUE TITLE
vis._send is not working

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/visdom#173]
`vis._send ` doesn't seem to be working. 
I ran this code:
```python
import visdom
vis = visdom.Visdom()

trace = dict(x=[1,2,3], y=[4,5,6], marker={'color': 'red', 'symbol': 104, 'size': "10"},
                    mode="markers+lines",  text=["one","two","three"], name='1st Trace')
layout=dict(title="First Plot", xaxis={'title':'x1'}, yaxis={'title':'x2'})

vis._send({'data': [trace], 'layout': layout, 'win': 'mywin'})
```
and the output I get is
```
''
```
As a result, I don't see any pane in my visdom dashboard. I do get a pane if I run `vis.text("hello world")` which tells me that there must be an issue related to `vis._send`.

**Comment by JackUrb** [comment]
Good catch - We should have this in our demos (which we frequently use for testing our code) to ensure it doesn't break in the future. Pushing a fix to the server soon, though it'll require entering a 'type' in the trace dict, like `type='custom'`. Going to update that in the docs as well.

**Comment by IssamLaradji** [comment]
thanks. It doesn't seem to be working still. Is it working for you ?

**Comment by JackUrb** [comment]
Have you updated visdom and added a type to your trace dict?

**Comment by IssamLaradji** [comment]
Yes, my visdom is `visdom-0.1.6.2`

and I run the following:
```python
import visdom
vis = visdom.Visdom()

trace = dict(x=[1,2,3], y=[4,5,6], marker={'color': 'red', 'symbol': 104, 'size': "10"},
                          mode="markers+lines",  text=["one","two","three"], 
                         name='1st Trace', type="custom")

layout=dict(title="First Plot", xaxis={'title':'x1'}, yaxis={'title':'x2'})

vis._send({'data': [trace], 'layout': layout, 'win': 'mywin'})
```
I get this output:
```
''
```

**Comment by JackUrb** [comment]
That is indeed what the demo script will output, however the server should output a post to `/events`. Then in your browser you'll end up with this:
![screen shot 2017-11-10 at 12 17 19 pm](https://user-images.githubusercontent.com/1276867/32670276-4abcfdd0-c611-11e7-8b93-22c73f248cf4.png)

**Comment by IssamLaradji** [comment]
Oh nevermind! it's working. I forgot to restart the Visdom server with the updated version of Visdom. Thanks for the help.

**Comment by JackUrb** [comment]
No worries, thanks again for the initial catch!

**Comment by yzexeter** [comment]
Hi, 
I tried vis._send(). It always throws  "Object of type ''int64" is not JSON serializable. What is wrong with this?

**Comment by JackUrb** [comment]
What are you trying to `_send`? Seems your data is not in a format that is is JSON serializable as the error says. You should convert to arrays of numbers rather than `int64` objects.

**Comment by yzexeter** [comment]
I am trying to send a list, which converted from np.array. So this means that I shall convert the dtype first, then use list()?
