### ISSUE TITLE
Error while running Demo file

### ISSUE THREAD

**Issue by shubhamjain0594** [facebookresearch/visdom#175]
While running [scatter](https://github.com/facebookresearch/visdom/blob/master/example/demo.py#L92) in demo.py, raises an error:

```bash
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
File "/home/users/shubham/anaconda2/envs/cxr_dl/lib/python3.6/site-packages/visdom-0.1.6-py3.6.egg/visdom/__init__.py", line 262, in _send
   data=json.dumps(msg),
File "/home/users/shubham/anaconda2/envs/cxr_dl/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
File "/home/users/shubham/anaconda2/envs/cxr_dl/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
File "/home/users/shubham/anaconda2/envs/cxr_dl/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
```

This is because in opts['markercolor'] has keys as class numbers not strings. Which is being set [here](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L612).

One way to solve is by deleting markercolor from opts if it exists since we are already passing it while preparing _data. If this sounds good, I will submit a PR for this.

**Comment by JackUrb** [comment]
Strange, I'm not running into the same issue - out of curiosity is this something that was newly introduced for you? (does it happen if you install earlier versions of visdom?)

Removing markercolor from opts right before the `_send` call does seem like it would solve the issue without breaking anything, so if it fixes it for you I'd accept that (as it would fix it for any others that might be having this problem as well).

**Comment by shubhamjain0594** [comment]
I am running Python3.6.

Tried using fresh install of visdom by uninstalling and then doing `pip install visdom`. Then tried running demo.py by commenting out `check_connection` and `win_exists` api calls. Still the same error persists.

Will send the PR right away.

**Comment by shubhamjain0594** [comment]
@JackUrb if you look at how opts['markercolor'] has been handled in `vis.scatter` and `vis.updateTrace` i.e [here](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L621) and [here](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L552) respectively is bit different. I did not dive into this problem but was curious to know why such difference.

If both of these options have a purpose, then deleting markercolor from opts key just before sending it to frontend might not be the correct option then to solve this issue.

**Comment by JackUrb** [comment]
From what I see it would appear that `updateTrace` is actually just not properly handling the `markercolor` in the way that `scatter` is. `scatter` is using a correct implementation, while `updateTrace` appears to be using an early format that we moved away from. It should be updated to use `scatter`'s handling at some point

**Comment by shubhamjain0594** [comment]
Do we even need `updateTrace`? We can handle it with if else function at end of `scatter`, only difference is `endpoint` argument and handling `name` in case of `updateTrace`. What is the exact utility of `updateTrace`?

**Comment by JackUrb** [comment]
To my knowledge updateTrace was supposed to be a catch-all function that we might expand in the future to update more than just scatter plots, but that hasn't quite happened yet.

**Comment by shubhamjain0594** [comment]
How about rather than calling `updateTrace` before any processing is done, we call it after the processing specifically required for that function (say `line` or `scatter`) is completed. So `updateTrace` will be called right before  `self._send` is called in the function end.

**Comment by JackUrb** [comment]
I'd be happy with that kind of solution. Sure, updateTrace would become a wrapper around the functionality of updating, but it at least it would make the logic consistent.
