### ISSUE TITLE
Reconnect to a window after starting new Python session

### ISSUE THREAD

**Issue by abisee** [facebookresearch/visdom#177]
Thanks for this project! I'm using it to do something like Tensorboard for training deep learning models.

I'm using visdom to plot a line graph of the loss function as I train. Sometimes I need to stop training, then restart it again. When I restart, is there some way I can connect to that same window, and continue appending points to the graph?

For example, is there some way to assign a unique ID to a window then retrieve it in a different session using the same ID?

**Comment by JackUrb** [comment]
Yup this is definitely doable - If pass a value in for `win` when creating the window the first time and then save the env, on a future run you can use `updateTrace` on that same `win`. Let me know if you have any trouble getting this to work.

**Comment by abisee** [comment]
Thanks @JackUrb!

Where can I find the API for `updateTrace`? I'm trying to use it but I don't know what arguments it should take.

**Comment by abisee** [comment]
OK, I think I've figured it out. Posting my solution here if useful for other people:

```
import visdom
import numpy as np
vis = visdom.Visdom()

# Make a new plot
vis.line(
  Y=np.arange(10), 
  X=np.arange(10), 
  win = "mywin"
)

# QUIT AND RESTART PYTHON HERE

import visdom
import numpy as np
vis = visdom.Visdom()

# Add new points to your plot
vis.updateTrace(
  Y=np.arange(10), 
  X=np.arange(10,20), 
  win="mywin"
)
```

**Comment by lvdmaaten** [comment]
Thanks for posting your solution!
