### ISSUE TITLE
Question: how to make plots into the Visdom Server from other languages? (eg. C++, Java, ...)

### ISSUE THREAD

**Issue by andrewssobral** [facebookresearch/visdom#179]
There is a REST interface or a specific HTTP request for that? Thank you!

**Comment by lvdmaaten** [comment]
There are currently no code examples showing how to do this, but it is certainly possible. All plotting functions in the Python client generate a JSON data structure describing the plot contents, and post the JSON to the server: https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L246
The JSON format is defined by Plot.ly. Hence, you can generate the appropriate JSON in C++ or Java and send it to the server, which will visualize it.

Having said that, re-implementing and maintaining client logic in some other language is a lot of work. For the Lua client, therefore, we did the following: the Lua client sends a special JSON request to the server that contains the (Python client) function name and all the input arguments that one would pass to the Python client: https://github.com/facebookresearch/visdom/blob/master/th/init.lua#L964
The server unpacks this special request and executes the corresponding Python client code to obtain the JSON that encodes the data Plot.ly needs: https://github.com/facebookresearch/visdom/blob/master/py/server.py#L290
The advantage of this approach is that (1) it minimizes the amount of Lua code we have to write and (2) any changes in the Python client are automatically exposed in the Lua client.

If you'd like to add a C++ or Java client, I would propose to use a similar setup. It may not require any changes in the server side (although we should probably change the name of the `unpack_lua` function).

**Comment by andrewssobral** [comment]
Great! Thank you for the detailed information @lvdmaaten
