### ISSUE TITLE
Feature Request: Programmatically resize window?

### ISSUE THREAD

**Issue by abisee** [facebookresearch/visdom#183]
I'd like to be able to define the width and height of a window programmatically. So far I can only find `opts.width` and `opts.height`, but those (a) resize the *figure* but not the *window* and (b) isn't available for e.g. text windows, which I'd also like to resize. Is there some way to programmatically resize a window?

**Comment by JackUrb** [comment]
Currently visdom doesn't support programmatically sizing windows, however we wouldn't be against supporting such functionality moving forward. If you're interested in contributing to such a feature, it would entail adding an additional pair of options (`win_width` and `win_height`) seem appropriate. One tricky thing you may run into looking at the code is that on the frontend windows are referred to as "Panes". Beyond that there are two primary places involved in such a change, the place where windows are packaged into panes, and the place where panes are processed on the frontend:
Windows are packaged into panes [here](https://github.com/facebookresearch/visdom/blob/master/py/server.py#L225). Panes are processed [here](https://github.com/facebookresearch/visdom/blob/master/js/main.js#L105).
