### ISSUE TITLE
Legend is not shown when there is a single plot

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/visdom#186]
When I run the following code, I get the scatter plot but no legend. Is it possible to get the legend displayed ? Thanks!

```python
vis.scatter(np.array([[4,5], [2,1], [5,4]]), 
                 opts=dict(legend=["example"], showlegend=True), win="dbg")
```

**Comment by JackUrb** [comment]
this appears to be a bug in [_opts2layout](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L104).  The line should read `'showlegend': 'legend' in opts,`. I'll push a fix

**Comment by IssamLaradji** [comment]
Thanks @JackUrb !
