### ISSUE TITLE
How can I change the background color?

### ISSUE THREAD

**Issue by zergzzlun** [facebookresearch/visdom#188]

**Comment by lvdmaaten** [comment]
I haven't tested it, but I think you can simply change this value: https://github.com/facebookresearch/visdom/blob/master/py/static/css/style.css#L24

**Comment by zergzzlun** [comment]
@lvdmaaten 
Thanks a lot.

**Comment by zergzzlun** [comment]
@lvdmaaten 
It worked! Thanks again!
![1405558678](https://user-images.githubusercontent.com/16285167/32361555-751eb48a-c09c-11e7-988e-6b4d9ddbdb7e.jpg)
