### ISSUE TITLE
Display row names in full texts

### ISSUE THREAD

**Issue by HenryZhou7** [facebookresearch/visdom#189]
When I am using the stacked bar chart, the x row names cannot be displayed in full texts due to the size of the window. I am wondering if it can be displayed in full text or what I should do in order to do that. Thanks! The below image is shown as an example. The label should be Inception, 2 Fast 2 Furious, Marley and Me.

![image](https://user-images.githubusercontent.com/9815099/32278134-eb6fd2d0-bed1-11e7-978c-6d1d86e25411.png)

**Comment by JackUrb** [comment]
I don't know if there's a way to get the bounding box for those names, so your only option is to use the `opts['marginbottom']` attribute for that window. Right now it defaults to 60, but if you increase that you should be able to see the rest of the text
