### ISSUE TITLE
Feature to make the font size bigger for labels and rownames?

### ISSUE THREAD

**Issue by HenryZhou7** [facebookresearch/visdom#190]
The rownames' font size seems to be default. And it is quite small. Is there a way to make the font size optional?

**Comment by JackUrb** [comment]
Once https://github.com/facebookresearch/visdom/pull/191 is in you should be able to use 
```
opts['xtickfont'] = {
    'size': 16
}
```
or 
```
opts['ytickfont'] = {
    'size': 16
}
```
to set the font size of labels on the x/y axis.

Or were you asking for something different?

**Comment by HenryZhou7** [comment]
Yes. This solved my problem. Thank you!
