### ISSUE TITLE
Feature request: plot the legends within the graph

### ISSUE THREAD

**Issue by HenryZhou7** [facebookresearch/visdom#197]
Is it possible to add an option to plot the legends within the graph itself, or to change the location of the legends? Thanks in advance!

**Comment by JackUrb** [comment]
This is currently supported by [plotly](https://plot.ly/javascript/legend/#positioning-the-legend-inside-the-plot) but not by visdom. You can consider adding a 'legendopts' param to opts, then adding a line to the [layout packing function](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L100) that sets `'legend': opts.get('legendopts', None),`. I'd be happy to accept a PR that does this
