### ISSUE TITLE
Feature Request: update text pane

### ISSUE THREAD

**Issue by elanmart** [facebookresearch/visdom#20]
Hi, 
sometimes it's useful to send some textual data from the model in regular intervals. As far as I understand, right now we can only replace text in the window with something new, but we cannot append.

I can easily monkey-patch it by adding the following to `UpdateHandler` and modifying `css` to display newlines, but I don't know how to do this properly. 
```python 
def update(self, p, args):
    if isstr(p['content']):
        p['content'] += "\r\n" + args['data'][0]['content']
        return p
```

**Comment by lvdmaaten** [comment]
The most logical way would be to add an `update` option to the Python and Lua implements of `text()`. If `update` is set to `True`, the `UpdateHandler` should be called instead. Here's an example of how to send a request to the `UpdateHandler`: https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L306-L315

In the `UpdateHandler`, you would have to check that the `type` of the request is `'text'` before executing the string concatenation code above.

**Comment by lvdmaaten** [comment]
Fixed by https://github.com/facebookresearch/visdom/pull/168
