### ISSUE TITLE
Feature request: error bars (basic and continuous)

### ISSUE THREAD

**Issue by dukebw** [facebookresearch/visdom#201]
Hello! I am interested in using error bars in my Visdom plots, ideally the continuous error bars (https://plot.ly/javascript/continuous-error-bars/), but just as well the basic error bars (https://plot.ly/javascript/error-bars/).

I tried adding basic error bars simply by adding,

```python
'error_y': {
    'type': 'data',
    'array': [10.0],
    'visible': True
},
```

(for example) to `scatter()` here: https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L648.

This works for the first point, but not for appending additional points (i.e. for the first point I get an error bar, but additional points get added to the plot with no error bars).

I was wondering if I might get some direction about what changes need to be made to get this functionality in, since Plotly supports it but it seems that Visdom does not. Do changes need to be made to server.py?

Thanks!

**Comment by ajabri** [comment]
Here's an example: https://github.com/facebookresearch/visdom/issues/18#issuecomment-309280610

**Comment by JackUrb** [comment]
Implementing something along the lines of @ajabri's linked method should only require changes to `__init__.py`, for as long as the error bar information is added both on creation and appending new info, the server should be able to handle the changes
