### ISSUE TITLE
can someone share  all your  of the files in visdom/static?

### ISSUE THREAD

**Issue by huguyuehuhu** [facebookresearch/visdom#202]
Can someone share  all of the files in visdom/static? Although with a VPN, I still can't  download the missing files caused by the firewall. Thanks very much!  My Email address is huguyuehuhu@gmail.com.

**Comment by lvdmaaten** [comment]
We cannot redistribute the JavaScript dependencies, but you can find a list of all dependencies and the subfolders in which they should be copied [here](https://github.com/facebookresearch/visdom/issues/185#issuecomment-340486095).

**Comment by huguyuehuhu** [comment]
got it, thank you.
