### ISSUE TITLE
Please update version on PIP

### ISSUE THREAD

**Issue by napsternxg** [facebookresearch/visdom#204]
The current pip version is not based on the current code. It doesn't have the name argument for the line function. Please update the version on pip.

**Comment by lvdmaaten** [comment]
You can always just install the current source using `pip install -e`.

**Comment by napsternxg** [comment]
When I do that I am not able to use visdom. 

I get the error: `No module named visdom.server` when running `python -m visdom.server`

Also, the site-package directory doesn't have any python packages. It looks like this:
```
/home/username/anaconda3/lib/python3.5/site-packages/visdom
└── static
    ├── css
    │   ├── bootstrap.min.css
    │   ├── react-grid-layout-styles.css
    │   └── react-resizable-styles.css
    ├── fonts
    │   ├── classnames
    │   ├── glyphicons-halflings-regular.eot
    │   ├── glyphicons-halflings-regular.eot?#iefix
    │   ├── glyphicons-halflings-regular.svg#glyphicons_halflingsregular
    │   ├── glyphicons-halflings-regular.ttf
    │   ├── glyphicons-halflings-regular.woff
    │   ├── glyphicons-halflings-regular.woff2
    │   └── layout_bin_packer
    └── js
        ├── bootstrap.min.js
        ├── jquery.min.js
        ├── mathjax-MathJax.js
        ├── plotly-plotly.min.js
        ├── react-dom.min.js
        ├── react-grid-layout.min.js
        └── react-react.min.js

4 directories, 18 files

```

**Comment by ajabri** [comment]
You can also try `python setup.py install`, from the visdom source directory.

**Comment by napsternxg** [comment]
Ok that worked. Any idea why the pip install didn't work ?

**Comment by JackUrb** [comment]
`pip install -e` sometimes has difficulties with linking module locations if you already have the module in question installed, I usually have to `pip uninstall` twice after accidentally installing with `-e` while I already have it installed. The pip version will be updated soon though - I had forgotten to bump the version number in the last set of updates
