### ISSUE TITLE
Using Visdom through an iframe with a reverse proxy?

### ISSUE THREAD

**Issue by ppeeou** [facebookresearch/visdom#205]
Hi, I want to use a reverse proxy while wrapping visdom in an iframe.
By the way, data in visdom is having difficulty parsing http header in nginx while using web socket. (There is no http referer.)

If I change the host, there is a cross-domain issue and I can not change it.

https://github.com/facebookresearch/visdom/blob/b7a2228f6c8449ec99d41f7008e16aab1c503ab7/js/main.js#L145

If you leave http header information in the socket path, We can use visdom more usefully.
Or is there another way ? Please help me ~~

**Comment by JackUrb** [comment]
Can you provide more details about your setup and the issue you're having?

WebSockets are supposed to support cross-domain traffic, so at that point I'm not quite sure I'm following what is wrong.

If headers are your issue, please refer to the [WebSocket docs](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) as I'm fairly sure there's a way to support passing http headers in there.

**Comment by ppeeou** [comment]
hi ! @JackUrb 
To better explain our service, Our system tries to put visdom into an iframe.

The server where the actual visdom is running and the server being serviced are in different spaces, We could not verify the server information running on visdom.

Below is a flow that inserts visdom into an iframe,
![image](https://user-images.githubusercontent.com/10924072/33478749-b93ed55e-d6cd-11e7-8fba-3e1f318ce61e.png)

If I call 6 image , the information should be called 7 , but  I can not handle nginx because there is no http referer information.

https://github.com/facebookresearch/visdom/blob/b7a2228f6c8449ec99d41f7008e16aab1c503ab7/js/main.js#L145



![image](https://user-images.githubusercontent.com/10924072/33479273-db41ac56-d6cf-11e7-8023-032a9d5be3ce.png)

- Only the web sockets that are called below are not leaving referer information.
![image](https://user-images.githubusercontent.com/10924072/33479371-3650a20a-d6d0-11e7-8918-8ab3a97f0b79.png)

This is our situation.

**Comment by ppeeou** [comment]
Resolved by using browser cookies.
