### ISSUE TITLE
Pane resize issue in firefox

### ISSUE THREAD

**Issue by Nintorac** [facebookresearch/visdom#206]
I am unable to resize panes, the initial click works and I can resize the window however the mouse up event never registers so the graph size is continually updated with my mouse movements despite not being clicked.

I think this has been an issue since updating to Firefox 58 ...currently running 58.0b4 (64-bit)

also tested in Chrome  62.0.3202.62 and everything works fine there

**Comment by lvdmaaten** [comment]
Do any errors messages appear in your browser console when you access visdom and/or when you try and resize a pane? (Check `Tools -> Web Developer -> Web Console`.)

**Comment by Nintorac** [comment]
no erros in console

**Comment by Nintorac** [comment]
seems to be working on current master
