### ISSUE TITLE
4D Tensor videos only display when dims are square

### ISSUE THREAD

**Issue by amini2nt** [facebookresearch/visdom#209]
I have a 4d tensor to display my atari game and it only displays the video when I input the height and width as a square(meaning that I give the same number of dimensions for both the height and width). It does not work when I have different height and width values  How do I fix that?

**Comment by JackUrb** [comment]
Can you give more context than 'it does not work' -> Do any errors appear in either the server or frontend console when using different values? What function are you using to render it?

Please refer to the [contributing guidelines ](https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md) and try to provide some more context so that we can better help you solve this issue. Thanks!

**Comment by amini2nt** [comment]
I understand that once the 4D image tensor of the form `FRAMESxHIEGHTxWIDTHx3`, is provided to the tensor argument of the video, it will generate a new window in the visdom server. Now, based on my experiments, the video in the browser could be played only when the images are square (`HIEGHT=WIDTH`). Otherwise the window will contain a blank video and could not be played. I tested it with Google Chrome 62.0.3202.94, Mozilla Firefox 57.0, and opera 49.0.2725.39.
To the best I can guess, it's probably some convention with CV2 or even THEO.
Also, I made another issue earlier that was deleted just to note that [here](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L463) it is mentioned that each tensor should be of shape `LxCxHxW`, however, the correct version of this is actually `LxHxWxC`. I can pull a request for that single line, too if you want.

**Comment by JackUrb** [comment]
Ah whoops I missed that that documentation mistake existed outside of the README. A PR would be really appreciated on that front. 

I'll do some investigation into why only square videos play, I don't believe we've had that issue in the past.

**Comment by amini2nt** [comment]
Hi, how do you think it is now ?

**Comment by JackUrb** [comment]
Hi @amini2nt - sorry for the delay. I'm currently still investigating how and why this is happening, I don't have an update as far as when I'd predict it being done though.
