### ISSUE TITLE
rownames/column names automatically removing identical items in list 

### ISSUE THREAD

**Issue by vanzytay** [facebookresearch/visdom#21]
Hi,

I was wondering if there is anyway to allow the labels on the xaxis or yaxis (column names or rownames) to show duplicated items. I am trying to visualize a sentence via the heatmap and all my pad tokens are converted to a single pad token which changes the alignment.

Thanks!

**Comment by lvdmaaten** [comment]
I have been looking into this, and it appears that this is a "feature" of Plotly. 

I used the following test code:
```lua
local visdom = require 'visdom'{port = 8085}
local X = torch.randn(3, 2)
visdom:heatmap{
   X = X,
   options = {
      columnnames = {'d', 'd'},
      rownames = {'a', 'b', 'a'},
   },
}
```

Looking at the message that is being broadcast at https://github.com/facebookresearch/visdom/blob/master/py/server.py#L220 (`p`), everything still appears to be fine:
```
{u'title': u'', u'i': 0, u'contentID': '34ef28ecaef900', u'content': {'layout': {u'margin': {u'r': 60, u'b': 60, u't': 60, u'l': 60}}, 'data': [{u'zmax': 1.0054633722786, u'colorscale': u'Viridis', u'zmin': -1.4410649905944, u'y': [u'a', u'b', u'a'], u'x': [u'd', u'd'], u'z': [[-0.50443826056116, -0.55385051210768], [-0.52712315391279, 1.0054633722786], [-1.4410649905944, 0.50761805140936]], u'type': u'heatmap'}]}, u'command': u'pane', u'type': u'plot', u'id': u'pane_34ef28ecaef8ba'}
```

Which suggests this must be happening in the rendering. Indeed, others appear to have observed the same issue: http://stackoverflow.com/questions/40742473/plotly-seems-to-lose-labels-of-a-heatmap

I'm afraid I don't have a good work-around for this at the moment (other than not using duplicate labels).

**Comment by lvdmaaten** [comment]
Tracking this further here: https://github.com/plotly/plotly.js/issues/1516

**Comment by lvdmaaten** [comment]
I haven't tested it, but https://github.com/plotly/plotly.js/issues/1516#issuecomment-289136644 suggests the plot will render okay when you use `columnnames = {'d', 'd '}`.

**Comment by JackUrb** [comment]
Closing as this is a plotly issue and we don't have a clean workaround to alleviate it
