### ISSUE TITLE
Feature request: no error message when check_connect fails

### ISSUE THREAD

**Issue by TCPN** [facebookresearch/visdom#214]
I run visdom in python and I use Visdom.check_connection to check whether the server should be started before any other usage, but it always gives me some error messages like "Max retries exceeded with url: /win_exists" and makes the screen looks messy.
Could the error messages be not printed when the server is not on and Visdom.check_connect is called?

**Comment by JackUrb** [comment]
This is reasonable and not necessarily a hard fix. It would require adding a `quiet=false` parameter to the `_send` function:
https://github.com/facebookresearch/visdom/blob/c1ffcb3d5175f41a7fff85f7e9bed3914ac62703/py/__init__.py#L247
and then only printing on line 267 if `quiet` is false. Then `win_exists_wrap` can call `_send` with `quiet = true`.

I'm likely not going to be able to jump into actually putting this in code immediately, so feel free to make the changes and submit a PR if you'd like them in more quickly.
