### ISSUE TITLE
Structured placement of plots and images

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/visdom#218]
When I have several experiments running, my visdom dashboard can become very messy. And I usually end up hunting down new plots and having to move them around to declutter.

Would it be possible to divide the dashboard into - maybe - a grid made of a set of cells and then assign each window to a cell ?

That way we can know which cell each plot goes to.
Would this feature be easy to add ?

I think it is very useful!
Thanks!

**Comment by JackUrb** [comment]
When you have multiple experiments running you could declutter by using the different environments feature. This will ensure that each environment only has the relevant plots. Have you tried using environments to solve your clutter issue?

**Comment by IssamLaradji** [comment]
Thanks, that works great! :)
Is there a way I can programmatically create an environment ?
For example, if i run this and environment `debug` does not exist, nothing is display,

`vis.images(imgs, opts=options, nrow=nrow, win=win, env="debug")`
Is there a way I could programmatically create an environment if it does not exist ?

Thanks!

**Comment by lvdmaaten** [comment]
If the `debug` environment does not yet exist, your code sample will create that environment. You may have to refresh the visdom page in your browser to see the new environment appear in the dropdown box.
