### ISSUE TITLE
surf plot feature enhancement.

### ISSUE THREAD

**Issue by HenryZhou7** [facebookresearch/visdom#220]
Is there a way to continuously update on one window instead of using a new window every time I update the plot?
```
window = None
for ...:
    window = viz.surf(x, update='new', win=window)
```
This code would still generate a lot of different windows.

**Comment by lvdmaaten** [comment]
Doesn't `window = viz.surf(x, update='replace', win=window)` work?

**Comment by HenryZhou7** [comment]
```
>>> from visdom import Visdom
>>> import numpy as np
>>> x = np.zeros((10, 10))
>>> win = None
>>> viz = Visdom()
>>> win = viz.surf(X=x, win=win)
>>> win
>>> win is None
True
>>> 
```
It seems that `viz.surf` is always returning None.

**Comment by HenryZhou7** [comment]
It turned out that it is the matter of using out-dated version.
By the way, it doesn't need to have `update='replace'`.
