### ISSUE TITLE
Programmatically remove a specific plot from the figure

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/visdom#221]
Thanks for all the help you have given me! The following is an issue I often face when running multiple experiments.

Is it possible to programmatically remove one of the plots in a figure, without removing the whole plot ? Perhaps using the plot's legend name ?

Let's say I am comparing the performance of two algorithms `alg1` and `alg2` as in the figure below.

![image](https://user-images.githubusercontent.com/3382128/33806896-918f6ac0-dd9c-11e7-96c4-d9672ad5ac8a.png)

Now I would like to re-run `alg2` at a different initialization and i would like to plot its performance on the figure above. However, I would like to remove the old `alg2` plot and keep the `alg1` plot. Is that possible ?

Thanks!

**Comment by lvdmaaten** [comment]
There is currently no function that "removes" a single trace from a line plot. However, to achieve the behavior you describe, can't you simply keep the data underlying `alg1`plot around in your code, and push this data together with the new `alg2` data to a new (or the current) visdom window?

**Comment by IssamLaradji** [comment]
that would be difficult if I am running, say, 10 experiments independently - it might require synchronization of the read and write operations of the `.pkl` files containing the performace/epoch data of each algorithm.

Would it be easy to implement code that can remove a trace ? or is that something too embedded within `plotly`? I am thinking of adding such code to the lib and possibly add a pull request if the owners are happy with the functionality.

**Comment by lvdmaaten** [comment]
It is certainly possible to add functionality that removes traces. You can look at the code that adds traces to a line plot for guidance on how to implement it.
