### ISSUE TITLE
Window on the page won't resize

### ISSUE THREAD

**Issue by Seraphli** [facebookresearch/visdom#226]
If I set the width and height, the plotly window will stay in that size and cannot be resized, even though the outer window can be resized using drag. And another problem is the plot can't be zoom in when the data are appended.
```
import visdom
import numpy as np
import time

vis = visdom.Visdom()
assert vis.check_connection()

win = vis.line(
    X=np.array([0]),
    Y=np.array([0]),
    opts=dict(title='Random!', width=200, height=200)
)
for _ in range(5000):
    vis.line(
        X=np.array([_]),
        Y=np.array([_ * 2 + np.random.randint(100)]),
        win=win,
        update='append'
    )
    time.sleep(0.1)
```

**Comment by JackUrb** [comment]
The easiest solution here is to implement the enhancement described as in https://github.com/facebookresearch/visdom/issues/183, as plotly without a specified width and height just fills the size of the container. Rather than size the plot, we should size the container instead.
