### ISSUE TITLE
update='append' does not work anymore

### ISSUE THREAD

**Issue by chenyuntc** [facebookresearch/visdom#233]
simple code to reproduce
```Python
import numpy as np
import visdom
vis = visdom.Visdom()
vis.line(np.arange(3),np.arange(3),win='test')
vis.line(np.arange(3),np.arange(3)+3,win='test',update='append')
```
It used to work, but I update visdom and it won't work any more.
I guess the problem comes from [here](https://github.com/facebookresearch/visdom/blob/master/py/server.py#L422)

If I change it to :
```Python
        name = args.get('name')
        append = args.get('append')
        if name is None and append is None:
            return p  # we only updated the opts or layout
``` 
It works again. But I don't know whether it was the right way.

Since I use it a lot in my [project](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/master/util/vis_tool.py#L209-L213) and many other, I really hope it could be fix eariler.  

Thanks for your great job to create such a lightweight and powerful visulization tool!

**Comment by JackUrb** [comment]
Ack sorry about this bug, going to push a fix right now. Pretty close to what you had, but I'm going to case it on the existence of `new_data` rather than append, which will fix appends and updates
