### ISSUE TITLE
line append

### ISSUE THREAD

**Issue by QinZiwen** [facebookresearch/visdom#238]
I want to use line's update=append parameter, like:
```
import visdom
import numpy as np

viz = visdom.Visdom()

win = viz.line(
    X=np.column_stack((np.arange(0, 10), np.arange(0, 10))),
    Y=np.column_stack((np.linspace(5, 10, 10), np.linspace(5, 10, 10) + 5))
)

viz.line(
    X=np.column_stack((np.arange(10, 20), np.arange(10, 20))),
    Y=np.column_stack((np.linspace(5, 10, 10), np.linspace(5, 10, 10) + 5)),
    win=win,
    update='append'
)
```
But second line do not showing.
![screenshot from 2018-01-01 10 48 01](https://user-images.githubusercontent.com/15364705/34465305-4c76e2f0-eee1-11e7-996e-15b7316bb081.png)

**Comment by dengbo22** [comment]
I meet the same problem. have you solved it?

**Comment by QinZiwen** [comment]
sorry, no

**Comment by JackUrb** [comment]
Looking into this now

**Comment by JackUrb** [comment]
What version of Visdom are you running on? The demo reflects features that are not yet on Pip, but can be used if you install from source.

**Comment by chengyangfu** [comment]
Same problem here. It seems the "append" function of viz.line does not work now. 
P.S. I use the pip version now.

**Comment by lvdmaaten** [comment]
The demo uses features that are not yet in the pip-version of visdom. Please install visdom from source if you need these features. See [the relevant question here](https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md) for details.

**Comment by chengyangfu** [comment]
Thanks! The repository version works now!

**Comment by QinZiwen** [comment]
@JackUrb My version of visdom is 0.1.6.5 using pip install.

**Comment by JackUrb** [comment]
@QinZiwen try following the instructions on the main README for installing from source. Not all features in the demo have been put into the pip version.
