### ISSUE TITLE
ERROR:root:Error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)

### ISSUE THREAD

**Issue by at-thirty** [facebookresearch/visdom#251]
python -m visdom.server
Downloading scripts. It might take a while.
ERROR:root:Error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) while downloading https://cdn.plot.ly/plotly-latest.min.js
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:8097 [BUT THE SERVER HAS NOT BEEN STARTED]

**Comment by at-thirty** [comment]
I'm using Python 2.7.10, MacOS 10.12.6

**Comment by lvdmaaten** [comment]
Can you try installing the JavaScript dependency manually per the instructions [here](https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md)?

**Comment by lvdmaaten** [comment]
Closing this because we do not have a repro, and the issue has not received comments for three weeks. Likely a firewall / networking issue.

**Comment by gitanupam** [comment]
This could be related to the recent deprecation of TLS 1.0 and 1.1 by Python.org sites. This SO post may help: https://stackoverflow.com/q/49768770/1526703

**Comment by Zhenye-Na** [comment]
Hi Visdom team,

I have met a similar problem as **at-thirty** mentioned above:


```
$ visdom
Downloading scripts. It might take a while.
ERROR:root:Error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) while downloading https://cdn.plot.ly/plotly-latest.min.js
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:8097
```

After search in the given link from **gitanupam** . I have been trying upgrade my `OpenSSL` and other libraries. However `Visdom` is not working when I trying to run the given example in the `README` file, specifically:

```python
import visdom
import numpy as np
vis = visdom.Visdom()
vis.text('Hello, world!')  # this line is working fine
vis.image(np.ones((3, 10, 10))) # this line does not work, no corresponding plot
```

I have already tried installing the JavaScript dependency manually as mentioned by **lvdmaaten**. However, I have been searching for visdom tutorial and I found that visdom integrated with matplotlib is working fine except the size of plots cannot be changed dynamically.

I am using Python3 and mac os 10.11

```
$ python3 -V
Python 3.5.4
```


Thanks in advance!

Best,
Zhenye
