### ISSUE TITLE
How to plot the same histogram as visualDL in visdom?

### ISSUE THREAD

**Issue by KeyKy** [facebookresearch/visdom#255]
How to plot histogram just like the histogram in https://github.com/PaddlePaddle/VisualDL

**Comment by JackUrb** [comment]
Hi @KeyKy, our normal plotting backend (plot.ly) doesn't support that kind of tiered histogram. We'd be open to having the VisualDL folks help provide us a pane type that can leverage the kind of data their logs use, however it's probably not appropriate for us to implement their frontend here without their approval or assistance.

**Comment by JackUrb** [comment]
Closing as it's been two weeks of no response and we're not planning to integrate this feature unless VisualDL wants to help support it
