### ISSUE TITLE
How to specify the env for a figure?

### ISSUE THREAD

**Issue by hashbangCoder** [facebookresearch/visdom#26]
>One can also specify the env to which the visualization should be added

I couldn't find a suitable option for the `vis.Visdom()` object.

**Comment by ajabri** [comment]
Hi @hashbangCoder,

The `env` parameter is specified with the figure call, not the creation of the visdom client, e.g:

```
import visdom
vis = visdom.Visdom()
vis.text('Hello, world!', env='helloworld')
```
