### ISSUE TITLE
`name` parameter is not used on first plotted line

### ISSUE THREAD

**Issue by 0phoff** [facebookresearch/visdom#262]
When plotting a line with the ``vis.line()`` function, one can specify a ``name`` for a trace.
This works fine when `` 'appending' `` new lines, but does not work for the first line you plot in a window.

One can work around the bug by adding a ``legend`` entry to the options, but this is a dirty hack imo...
The reason this is irritating is because this does not allow for a consistent API for updating/removing traces.

# Reproducing bug
```python
import visdom
import numpy as np

vis = visdom.Visdom()
vis.line(np.array([1,2,3]), np.array([0,1,2]), win='my_window', name='custom_trace', opts={'showlegend':True})
# The line will have '1' as name in stead of 'custom_trace'
```

**Comment by JackUrb** [comment]
Ah this is definitely fixable - hadn't thought about the parity here between create and append. Will put together a fix!
