### ISSUE TITLE
Feature Request : API to pull scalar data

### ISSUE THREAD

**Issue by jramapuram** [facebookresearch/visdom#266]
Tensorboard allows to curl down the data from specific plots (scalars particularly).
Not sure about the plotly blockers, but would be nice feature to gather data from 100s of envs.

**Comment by lvdmaaten** [comment]
Dumping the raw data in JSON format or something like that should be totally fine.

**Comment by JackUrb** [comment]
I can implement some GET requests on the server that will allow this. As visdom is now supporting callbacks from webclient events I can imagine there will be growing use cases for this kind of functionality.
