### ISSUE TITLE
AttributeError: 'Visdom' object has no attribute 'register_event_handler'

### ISSUE THREAD

**Issue by roozbehm** [facebookresearch/visdom#268]
Hi,
I get the following error when I run the python demo:
Traceback (most recent call last):
  File "example/demo.py", line 49, in <module>
    viz.register_event_handler(type_callback, callback_text_window)
AttributeError: 'Visdom' object has no attribute 'register_event_handler'

**Comment by lvdmaaten** [comment]
Most likely, you are using the most recent demo against an older version of visdom. Please upgrade visdom, or do an install from source via `pip install -e`. Please re-open this if that does not resolve your issue.

**Comment by roozbehm** [comment]
I tried pip install visdom --upgrade, but still the same error

**Comment by JackUrb** [comment]
Hi @roozbehm - We don't have a regular release cycle to pip as we contribute to visdom on the side of our main work and only push to pip once we've had an opportunity to become totally secure in our changes. Please upgrade using `pip install -e .` or `easy_install .` to install visdom from source rather than from pip.

**Comment by nadieh** [comment]
I install with pip install -e and easy_install . and still have the same issue

**Comment by JackUrb** [comment]
@nadieh - what version of visdom are you running?

**Comment by nadieh** [comment]
I tried with  version=0.1.6.3 and version=0.1.8.5

**Comment by nadieh** [comment]
This is the error I have AttributeError: module 'visdom' has no attribute 'Visdom'

**Comment by JackUrb** [comment]
This is not the issue above, as all versions of visdom should have the Visdom object.

Please open a new issue, and in it put that full error text, as well as the output of:
```
import visdom
print(dir(visdom))
```

**Comment by omid-ghozatlou** [comment]
> This is not the issue above, as all versions of visdom should have the Visdom object.
> 
> Please open a new issue, and in it put that full error text, as well as the output of:
> 
> ```
> import visdom
> print(dir(visdom))
> ```

I got this error and the output of print(dir(visdom)) :
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
