### ISSUE TITLE
Clear environment programmatically?

### ISSUE THREAD

**Issue by dizcza** [facebookresearch/visdom#271]
I don't see any method in `Visdom` class that would clear the current env. The functional is already implemented in UI, so it won't be hard to add a simple `clear` method in visdom class.
Use case: creating visdom object with a custom `env` that is already present/dirty. I'd like to clear it before plotting a new stuff.

**Comment by JackUrb** [comment]
Yeah I can definitely see this being useful, though the UI implementation is separate from what the visdom class would be able to handle (as the UI has a notion of the current env state, and can just call close on all of the windows). The visdom class doesn't have that state stored locally, so it doesn't know what to close. Still, this is doable with a new handler, so I'll look into a good solution.

**Comment by JackUrb** [comment]
Ah wait it appears I got ahead of myself - we've already exposed this functionality as a separate handler on the server-side 😅. You can use `visdom.close(env=envID)` to close all the panes in an environment, and `visdom.close(win=winID, env=envID)` to close a specific pane in an environment.

**Comment by lvdmaaten** [comment]
And documented it, too! ;)

https://github.com/facebookresearch/visdom#visclose
