### ISSUE TITLE
Env selection by URL path

### ISSUE THREAD

**Issue by timmeinhardt** [facebookresearch/visdom#273]
For a more clear structure and an easier way to refresh the visualisations in an environment I suggest to make an environment selection based on the URL possible. Selecting an environment called `my_favorite_env` should change to URL to for example `http://localhost:8098/my_favorite_env` and entering or refreshing this URL should directly open this environment.

I have a use case where I create and destroy many windows and sometimes those keep hanging around until I refresh the page. But then I always have to reselect the environment.

**Comment by lvdmaaten** [comment]
This feature used to be supported but is currently broken. Fixing this is on our to-do list.

**Comment by JackUrb** [comment]
The infrastructure for this currently does exist - the domain was `http://localhost:8098/envs/my_favorite_env` but something broke along the way (unsure when). The existing 'support' is somewhere in the `EnvHandler` in the server but I haven't had a chance to find the bug yet:
 https://github.com/facebookresearch/visdom/blob/2a390d66326a0d62b803d4b883c745c7c52e52f9/py/server.py#L690
