### ISSUE TITLE
Append different plot types in one window

### ISSUE THREAD

**Issue by ehsanomidi** [facebookresearch/visdom#278]
When I try to append a scatter plot to a line plot, my scatter plot is drawn with lines which is obviously not desired.
Sample code:

    Y = np.linspace(-5, 5, 100)
    winLine=viz.line(
        Y=Y * Y,
        X=Y,
        opts=dict(markers=False),
    )

    viz.scatter(
        X=np.random.rand(25, 2),
        Y=(np.random.randn(25) > 0) + 1,
        win=winLine,
        opts=dict(
            markersize=10,
            markercolor=np.floor(np.random.random((2, 3)) * 255),
        ),        
        update='append'
    )

**Comment by JackUrb** [comment]
Hi @ehsanomidi - this is not quite the way that the 'update' field is supposed to be used. Currently you can only use `scatter`'s update to update scatter plots with more scatter traces and `line`'s update to update line plots with more line traces.

You will be able to override this behavior once #275 is in however by appending a line trace using the `line` function's update but setting `'traceopts': {'mode': 'markers'}` in opts, as we process line plots as scatter plots in `'line'` mode so if you override that with `'markers'` mode that trace will be handled as a scatter plot.

**Comment by JackUrb** [comment]
You can also view #155 for a method to implement this behavior right now by using the generic send functionality

**Comment by JackUrb** [comment]
This is now supported via both #275 and #155, closing.
