### ISSUE TITLE
The line doesn't show in visdom

### ISSUE THREAD

**Issue by Cheneng** [facebookresearch/visdom#284]
Always a blank board in the panel. 
The line doesn't show. 
And I testing the scatter, the same blank board.
How to solve? Thanks.

> python3.5 
> visdom 0.1.7

```
x = torch.arange(0, 30, 0.1)
y = torch.sin(x)
vis.line(X=x, Y=y, win='sinx', opts={'title': 'y=sin(x)'})
```

**Comment by JackUrb** [comment]
Hi @Cheneng - using your exact setup I get the following:
![screen shot 2018-02-27 at 11 30 29 am](https://user-images.githubusercontent.com/1276867/36740865-ad47b1b6-1bb1-11e8-96f9-91c0f77df475.png)

It's possible you're not getting the correct dependancies however, can you check the javascript console logs to ensure there are no errors there? You can also try updating to visdom 0.1.7.2 which I believe has better handling for dependency downloads by cloning the repo and using `easy_install .`

**Comment by Cheneng** [comment]
@JackUrb Oh，Thanks。I update the visdom version to 0.1.7.2 and found the error in downloading the plotly.min.js and following this [link](https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md)
then solve the question!
Thanks a lot!
