### ISSUE TITLE
[Feature Request] Add slide bars to show multiple images over time

### ISSUE THREAD

**Issue by moskomule** [facebookresearch/visdom#286]
Hi, now I'm using both visdom and TensorBoard. Is it possible to add slide bars as the attached image below to show multiple images over time? Now, if you display GANs' generated images at each epoch, for example, the window is filled with them.

![screenshot-2018-3-3 tensorboard](https://user-images.githubusercontent.com/11806234/36930437-e81f2bb8-1ee3-11e8-87da-cc81a34c503f.png)

**Comment by JackUrb** [comment]
Hi @moskomule - a workaround to allow this kind of thing to work is already coming together in the short term through adding arbitrary sliders which you can attach callbacks to. This would allow you to keep a local array of images and then push the one you want to see based on the current value of the slider.

After that's together, a more integrated solution (where you can post multiple images to a 'multi-image-pane' or something) may follow.
