### ISSUE TITLE
Feature Request: Animation of sequences of images

### ISSUE THREAD

**Issue by zuoxingdong** [facebookresearch/visdom#29]
Sometimes we would like to visualize the evolution of feature maps or kernels. It is interesting to be able to produce an animation given the sequence of such images over time.

**Comment by ajabri** [comment]
Good idea!

**Comment by lvdmaaten** [comment]
I'm working on a PR for this.

**Comment by lvdmaaten** [comment]
Implemented by https://github.com/facebookresearch/visdom/commit/f00207e35680e97414f8e672d3eab63589ad8303.
