### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by Allloginsbusy** [facebookresearch/visdom#293]
In python code I tried to set proxy settings/
vis = visdom.Visdom(proxy=' ')
Then I tried to download js libs locally and see this error.

WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
MathJax.js:32:5
Ошибка карты кода: request failed with status 404
URL ресурса: http://127.0.0.1:8097/static/fonts/layout_bin_packer?v=6c46683ed70fbb1443caf3531243836d
URL карты кода: layout-bin-packer.js.map
[Подробнее]
Ошибка карты кода: request failed with status 404
URL ресурса: http://127.0.0.1:8097/static/js/react-grid-layout.min.js?v=062d847cc21a7fc3df5557aa91b4dbf5
URL карты кода: react-grid-layout.min.js.map
[Подробнее]
Ошибка карты кода: request failed with status 404
URL ресурса: https://unpkg.com/layout-bin-packer@1.2.2
URL карты кода: layout-bin-packer.js.map
[Подробнее]
Ошибка карты кода: request failed with status 404
URL ресурса: http://127.0.0.1:8097/static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219
URL карты кода: bootstrap.min.css.map

 What I must do to solve the problem?

**Comment by JackUrb** [comment]
If you're using some proxy settings that seem to be preventing the required sources from downloading, we suggest downloading the scripts locally first as described in [the contribution guide](https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md).

**Comment by Allloginsbusy** [comment]
I install visdom. I have the same problem https://github.com/facebookresearch/visdom/issues/111 
I tried to load js libs to js directory and change index.html, but see error in 1 post.

**Comment by JackUrb** [comment]
You shouldn't need to change anything in index.html after you download the dependancies manually

**Comment by Allloginsbusy** [comment]
I load all manually like in https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md,but see error.

WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
mathjax-MathJax.js:32:5
Ошибка карты кода: request failed with status 404
URL ресурса: http://localhost:8097/static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219
URL карты кода: bootstrap.min.css.map

**Comment by JackUrb** [comment]
Are you running from a `pip install` of the pypi version, or an `easy_install .` directly from the source here on github? I suspect that the manual downloads don't work for the pip version

**Comment by Allloginsbusy** [comment]
I install by pip. Now I try to install manually by python3 setup.py install. When I use wget I see that most of all is ok,but  smth is bad. 

zsh: no matches found:  https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_SVG
static/fonts/glyphicons-halflings-regular.eot: No such file or directory
static/fonts/glyphicons-halflings-regular.woff2: No such file or directory
static/fonts/glyphicons-halflings-regular.woff: No such file or directory
static/fonts/glyphicons-halflings-regular.ttf: No such file or directory
static/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular: No such file or directory

Then I see  in browser log:
WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
mathjax-MathJax.js:32:5
Ошибка карты кода(Card code error in English): request failed with status 404
URL ресурса(resource): http://localhost:8097/static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219
URL карты кода(Card code error in English): bootstrap.min.css.map

**Comment by JackUrb** [comment]
Try pulling MathJax from `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_SVG` instead to begin with, and then we'll see what else is an issue. You'll need to make sure you have created a `static/fonts` directory before you run the wget script, I also forgot to mention that.

**Comment by Allloginsbusy** [comment]
After preload js and create fonts dir I see this error on browser log.
What problem can happend?

SyntaxError: unexpected token: numeric literal
[Подробнее]
MathMenu.js:2:10
SyntaxError: unexpected token: numeric literal
[Подробнее]
MathZoom.js:2:10
Ошибка карты кода: request failed with status 404
URL ресурса: http://localhost:8097/static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219
URL карты кода: bootstrap.min.css.map
[Подробнее]

**Comment by JackUrb** [comment]
do you have a `bootstrap.min.css` file in your `static/css` directory?

**Comment by Allloginsbusy** [comment]
Yes, I have.

**Comment by JackUrb** [comment]
can you access it at `http://localhost:8097/static/css/bootstrap.min.css`?

**Comment by Allloginsbusy** [comment]
Yes, I can

**Comment by JackUrb** [comment]
Alright all three of those errors are actually expected at this point - I don't know why visdom doesn't seem to be functioning for you.

**Comment by Allloginsbusy** [comment]
This error is new and appeared after add https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_SVG in js.


SyntaxError: unexpected token: numeric literal
[Подробнее]
MathMenu.js:2:10
SyntaxError: unexpected token: numeric literal
[Подробнее]
MathZoom.js:2:10

**Comment by JackUrb** [comment]
That's the one I was referring to - it happens to me in the current build as well but visdom still functions.

**Comment by Allloginsbusy** [comment]
Ok, so problem in css.

**Comment by JackUrb** [comment]
Yeah, the version of bootstrap that you got is referring to a file that we don't request access for. For a temporary fix you can remove the `/*# sourceMappingURL=bootstrap.min.css.map */` line from your `bootstrap.min.css` file

**Comment by Allloginsbusy** [comment]
Ok, I edit file in nano and see in browser, but there are no changes. What can be problem? File is static/cs/bootstrap.min.css

**Comment by JackUrb** [comment]
like the line already doesn't exist? Or making the change in the file doesn't appear when you load it in web. If it's the latter, run `python setup.py install` again

**Comment by Allloginsbusy** [comment]
It help. Now I haven't problem in browser log not to mention MathMenu.js:2:10  . I try use example in docs, but It doesnt show anything. 
Here is my code.
vis = visdom.Visdom(proxy='http://proxy.thf:3129')
vis.text('Hello')
vis.image(np.ones((3, 10, 10)))
vis.save(['1'])
 What kind of problem can happend?

**Comment by JackUrb** [comment]
Are any errors coming up in your python window? 

This may be related to https://github.com/facebookresearch/visdom/issues/279. I'm looking into establishing websockets over proxy, though there should also be a fallthrough if that isn't working.

**Comment by JackUrb** [comment]
Finally figured this one out - you'll need to be using the proxy that's appropriate for your setup to download the scripts, and you may need to also use one to run the python client as well.

To download the scripts properly, you can run:
```
from Visdom import server
server.download_scripts(
        proxies={
            'http': <HTTP_PROXY>,
            'https': <HTTPS_PROXY>,
        },
)
```

To run the client through the proxy as well, as of #314 you can pass `http_proxy_host` and `http_proxy_port` parameters to your visdom client (rather than the `proxy` argument) and these will be properly used

**Comment by jianghaojun** [comment]
a

**Comment by jianghaojun** [comment]
@Gerkam Hi, i encountered the same problem!

SyntaxError: unexpected token: numeric literal
MathMenu.js:2:10
SyntaxError: unexpected token: numeric literal
MathZoom.js:2:10

And i followed the @JackUrb 's suggestion to remove the line /*# sourceMappingURL=bootstrap.min.css.map */ before i load it to web, but it didn't help. Then i also tried to run python setup.py install again and remove the line, but it still didn't work. 

Could you tell me how to solve the problem? @Gerkam

**Comment by JackUrb** [comment]
"SyntaxError: unexpected token: numeric literal
MathMenu.js:2:10
SyntaxError: unexpected token: numeric literal
MathZoom.js:2:10" is a non-error, visdom works fine when reporting this. Have you followed the instructions in the contributing guidelines? What actually is your problem? If the only shared symptom is mathMenu and MathZoom please open a new issue.

**Comment by michaelschleiss** [comment]
> To run the client through the proxy as well, as of #314 you can pass http_proxy_host and http_proxy_port parameters to your visdom client (rather than the proxy argument) and these will be properly used

I get the following error message when i try to connect to visdom server "failed CONNECT via proxy status: 403"
So how do I pass http_proxy_host and http_proxy_port to the client exactly?

**Comment by JackUrb** [comment]
Hi @michaelschleiss - As of #538 `proxies` is the correct argument to use a proxy from the client.
