### ISSUE TITLE
how to plot multiple line  seperately on one window 

### ISSUE THREAD

**Issue by lixinsu** [facebookresearch/visdom#297]
I use visdom to plot train loss, I start many processes in different configurations to train model, and I want to plot multiple curve of train loss  in one window for comparing different model to choose the best model parameters,Could I use visdom to do this?

**Comment by JackUrb** [comment]
Hi @lixinsu - do you mean you want to plot multiple lines separately in different plots in the same window? (something like matlab's subplots?) Or plot multiple traces on the same plot in a window? 

We don't support the former currently, but to get the desired behavior for that I'd suggest using multiple windows with a tag in the titles, this way you can filter by that tag and see them all. 

To plot multiple curves on the same axes you can determine the window name you want to use, and then use `viz.line(... win=<window_name>, update='append', name=<trace_name>)` for each trace.

Alternately, after https://github.com/facebookresearch/visdom/pull/283 is in you can plot all the relevant data for each experiment in its own env and then use the compare features to show the data on the same plot without needing to plot from different places into the same window.

**Comment by lixinsu** [comment]
thanks, I just ask for ploting multiple curves on the same axes, but I found that the code
 below `viz = Visdom(port=8093)
# line updates
win = viz.line(
    X=np.column_stack([np.arange(0, 1) for i in range(10)]),
    Y=np.column_stack([np.arange(0, 1) for i in range(10)]),
    win="test"
)

viz.line(
    X=np.arange(1, 38),
    Y=np.random.randn(37),
    win="test",
    name='6',
    update='append',
)

viz.line(
    X=np.arange(1, 38),
    Y=np.random.randn(37),
    win="test",
    name='11',
    update='append',
)
`
generate the axes as following 
![22101](https://user-images.githubusercontent.com/15691697/37407951-0773e490-27d6-11e8-8ca5-db8665372e30.png)

the second line ,I name it as 11, but in the graph it names 1?

**Comment by lixinsu** [comment]
is it a bug ,or I make a mistake in the usage

**Comment by JackUrb** [comment]
Are you using the pypi version of visdom or the one installed from source here? The naming issue is fixed in version 0.1.7.1

**Comment by JackUrb** [comment]
That version hasn't been released yet as it breaks some behavior for proxies and I'm waiting to fix it before I release. You can use `easy_install .` or `python setup.py install` after cloning the git repo to install from source.

**Comment by lixinsu** [comment]
I install visdom (0.1.7)

**Comment by lixinsu** [comment]
thanks

**Comment by lixinsu** [comment]
I install 0.1.7.2 from master branch, but the program still give the above result

**Comment by JackUrb** [comment]
As in it's giving the second trace the name "1"? What happens if you enable a legend?

**Comment by Eyshika** [comment]
@JackUrb 
I am trying to plot multiple lines. There are four legends, still it is plotting only 1. what is the reason ?
`self.plot_data['X'].append(epoch + counter_ratio)
    self.plot_data['Y'].append([errors[k].cpu().data.numpy() for k in self.plot_data['legend']])
print(list(np.stack([np.array(self.plot_data['X'])] * len(self.plot_data['legend']), 1).ravel()))
print(list(np.array(self.plot_data['Y']).ravel()))
   self.vis.line(
X=list(np.stack([np.array(self.plot_data['X'])] * len(self.plot_data['legend']), 1).ravel()),
             Y=list(np.array(self.plot_data['Y']).ravel()),
            opts={
              'title': self.name + ' loss over time',
'legend': self.plot_data['legend'],
'xlabel': 'epoch',
'ylabel': 'loss'}, win=self.display_id, update = 'append')  `

> X =[4.6124401913875595, 4.6124401913875595, 4.6124401913875595, 4.6124401913875595]  
> 
> Y = [1.2601129, 29.566483, 0.35748744, 0.7072838]
