### ISSUE TITLE
Text labels in scatterplot not behaving as expected

### ISSUE THREAD

**Issue by mranzinger** [facebookresearch/visdom#301]
I am trying to create a scatterplot visualization of the embedding space for my vision model by looking at the t-SNE projections of a few classes. As far as the plotting goes, I seem to have everything wired up. In this attached image, you can see that I'm looking at a plot of dog and cat embeddings.
<img width="832" alt="screen shot 2018-03-19 at 7 29 28 pm" src="https://user-images.githubusercontent.com/6589108/37630753-e4a02382-2bab-11e8-9f59-f874fe9163f9.png">
The problem I am having is that the 'textlabels' that I have supplied the plot function are not showing up. My goal is to show the image id for the given data point, so that I can dive deeper into data points that are not where I'd expect them to be (e.g. a dog image deep within the cat cluster). I would expect the mouseover to show either the class and my supplied label, or at the very least, my supplied label. In the current implementation, it's instead only showing the class.

The code supporting my visdom plot:
```
print('Computing t-SNE')
# This will produce the (N, 2) coordinate matrix
vis_pos = bh_sne(all_vecs)
# This is the (N,) matrix of labels for each point
vis_lab = numpy.concatenate([numpy.repeat(i+1, v.shape[0]) for i, v in enumerate(q_vecs)])
print('Done')
print('Plotting...')
opts = {
    'legend': q_list,
    'title': args.plot,
    # This is a python list of string ids for each image (size N)
    'textlabels': all_ids,
    'mode': 'markers+text'
}
print('vis_pos', vis_pos.shape)
print('vis_lab', vis_lab.shape)
print('all_ids', len(all_ids))
vis.scatter(X=vis_pos, Y=vis_lab, win=args.plot, opts=opts)
```

Sample Output:
```
Plotting...
vis_pos (2000, 2)
vis_lab (2000,)
all_ids 2000
```

Both my client and server version of visdom is 0.1.7

I was looking into the source code (master), and there appears to be a few bugs in at least the client code. I'll try to outline what I think I'm seeing, but my workaround also doesn't work.
In this block:
https://github.com/facebookresearch/visdom/blob/4d9f7c0e6a896943707fd255e0d46bc6798a42e3/py/__init__.py#L838-L872

It appears to be iterating over each class, and preparing the markers separately for the data for each respective class. The problem is, the function doesn't also select the relevant `textlabels` for the given class on line 854.

The apparent workaround to this, just to see if I could get the textlabels to show was to set all of the points to the same class, which should cause the supplied labels to again align with the points. The problem is, I still don't see my supplied labels, as shown.
<img width="829" alt="screen shot 2018-03-19 at 7 47 35 pm" src="https://user-images.githubusercontent.com/6589108/37631250-6e554362-2bae-11e8-8a44-d74a9915f747.png">

Is there a setting that I am missing, or a known bug for this? I'm also happy to dig further into this if someone can point me in the rough direction of the server code that's making the plotly calls.

Thanks

**Comment by JackUrb** [comment]
Hi @mranzinger - Does the demo for text labels work? This is properly rendered as per the [plotly docs](https://plot.ly/javascript/line-and-scatter/) on my machine.
```
viz.scatter(
    X=np.random.rand(10, 2),
    opts=dict(
        textlabels=['Label %d' % (i + 1) for i in range(10)]
    )
)
```
Also I hadn't really thought about the labelling issue in the past for multiple traces (unsure what the right way to go about that would be, perhaps it could be improved by reshaping to ensure it has a 'trace dimension' and then use `textlabels[i]` for the correct trace `i` during the construction. That would be an appreciated fix). 

The workaround without the fix would be to create a scatterplot with just one of the traces and then append the other trace using `update=append` with a given distinct trace name (cats vs dogs), though the fix probably would make more complicated examples easy to work with.

**Comment by herrmann** [comment]
Same here, also using version 0.1.7 on both sides.

**Comment by JackUrb** [comment]
Hi @herrmann - can you try to compile from source and see if the issue is still there?

**Comment by cympfh** [comment]
↑ 0.1.7 is too old to use textlabels. BTW I want `.__version__`.

**Comment by JackUrb** [comment]
@cympfh fixed this in #347. (Thanks again!)

**Comment by dizcza** [comment]
Is it possible to use `textlabels` with lines, not scatter?

**Comment by JackUrb** [comment]
@dizcza yeah it should technically be possible, you need to change `opts['mode']` to get the behavior you want. I believe `opts['mode'] = 'lines+markers+text'` will display the text on the markers without hover, `opts['mode'] = 'lines+markers'` will only display the text on hover. You do need to use `textlabels` in both cases.

**Comment by dizcza** [comment]
@JackUrb it works, thank you. Following you, I spot a bug when updating a scatter plot with a single point that has a textlabel. Code to reproduce

```
viz.scatter(X=np.random.rand(10, 2), win='scatter', opts=dict(
    textlabels=[f"Epoch {i}" for i in range(10)],
))
viz.scatter(X=np.random.rand(1, 2), win='scatter', opts=dict(
    textlabels=["Epoch 10"],
), update='append')
```
Traceback:
```
  File "/home/dizcza/anaconda3/envs/embsdr_cpu/lib/python3.6/site-packages/visdom/__init__.py", line 1064, in scatter
    assert len(L) == X.shape[0], \
TypeError: len() of unsized object
```
Source part:
```
L = opts.get('textlabels')
if L is not None:
    L = np.squeeze(L)
    assert len(L) == X.shape[0], \
        'textlabels and X should have same shape'
```

I don't think `L = np.squeeze(L)` is needed. `textlabels` is just a list anyway.
Should I fire the issue?

**Comment by JackUrb** [comment]
IIRC the `squeeze` is related to backward support for the lua version. Instead you'll need to deal with the special case of not squeezing when L only has one element.

**Comment by dizcza** [comment]
@JackUrb so how do I do so? Not squeezing when L only has one element. Numpy squeezes it to a scalar not matter how you represent it.
