### ISSUE TITLE
Too much data transfer when logging to lots of environments

### ISSUE THREAD

**Issue by adityab** [facebookresearch/visdom#302]
I'm often running experiments where ~20 environments are actively updated, with ~6 plots in each. My logging frequency is very high --- about 3 times a second for each environment.

Previously, visdom's client side would only retrieve data whenever it needed to render --- i.e., when selecting an environment from the dropdown, only its data would be downloaded.

I think that at some point in the past ~3 months (I could be wrong), visdom underwent a frontend update such that data from all environments is downloaded client-side all the time.
This update makes it impossible to use the web UI, as everything is frozen due to high CPU usage (presumably from downloading and de-serializing the many streams of data being logged).

**Comment by JackUrb** [comment]
Hi @adityab - I'm sorry that you're running into this issue. I'm not sure which of the features might've added so much additional throughput over what was already being sent 3 months ago that visdom has become unusable. It certainly shouldn't need to be syncing all the time, so it's possible there was some oversight on my part during one of the more recent develoments. I'll investigate and see where I can cut it down!

**Comment by JackUrb** [comment]
Hi @adityab - sorry for being so slow on this, but I think I've traced this one down, can you comment out this line: https://github.com/facebookresearch/visdom/blob/8779e3862412edc99176f4d17e20a2ba61f6280a/py/visdom/server.py#L377
 in the server.py file, install, and then run again and see if you're still having the same issue?

I think this was all an unintended side-affect of making the UI more responsive to new envs being created without requiring a refresh, but it's possible that receiving the environment list over the socket so frequently every second is killing the browser. If it's this I'll push a fix, but if not I'll want to investigate further.
