### ISSUE TITLE
not clearing images from previous posts in visdom

### ISSUE THREAD

**Issue by ankita-kalra** [facebookresearch/visdom#309]
I tried clearing the environment and then reloading, visdom not clear previous posts on its window.

**Comment by JackUrb** [comment]
Hi @ankita-kalra - is it possible that you're running visdom on a process that doesn't have the permissions to write to the folder where your visdom data is stored? The clear button attempts to remove all the windows and save the cleared environment to file, however if the save was denied a reload will simply load the old version of the file with all the contents still there.

**Comment by JackUrb** [comment]
I'm going to close for now, but please feel free to re-open if you're still having this issue

**Comment by sksenthilkumar** [comment]
> Hi @ankita-kalra - is it possible that you're running visdom on a process that doesn't have the permissions to write to the folder where your visdom data is stored? The clear button attempts to remove all the windows and save the cleared environment to file, however if the save was denied a reload will simply load the old version of the file with all the contents still there.

I'm not able to find the close button! Where can I find it in the environment?

**Comment by JackUrb** [comment]
@sksenthilkumar - you can use the eraser icon to clear all of the contents of the environment, and then save the environment in the dialog launched with the folder icon next to that eraser. This will ensure the contents are removed.
