### ISSUE TITLE
t.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

### ISSUE THREAD

**Issue by dzimmerer** [facebookresearch/visdom#310]
With the new master I get the following error: 

t.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object. 
```
Uncaught Error: Minified React error #109; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=109&args[]=t for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (react-dom.min.js:15)
    at p._renderValidatedComponent (react-dom.min.js:13)
    at performInitialMount (react-dom.min.js:13)
    at p.mountComponent (react-dom.min.js:13)
    at Object.mountComponent (react-dom.min.js:14)
    at mountChildren (react-dom.min.js:14)
    at m._createInitialChildren (react-dom.min.js:13)
    at mountComponent (react-dom.min.js:13)
    at Object.mountComponent (react-dom.min.js:14)
    at performInitialMount (react-dom.min.js:13)
```

**Comment by JackUrb** [comment]
Ah sorry about this @dzimmerer - we recently had an update that was supposed to force a redownload of the visdom resources (as we no longer support the version of react that we used to), but I suppose that didn't make it in. I'll put together a fix, but you should be able to fix the issue by uninstalling and reinstalling visdom!

I'll investigate other reasons as to why this would happen just in case the react version update to 16.2 doesn't help

**Comment by dzimmerer** [comment]
Thanks for the answer =), 

uninstalling and reinstalling did not help, somehow the static folder was not deleted when uninstalling, but removing the folder manually solved the issue. 
(if anyone else has the issue delete the static folder in the visdom folder e.g. in your site-packages folder)
