### ISSUE TITLE
Hold on the fig location

### ISSUE THREAD

**Issue by zjtgit** [facebookresearch/visdom#311]
I  train my models with pytorch, and use visdom show training status. Every time when I open the showing html page, the fig mixed up together. So, how to hold on the figure location with the fixed order?

**Comment by JackUrb** [comment]
Hi @zjtgit - If you have a particular ordering of figures that you want, you can rearrange the figures to fill those slots, hit the pack button (the 9 squares), and then save the current setup as a view using the view modal. Selecting this view will always return the figures to the locations and sizes they were when you saved them.

Unfortunately if you can't get the organization you want to stay after hitting the pack button, saving a view like this will only save the version of that view that would result from hitting the pack button. This is a limitation of the way we use grid-layout, and while we intend to support multiple layout options in the future, the implementation of those is a ways away.

**Comment by zjtgit** [comment]
Thanks for your reply, I will have a try.
