### ISSUE TITLE
[Feature Request] Filter / Search on environments

### ISSUE THREAD

**Issue by jramapuram** [facebookresearch/visdom#315]
While the filter on the graphs is great it would be useful to have a filter on the environments as well, this is especially useful when we have a ton of envs, eg:

![screenshot from 2018-04-18 13-58-06](https://user-images.githubusercontent.com/8204807/38930541-9351310c-4310-11e8-858d-d214d0d7d299.png)

**Comment by JackUrb** [comment]
Hi @jramapuram - we now have a filter/search on environments as of #283, If you install from source you can try it our and see if it works for you!

**Comment by jramapuram** [comment]
Great! Just compiled from source. Looks awesome!
