### ISSUE TITLE
[Bug] Sort on environments fails when visdom is getting data sent in

### ISSUE THREAD

**Issue by jramapuram** [facebookresearch/visdom#316]
So once visdom has received all the data from 1 or more experiments it nicely sorts the environment names, eg:

![screenshot from 2018-04-18 14-01-33](https://user-images.githubusercontent.com/8204807/38930705-15feb6c4-4311-11e8-9947-6be476888bee.png)

However, when it is receiving data from 1 or more running experiments the sort is lost, eg:

![screenshot from 2018-04-18 13-58-06](https://user-images.githubusercontent.com/8204807/38930728-2b6a0982-4311-11e8-8d20-356af79407dd.png)

**Comment by JackUrb** [comment]
@jramapuram I'm somewhat sure this is no longer an issue as #283 introduces a component that forces sorting, but if you update to that and still see sorting issues let me know!

**Comment by jramapuram** [comment]
@JackUrb  : yup, looks like this is fixed when compiling from src!
