### ISSUE TITLE
[Bug] Unresponsive visdom when using source build

### ISSUE THREAD

**Issue by jramapuram** [facebookresearch/visdom#318]
Using commit 7a206101e5b87914755183ad04e081dd8c5a9046 to check out the next search feature and the new merging of multiple envs (super useful), however I keep getting unresponsive pages when there are many envs sending data to the visdom server. On a smaller case (eg: 2-3 envs being updated) the issue does not seem to exist.

![screenshot from 2018-04-20 11-28-40](https://user-images.githubusercontent.com/8204807/39043778-94e10748-448e-11e8-8808-e28e41f0d07b.png)

Small screenrecord also:
[out-1.ogv.zip](https://github.com/facebookresearch/visdom/files/1931560/out-1.ogv.zip)

**Comment by JackUrb** [comment]
Hi @jramapuram - can you try the solution suggested in #302? I think that should solve the issue but I haven't been able to take the moment to set up an environment to test the heavy load issue just yet.

**Comment by jramapuram** [comment]
Sorry for the delay; this is indeed fixed @JackUrb
