### ISSUE TITLE
Cannot save the environment if it contains slashes

### ISSUE THREAD

**Issue by jihunchoi** [facebookresearch/visdom#32]
Hi, thank you for the great software first!

I am really enjoying using the software, however I found some trivial bugs that occur in corner cases.
When I try to save an environment which contains slashes, for example "model_1/dim100", it cannot save the environment and makes some unhappy side effects.
If I save it programmatically, for example `vis.save([env_name])`, the server makes error logs of `FileNotFoundError`, since the directory `$HOME/.visdom/model_1` does not exist.
And if I try to save it on the webpage, the webpage goes offline and I have to click the "offline" button or refresh the page to revive functionalities.

I think two solutions are possible:
1) making the directory (using something like `mkdir -p` or `os.makedirs`) before making the JSON file of an environment, or
2) replacing slash characters with other safe characters, like `_`.

**Comment by ajabri** [comment]
Hi @jihunchoi , thanks for your post! You're right, and it sounds like 2 is a good solution. Since the change is pretty simple, want to submit a pull request?

**Comment by jihunchoi** [comment]
Yup, I will send a PR within 24 hours.
