### ISSUE TITLE
The visdom experienced an exception while running: AttributeError("'Visdom'  'register_event_handler'",)

### ISSUE THREAD

**Issue by poppingcode** [facebookresearch/visdom#320]
when i run python demo.py

output : 
The visdom experienced an exception while running: AttributeError("'Visdom' o 'register_event_handler'",)
The demo displays up-to-date functionality with the GitHub version, which mapip. Please upgrade using `pip install -e .` or `easy_install .`
If this does not resolve the problem, please open an issue on our GitHub.

my visdom version is 0.1.7

**Comment by JackUrb** [comment]
Hi @poppingcode - our demo tests things that aren't always live yet in the pypi version of visdom. I've been a bit behind on getting some of the features from this year onto pypi, but the most up-to-date version `0.1.7.2` is accessible by running `pip install -e .` or `easy_install .`, as suggested by the error message.
