### ISSUE TITLE
Send data to remote server

### ISSUE THREAD

**Issue by TimingSpace** [facebookresearch/visdom#322]
If I want to run my training code on Computer A with no public IP and run my visdom server on computer B with public IP, how can I send the data for plotting from computer A to Computer B?

Or when my training computer cannot be accessed by IP (such as a cluster with slurm), how can I use visdom?

**Comment by JackUrb** [comment]
In this case you would set up your visdom server on Computer B (`python -m visdom.server`). Knowing the IP of computer B, on computer A you would initialize a visdom client with `vis = visdom.Visdom(server='http://<COMPUTER_B_IP_ADDRESS>')` and then calls to `vis` should plot to computer B.

**Comment by TimingSpace** [comment]
That works, Thank you!

**Comment by yfzhang** [comment]
Is there a way to add a port based on the code below.
`vis = visdom.Visdom(server='http://<COMPUTER_B_IP_ADDRESS>')`
