### ISSUE TITLE
Can't pass options through to Plotly

### ISSUE THREAD

**Issue by yasuiniko** [facebookresearch/visdom#324]
In this example I'm trying to get rid of the x-axis labels in a heatmap. I a couple different options that made sense given the docs, code, and [Plotly docs](https://plot.ly/python/axes/), but none of them worked and I'm at a loss. 

Here is my code:

```{python}
import visdom
vis = visdom.Visdom()
vis.heatmap(X=np.arange(10).reshape(2,5), opts=dict(xlabel=False, xtick=False))

vis.heatmap(X=np.arange(10).reshape(2,5), opts=dict(xlabel='', xtick=''))

vis.heatmap(X=np.arange(10).reshape(2,5), opts={'xaxis': dict(autorange=True, showgrid=False, zeroline=False, showline=False,autotick=True,ticks='',showticklabels=False)})

vis.heatmap(X=np.arange(10).reshape(2,5), opts={'layoutopts': {'plotly': {'xaxis': dict(autorange=True, showgrid=False, zeroline=False, showline=False,autotick=True,ticks='',showticklabels=False)}}})
```

The last line in particular is recommended in the Visdom docs. How can I pass the appropriate options to Plotly?

**Comment by JackUrb** [comment]
Hi @yasuiniko! Have you tried installing visdom from source? The `layoutopts` override isn't yet available on pypi, but version 0.1.7.2 (current source version) has it.
![screen shot 2018-04-25 at 1 09 57 pm](https://user-images.githubusercontent.com/1276867/39261262-f9d0fbf0-4889-11e8-9ce5-bba35742eab9.png)

**Comment by JackUrb** [comment]
Once #302 / #318 has been resolved I'll be pushing the new version out to pypi

**Comment by yasuiniko** [comment]
Thanks @JackUrb, building from source solved the problem! Looks like I was confused because the github docs don't apply to the pypi code.

For anyone else reading this, my last example above was the one that worked, as per the github docs.

```
import numpy as np
import visdom
vis = visdom.Visdom()

vis.heatmap(X=np.arange(10).reshape(2,5), opts={'layoutopts': {'plotly': {'xaxis': dict(autorange=True, showgrid=False, zeroline=False, showline=False,autotick=True,ticks='',showticklabels=False)}}})
```
