### ISSUE TITLE
Visdom is extremely laggy when there are many windows (~30).

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/visdom#327]
Is it a performance issue?

**Comment by JackUrb** [comment]
Do you have many environments as well? Are the windows being plotted to actively? Could be related to #302, which is being solved in #326

**Comment by yxchng** [comment]
Nope. It open a new window everytime it sends to Visdom. Is it normal? What is the maximum number of windows that can be opened before I hit performance issues?

**Comment by ajabri** [comment]
I noticed the following change recently: all plot windows seem to rerender whenever I re-hover over a plot window. It could be that at some point the child rendering logic was changed so that all windows are now rerendering when they shouldn't be.

**Comment by yxchng** [comment]
@JackUrb they are indeed all going to the "main" environment? should i open new environment for each window?

**Comment by JackUrb** [comment]
@ajabri re-rendering completely on hover? I haven't observed that behavior... What's the symptom - does zoom reset or does the plot blink out for a second?

@yxchng you shouldn't need to open an environment for each window. Are you running on the pypi version or have you installed from source?

**Comment by yxchng** [comment]
@JackUrb installed from source

**Comment by JackUrb** [comment]
@yxchng Also from before - what browser are you using?

**Comment by yxchng** [comment]
@JackUrb Chrome. Ok.

**Comment by JackUrb** [comment]
Hm I also use chrome. Are your plots very dense?

**Comment by yxchng** [comment]
@JackUrb Nope. Just a simple matplotlib plot per window.

**Comment by JackUrb** [comment]
Oh you aren't using the plotly plots? I don't know how well the matplotlib plots scale, as they rely on an SVG backend, which is less efficient than the webgl that the plotly plots use

**Comment by yxchng** [comment]
@JackUrb Ok. I didn't know about that. Will try plotly.
