### ISSUE TITLE
CC-BY-4.0 in setup.py should be CC BY-NC 4.0?

### ISSUE THREAD

**Issue by davidwagnerkc** [facebookresearch/visdom#332]
https://github.com/facebookresearch/visdom/blob/3bc7d045c7683253f241153d655c02d54377c0ab/setup.py#L26

This might need to be changed to CC BY-NC 4.0 to match the **LICENSE.md** file.
https://github.com/facebookresearch/visdom/blob/3bc7d045c7683253f241153d655c02d54377c0ab/LICENSE#L57

I don't know if this is a problem or not, just noticed it and wanted to make you aware in case it was.

**Comment by lvdmaaten** [comment]
Thanks!
