### ISSUE TITLE
when I start visdom, the web page opens slowly and there is nothing on the window.

### ISSUE THREAD

**Issue by woaichipinngguo** [facebookresearch/visdom#336]
when I start visdom, the web page opens slowly and there is nothing on the window.
![10](https://user-images.githubusercontent.com/15664013/39672923-c2093400-5165-11e8-8b26-2a0c3b408499.JPG)
**## Then I input "http://localhost:8097/" in the chrome. It opens very slowly.**
I run the code snippet:
`import visdom`
` import numpy as np`
`vis = visdom.Visdom()`
 `  vis.text('Hello, world!')`
`vis.image(np.ones((3, 10, 10)))`
output in the jupyter notebook is: `'pane_36334f89fb6f3c'`
## **# But there is nothing on the window.**
![111](https://user-images.githubusercontent.com/15664013/39672987-cd4e112c-5166-11e8-86b7-696ed8271612.JPG)

**Comment by JackUrb** [comment]
Hi @woaichipinngguo - is anything coming up in your javascript console? If resources are missing have you tried to download the dependancies as described in the **Issue: I see a blue screen in my browser, but I do not see visualizations** section of [the contributing guidelines](https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md)? Even more easily you can use the [download.sh](https://github.com/facebookresearch/visdom/blob/master/download.sh) script (as taking a look now it seems the deps listed in the contributing guidelines are slightly out of date)

**Comment by woaichipinngguo** [comment]
@JackUrb  Thanks!!!
The problem has been solved. The issue also occurred  in my Windows visdom. I found some files was missing in the folder ` Anaconda3\Lib\site-packages\visdom\static` and then I completed them .  Now  it is Ok.

**Comment by JackUrb** [comment]
Closing as you mentioned it's okay now. Thanks for reaching out!
