### ISSUE TITLE
no plot shown on the webpage

### ISSUE THREAD

**Issue by zchrissirhcz** [facebookresearch/visdom#337]
Hi, I install visdom and run the hello world plot but cannot see plot on the webpage.

## Basic Info
System: Ubuntu16.04
Python: 2.7.12
pip: 10.0.1

## Steps that I took:
```bash
sudo pip install visdom
python -m visdom -port 9090
```
Then in a jupyter-notebook I wrote:
```python
import visdom
import numpy as np
vis = visdom.Visdom()
vis.text('Hello, world!')
vis.image(np.ones((3, 10, 10)))
```
![visdom](https://user-images.githubusercontent.com/3831847/39740069-909e7f26-52c6-11e8-8ca4-c3cdcd7fb5e8.png)

I've also git cloned the latest github repo, and run its example code by:
```
cd /opt/work
git clone https://github.com/facebookresearch/visdom
cd visdom
python example/demo.py
```
which gives:

![visdom2](https://user-images.githubusercontent.com/3831847/39740269-7a5bbd18-52c7-11e8-818a-3d5eb4d0261e.png)

So I follow this help information, by typing:
```
cd /opt/work/visdom
sudo pip install -e .
```
and reopen jupyter-notebook and visdom server. Thi time, the webpage still give no plot, and javascript console gives new error:
![visdom3](https://user-images.githubusercontent.com/3831847/39740395-00c38980-52c8-11e8-97f5-594ba4cb4e2a.png)

And by running `cd /opt/work/visdom; python example/demo.py`, the terminal gives:
```
➜  visdom git:(master) ✗ python example/demo.py
No handlers could be found for logger "visdom"
The visdom experienced an exception while running: AssertionError(u'No connection could be formed quickly',)
The demo displays up-to-date functionality with the GitHub version, which may not yet be pushed to pip. Please upgrade using `pip install -e .` or `easy_install .`
If this does not resolve the problem, please open an issue on our GitHub.
```

Note, I've also tried python3.6 with pip3. Nearly same error, the webpage still empty plot.

**Comment by JackUrb** [comment]
Was this issue resolved using `pip install -e .` or `easy_install .`?

**Comment by soulslicer** [comment]
I have the same problem but rebooting doesnt work

**Comment by JackUrb** [comment]
@soulslicer have you referred to the [contributing guidelines](https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md) for blue screen issues? A lot of completely separate issues can cause the blue screen, so look there and then open a new issue if the instructions don't resolve anything. Be sure to include logs as described in the template for issues.

**Comment by soulslicer** [comment]
My issue is that it shows up in the blue screen, but not on ipython

**Comment by JackUrb** [comment]
Please open a new issue with complete details, you haven't provided enough information and I'm not convinced you have the same issue as you have only given me 2 sentences to work with.
