### ISSUE TITLE
Confirmation checkbox for clearing all the windows

### ISSUE THREAD

**Issue by HenryZhou7** [facebookresearch/visdom#339]
Is it possible to add an optional confirmation pop-up box when accidentally clicking the erasing button?

**Comment by JackUrb** [comment]
Hi @HenryZhou7 - Confirm functionality is currently implemented in the pre-release here on github, install from source using `pip install -e .` to see it. https://github.com/facebookresearch/visdom/pull/325

**Comment by JackUrb** [comment]
(Closing as the feature is already implemented)
