### ISSUE TITLE
Feature Request: Grid of multiple images

### ISSUE THREAD

**Issue by zuoxingdong** [facebookresearch/visdom#34]
It is often useful to plot multiple images in a grid, for comparison need. It shall be very good if Visdom adds this functionality, e.g. PyTorch has this [make_grid](https://github.com/pytorch/vision/blob/master/torchvision/utils.py) function which is nice. Hopefully it can be improved a bit and integrated into Visdom.

**Comment by ajabri** [comment]
Hi @zuoxingdong ,

Yes, definitely. In torch-image, you have `image.toDisplayTensor`. We originally thought that people make such grids in their own code before calling `vis.image`, but we can add it if you think it's useful. Want to submit a pull request?

**Comment by zuoxingdong** [comment]
Hi @ajabri , I am happy to work on it during next few days. Do you suggest to make it as a new API, e.g. `vis.image_grid(tensor, nrow, padding)`, 

or put it as a flag with same API , `vis.image(img, )` to make everything internally, to check 
1. if it is 3D tensor, then use original source code. 
2. If it is 4D tensor, then make a grid that mimics the functionality in torchvision `make_grid`

**Comment by ajabri** [comment]
Both sound reasonable. You can also make `vis.images(tensor, ...)` that makes the grid and then calls `vis.image(img, )`.

**Comment by soumith** [comment]
if you are interested, you can simply port this function over: https://github.com/pytorch/vision/blob/master/torchvision/utils.py#L6-L78

**Comment by zuoxingdong** [comment]
@soumith @ajabri Thanks for the info. I've adapted this code to Numpy version, so that dependencies of torchvision is not required. The change made in PR #51

**Comment by ajabri** [comment]
Fixed in #51

**Comment by isalirezag** [comment]
if you guys can also add the option to it so the user can specify if it is for gray images or rgb images that would be great

**Comment by JackUrb** [comment]
Hi @isalirezag - please open that as a new feature request issue so that people can see it as a higher visibility request they can work on. In the meantime you can expand your 1 channel image to 3 channels with the same content and that should plot.
