### ISSUE TITLE
No filter button shown in the web page

### ISSUE THREAD

**Issue by yfzhang** [facebookresearch/visdom#344]
I could not find the filter button in the web page.
I am currently using visdom 0.1.4. 
![image](https://user-images.githubusercontent.com/3224485/39832706-f307a884-5395-11e8-83c3-a454d71135c8.png)

**Comment by JackUrb** [comment]
Version `0.1.4` came before the filter was added - please update to the most recent pip version `0.1.7` or install from source using `pip install -e .` from a clone of the repo to get version `0.1.7.2`
