### ISSUE TITLE
No filter button shown in the web page (visdom 0.1.7)

### ISSUE THREAD

**Issue by yfzhang** [facebookresearch/visdom#345]
I could not find any filter button in the web page.
I have already updated visdom to latest `0.1.7`.
I have tested in chrome and firefox.
![image](https://user-images.githubusercontent.com/3224485/39846735-59697d7a-53cb-11e8-9fae-097b137a0cc1.png)

**Comment by lvdmaaten** [comment]
Did you restart the visdom server after you updated? It looks like your
browser is still hitting an old version of the visdom server.

**Comment by JackUrb** [comment]
You should be able to pip install version `0.1.8.1` which certainly has the filter working. Reopen this issue if you're still having issues.
