### ISSUE TITLE
Please release a stable version newer than 0.1.7

### ISSUE THREAD

**Issue by OmegaNJU** [facebookresearch/visdom#346]
I notice that the 0.1.7 version is released on Jan 10, but many awesome new feature and API added after that. Unfortunately, when I install the latest version from here (it is 0.1.7.2), the visdom server doesn't work normally. The browser just presents a blue background webpage with nothing.
<img width="1680" alt="2018-05-10 10 42 16" src="https://user-images.githubusercontent.com/5026687/39849459-0bf04b9a-543f-11e8-9265-222170626bc6.png">

And the console of browser reports bugs as following picture shows:
<img width="1680" alt="2018-05-10 10 42 40" src="https://user-images.githubusercontent.com/5026687/39849464-1263a6fc-543f-11e8-94a8-2c183187e6e7.png">

P.S. I tested both in Mac OS 10.13 and Ubuntu 16.04. Python version is 3.6.5. Browsers are including Safari, Chrome and Firefox.

**Comment by OmegaNJU** [comment]
Ah! I got it, my problem is same with #310

**Comment by JackUrb** [comment]
Hi @OmegaNJU - I appreciate the enthusiasm about the new features! #310 is actually the only remaining reason that `0.1.7.2` hasn't been pushed public as `0.1.8`, as I'd like to ensure the transition for all users is seamless. Rest assured I have a solution in mind and will be pushing it soon

**Comment by JackUrb** [comment]
`0.1.8` is now live on pypi - enjoy!
