### ISSUE TITLE
Visdom crashes with numerical title

### ISSUE THREAD

**Issue by RicCu** [facebookresearch/visdom#353]
OS: Ubuntu 16.04
Browser: Chrome
Visdom version: 1.8.2

If the "title" property passed to a visdom plot contains a numeric value rather than a string, the client crashes without an error message and displays only the background.  I.e:

```python
import torch
import visdom
vis = visdom.Visdom()
vis.line(X=torch.tensor([0]), Y=torch.tensor([1]), opts={'title': 'text'}) # works fine
vis.line(X=torch.tensor([0]), Y=torch.tensor([1]), opts={'title': 10}) # crashes
```

![image](https://user-images.githubusercontent.com/9958312/40021763-656fd27c-578b-11e8-87d3-ffb02d88ff0c.png)

Python does not generate any message and the Javascript console shows:

> Warning: Each child in an array or iterator should have a unique "key" prop.
 TypeError: n.title.match is not a function
    at main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:35
    at Array.map (<anonymous>)
    at t.value (main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:35)
    at h (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:130)
    at beginWork (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:134)
    at d (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:158)
    at f (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:159)
    at g (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:159)
    at t (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:167)
    at x (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:166)

This can be easily solved by casting the number to a string before passing it to the opts dict, however there is no error message that clearly points to the problem. Alternatively it could be silently cast to a string by visdom. 

If you agree with either fix or have something else in mind I can prepare a PR.

**Comment by JackUrb** [comment]
Hi @RicCu - Thanks for bringing up this issue! I think in this case we should actually go with both: a noisy cast. Have a `logger.warn` if the user is passing something that isn't a string before the cast. This wins in both, as it allows use of the function even if somewhat improper, but prevents someone down the road from creating window `10` and window `'10'` and having everything break with no visible reason. I'd be happy to accept such a PR!
