### ISSUE TITLE
visdom use_incoming_socket argument

### ISSUE THREAD

**Issue by robert780612** [facebookresearch/visdom#354]
OS ubuntu 16.04
visdom 0.1.8.2

While I was running visdom server, terminal displayed the following warning message.
> WARNING:visdom:Visdom
  python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.

But there is no command line option called `use_incoming_socket`.
For example, I typed the following command in the terminal:
`python -m visdom.server --use_incoming_socket=False`
> Downloading scripts. It might take a while.
 usage: server.py [-h] [-port port] [-env_path env_path]
                  [-logging_level logger_level] [-readonly]
 server.py: error: unrecognized arguments: --use_incoming_socket=False

How can I turn off the `use_incoming_socket`?

Thanks

**Comment by JackUrb** [comment]
Hi @robert780612 - this was an unintended side-effect of #352, but a fix is out in #355. The server should never need to use the incoming socket.

**Comment by asaxenastanford** [comment]
@JackUrb I'm still getting this issue. Are there any fixes?

**Comment by JackUrb** [comment]
Have you updated visdom? What is your visdom version?

**Comment by asaxenastanford** [comment]
@JackUrb I have version 0.1.8.4. I am running the server, but I receive a warning about the socket and eventually my training script crashes. It says: Could not connect to Visdom server (https://github.com/facebookresearch/visdom) for displaying training progress.
You can suppress connection to Visdom using the option --display_id -1.

**Comment by JackUrb** [comment]
Are you using visdom through some other sourced script? We don't have any message like you've described, and it's possible they're not up to date and I'd like to let them know. You might be successful by simply using `visdom.Visdom(use_incoming_socket=False)` in that script but I don't have enough context to know.

You should also try running the demo.

**Comment by asaxenastanford** [comment]
@JackUrb Yes, I am running train.py from this [style GAN repository](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix).

**Comment by JackUrb** [comment]
Have you launched a visdom server using `visdom` in a screen on your command line before running the train script? I'm guessing it can't connect because you don't have one running (and thus this problem is unrelated to the issue you've attached it to)

**Comment by asaxenastanford** [comment]
@JackUrb The server is running on command line.

**Comment by JackUrb** [comment]
Have you tried the demo script from this repo? I can't debug through an external script if I can't reproduce it.

**Comment by robert780612** [comment]
Hi @JackUrb 
I tried the cyclegan repo, and it works fine.
![screenshot from 2018-08-02 09-44-39](https://user-images.githubusercontent.com/5730812/43557761-d0850d7a-9638-11e8-877b-d31332c63c69.png)

![screenshot from 2018-08-02 09-46-03](https://user-images.githubusercontent.com/5730812/43557781-e6568016-9638-11e8-9fde-2303d1ff0e93.png)

**Comment by JackUrb** [comment]
Thanks @robert780612 - sorry about the noise here. @asaxenastanford please try to reproduce your issue using our demo and then open a new issue for it, as it is likely something is wrong with your setup
