### ISSUE TITLE
AttributeError: 'Visdom' object has no attribute 'updateTrace'

### ISSUE THREAD

**Issue by blister1824** [facebookresearch/visdom#359]
Hey guy.  I am a newer to visdom and I try the code
`viz.updateTrace(
    X=np.random.rand(255),
    Y=np.random.rand(255),
    win=win,
    name='new_trace',
)
`
online but then I get the bug `AttributeError: 'Visdom' object has no attribute 'updateTrace'`
My version is the newest version 0.1.8.3 and i wonder know if there is any bug in the newest version?

**Comment by JackUrb** [comment]
As noted in https://github.com/facebookresearch/visdom/issues/358, updateTrace was deprecated more than 6 months ago and removed in the last major update (`0.1.8`). You can update directly with traces directly using `line` and `scatter`

**Comment by YashSunidhi** [comment]
AttributeError: 'Visdom' object has no attribute 'updateTrace'. What Update , I need to make Callback code to get away with this issue?

**Comment by JackUrb** [comment]
Rather than calling `updateTrace`, you can simply use `scatter` or `line` with the update you want to make. Please view the [demo](https://github.com/facebookresearch/visdom/blob/3335974395b08371d0f9cb225832cf7d54d703fd/example/demo.py#L254) for examples

**Comment by soulslicer** [comment]
Can someone please tell me how to port this line to the new API

            #self.viz.updateTrace(X=np.array([x]), Y=np.array([y]), env=self.env, win=self.plots[var_name], name=split_name)

I can't find any solution anywhere

**Comment by JackUrb** [comment]
@soulslicer are you trying to append or replace? Is it a line or a scatter plot? Depending on which, you'll just use `viz.scatter` or `viz.line` with the parameters `update='append'` or `update='replace'` and the rest of the parameters as you've provided above.
