### ISSUE TITLE
event handlers doesn't work

### ISSUE THREAD

**Issue by jabacrack** [facebookresearch/visdom#362]
Windows 10, python 3.6.4, visdom 0.1.8.3, Chrome and Firefox browsers

1. Run code from examples:
```
 txt = 'This is a write demo notepad. Type below. Delete clears text:<br>'
    callback_text_window = viz.text(txt)

    def type_callback(event):
        if event['event_type'] == 'KeyPress':
            curr_txt = event['pane_data']['content']
            if event['key'] == 'Enter':
                curr_txt += '<br>'
            elif event['key'] == 'Backspace':
                curr_txt = curr_txt[:-1]
            elif event['key'] == 'Delete':
                curr_txt = txt
            elif len(event['key']) == 1:
                curr_txt += event['key']
            viz.text(curr_txt, win=callback_text_window)

viz.register_event_handler(type_callback, callback_text_window)
```
2. Select text window in browser and press enter or 1
3. In visdom console "INFO:root:from web client: {"cmd":"forward_to_vis","data":{"event_type":"KeyPress","key":"Enter","key_code":13,"target":"window_3641620f4427dc","eid":"main"}}"
But in text window nothing changed

**Comment by JackUrb** [comment]
Hi - Is the python demo code thread still running? If the thread closes, the callbacks are cleaned up by python garbage collection and nothing can trigger even if the server catches events happening.

If it is still running, what do you see in the terminal with the demo code running? What value does `visdom.use_socket` have?

On May 24, 2018, at 5:26 AM, jabacrack <notifications@github.com<mailto:notifications@github.com>> wrote:


Windows 10, python 3.6.4, visdom 0.1.8.3, Chrome and Firefox browsers

  1.  Run code from examples:

 txt = 'This is a write demo notepad. Type below. Delete clears text:<br>'
    callback_text_window = viz.text(txt)

    def type_callback(event):
        if event['event_type'] == 'KeyPress':
            curr_txt = event['pane_data']['content']
            if event['key'] == 'Enter':
                curr_txt += '<br>'
            elif event['key'] == 'Backspace':
                curr_txt = curr_txt[:-1]
            elif event['key'] == 'Delete':
                curr_txt = txt
            elif len(event['key']) == 1:
                curr_txt += event['key']
            viz.text(curr_txt, win=callback_text_window)

viz.register_event_handler(type_callback, callback_text_window)


  1.  Select text window in browser and press enter or 1
  2.  In visdom console "INFO:root:from web client: {"cmd":"forward_to_vis","data":{"event_type":"KeyPress","key":"Enter","key_code":13,"target":"window_3641620f4427dc","eid":"main"}}"
But in text window nothing changed

**Comment by jabacrack** [comment]
Look like I wrong understand how work with events - I doesn't think that parent thread must run all time. 
But after I add time.sleep(1000) (is that enough? )at the end of my file, after first key press I get next error in visdom console:
```
INFO:root:from web client: {"cmd":"forward_to_vis","data":{"event_type":"KeyPress","key":"Delete","key_code":46,"target":"window_364182f1b8ecac","eid":"main"}}
ERROR:tornado.application:Uncaught exception in /socket
Traceback (most recent call last):
  File "C:\Miniconda3\envs\pytorch\lib\site-packages\tornado\websocket.py", line 494, in _run_callback
    result = callback(*args, **kwargs)
  File "C:\Miniconda3\envs\pytorch\lib\site-packages\visdom\server.py", line 285, in on_message
    packet['pane_data'] = environment['jsons'][packet['target']]
KeyError: 'window_364182f1b8ecac'
```

**Comment by JackUrb** [comment]
Time.sleep would give you 1000 seconds of runtime, which might be enough for what you're doing. If you look at the demo file I've just set up an infinite loop that waits for an interrupt. You can also use a `input('Enter anything to exit')` for the same purpose. 

Can you try running the provided demo file? Or restarting the server? This error seems to imply that something is out of sync (the window that the event is coming from doesn't exist - this occurrence wouldn't make sense as the window itself is deciding to send the event, so it *should* exist)

**Comment by jabacrack** [comment]
Thank you for your help. I find mistake in my code and after all start working.

**Comment by prateekpg2455** [comment]
Hi,
I couldn't get how to get callback events working. So far I have been using Visdom to log data interactively. When I copy pasted the above code the text window is not taking any inputs.

**Comment by JackUrb** [comment]
@prateekpg2455 Please try running the visdom demo in the examples folder and see if that is working properly. The python process that's running the visdom client must remain open for callbacks to work.

**Comment by prateekpg2455** [comment]
I tried but it gives me this warning:
`No handlers could be found for logger "visdom"`

**Comment by JackUrb** [comment]
Can you paste your full terminal log? And what version of visdom are you on?

**Comment by JackUrb** [comment]
Did you press any keys other than backspace? This looks correct.

What about the logs from the client side?

On Jun 7, 2018, at 12:25 PM, Prateek <notifications@github.com<mailto:notifications@github.com>> wrote:


I just updated visdom to 0.1.8.3

Here is my log:

INFO:tornado.access:200 POST /env/07%20Jun%2016:22_session_name (::1) 1.22ms
INFO:tornado.access:200 POST /env/07%20Jun%2016:22_session_name (::1) 1.68ms
INFO:root:from web client: {"cmd":"forward_to_vis","data":{"event_type":"KeyPress","key":"Backspace","key_code":8,"target":"window_364c9cf0d51cc6","eid":"07 Jun 16:22_session_name"}}
INFO:root:from web client: {"cmd":"forward_to_vis","data":{"event_type":"KeyPress","key":"Backspace","key_code":8,"target":"window_364c9cf0d51cc6","eid":"07 Jun 16:22_session_name"}}
INFO:root:from web client: {"cmd":"forward_to_vis","data":{"event_type":"KeyPress","key":"Backspace","key_code":8,"target":"window_364c9cf0d51cc6","eid":"07 Jun 16:22_session_name"}}
INFO:root:from web client: {"cmd":"forward_to_vis","data":{"event_type":"KeyPress","key":"Backspace","key_code":8,"target":"window_364c9cf0d51cc6","eid":"07 Jun 16:22_session_name"}}

**Comment by prateekpg2455** [comment]
So I finally got it to work for demo.py. There are no client-side logs tough. The last line just asks to `press Enter to quit.`

However, how can I make it work for my project? Where is it in demo.py that it is being set up as a web-server??

**Comment by JackUrb** [comment]
https://github.com/facebookresearch/visdom/blob/89bc44fd8f1baae10541da19d797618123d72ca5/example/demo.py#L38

Here through line 54 is an example of creating a window and registering a callback to it. You can register any arbitrary function as long as it parses the event structure.

https://github.com/facebookresearch/visdom/blob/89bc44fd8f1baae10541da19d797618123d72ca5/example/demo.py#L457

This line is used to keep the thread running even after everything has been logged to prevent the main thread from quitting.

Another example can be seen here in the properties pane demo: 

https://github.com/facebookresearch/visdom/blob/89bc44fd8f1baae10541da19d797618123d72ca5/example/demo-properties.py#L78

**Comment by JackUrb** [comment]
You can learn more about how visdom event handlers are maintained by looking into the visdom object:
https://github.com/facebookresearch/visdom/blob/89bc44fd8f1baae10541da19d797618123d72ca5/py/visdom/__init__.py#L322

https://github.com/facebookresearch/visdom/blob/89bc44fd8f1baae10541da19d797618123d72ca5/py/visdom/__init__.py#L333
