### ISSUE TITLE
Cannot instantiate visdom with specified env name

### ISSUE THREAD

**Issue by TommeyChang** [facebookresearch/visdom#365]
When run the following code, an error is reported by the terminal running the visdom.server
vis = Visdom(env='test')

However, if the env name is not given, it is OK. The specific code is:
vis = Visdom()

I have tried to fix this error by install simplejson, but it does not work.

ERROR:tornado.application:Uncaught exception POST /win_exists (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8097', method='POST', uri='/win_exists', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1541, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/visdom/server.py", line 481, in post
    self.wrap_func(self, args)
  File "/usr/local/lib/python3.5/dist-packages/visdom/server.py", line 472, in wrap_func
    if args['win'] in handler.state[eid]['jsons']:
KeyError: 'test'
ERROR:root:ERROR: 500: {'exc_info': (<class 'KeyError'>, KeyError('test',), <traceback object at 0x7fca48f23608>)}

**Comment by lvdmaaten** [comment]
Looks like a bug, thanks for reporting!

As a work-around, you can instantiate the visdom class without environment, `vis = Visdom()`, and specify the environment whenever you create a plot: `vis.line(Y, X, env='test')`.

**Comment by TommeyChang** [comment]
Nice. It works. Thank you very much.
