### ISSUE TITLE
Fixed axis range and log scale

### ISSUE THREAD

**Issue by lozino** [facebookresearch/visdom#371]
Hi,

Is there a way to constrain the range of an axis to a specific interval (so that it does not automatically update upon appending new data)? Also, is there a way to display data along an axis in log scale?

Thanks!

**Comment by JackUrb** [comment]
Hi @lozino - you can fix the axis by providing both `xtickmin` and `xtickmax` options to the plot (for the x axis for example). You have to provide both as plotly requires a range to display over. (If setting those initially is still updating the plot you may also need to provide these during your append as well, but I don't think that should be required.)

For log axis, you can supply direct plotly opts using the `layoutopts` option. The format for that will be a dict that contains a `plotly` key with the value being a dict of plotly options. The one for using log axis is [here](https://plot.ly/javascript/log-plot/). Note that as this is directly overriding the axis options, the above note about specifying the range may be overridden. If it is, you will need to directly supply the range in the `plotly` dict as a `range` entry containing a two element array with the first being the min and the second being the max, as well as providing `autorange: False`. 

Below is an example that both sets the range and the plot type to log:
```
opts = {
  'layoutopts': {
    'plotly': {
      'xaxis': {
        'type': 'log',
        'range': [0, 1000],
        'autorange': False,
      }
    }
  }
}
```

**Comment by lozino** [comment]
Perfect, thanks!
