### ISSUE TITLE
Add support for showing caption (text) for videos

### ISSUE THREAD

**Issue by grantlj** [facebookresearch/visdom#378]
Currently it is not supported as in vis.image(). This is very inconvenient when debugging with the video data in large scale.

**Comment by JackUrb** [comment]
Right now captions aren't showing anymore at all, which seems to be a bug that was introduced recently (noted in #369). Currently investigating that, so I'll look into adding it to videos as well

**Comment by grantlj** [comment]
Could I adjust the position (or color) of the title for a little bit then? Currently the title is fully overlapped with the video and hence to be vague.

**Comment by JackUrb** [comment]
Feel free to install from source and edit your css file in the meantime to fix this for now (though the fact that the title overlaps the video is a problem)

**Comment by JackUrb** [comment]
This is similar to #443, so merging these together
