### ISSUE TITLE
Feature requests: default env and let win to be set from the start

### ISSUE THREAD

**Issue by DmitryUlyanov** [facebookresearch/visdom#38]
Hello, first thank you for maintaining this project, it is wonderful (and did not fail for me so far). 

1) Now you must specify `env` for each visualization you create. But I assume a lot of people use only one `env` per script (for example each `env` corresponds to an experiment and you plot a lot of things for it). So I would love to set `env` once and then pass `viz` object wherever I want (now I also need to pass `env` along with `viz` if I want to create visualization inside a function or package). I am not sure what is the best way to implement it though, so submitting issue instead of pull request. 

2) In `display` one could specify `win` for every plot, e.g. always plot loss in the first, show samples in the second. Now every time I rerun experiment new windows are created and I need to close old ones manually.

**Comment by ajabri** [comment]
Hi @DmitryUlyanov ,

Thanks for your post. 

For (1), I think we can just add a `default_env` parameter to the visdom client constructor (for now default env is hard coded to `main`).

For (2), you should actually be able to specify `win` for every plot... Have you tried this? This is the usual use-case and it should work.

**Comment by DmitryUlyanov** [comment]
Hi @ajabri, I tried to pass 0,1,2 .. as `win` variable, but the plots did not appear. Do I missing something?

**Comment by ajabri** [comment]
Hm, it does indeed look like giving an integer `win` variable fails. For now, can you cast `win` to a string? I can fix this later today. Feel free to submit a pull request too.

**Comment by ajabri** [comment]
I fixed this, will land tomorrow.

**Comment by DmitryUlyanov** [comment]
Thanks!

**Comment by ajabri** [comment]
Solved by commit ee4087a.
