### ISSUE TITLE
scatter does not apply colormap

### ISSUE THREAD

**Issue by hjalmarlucius** [facebookresearch/visdom#380]
https://github.com/facebookresearch/visdom/blob/d1c95845c784b1cd1a99bc64afd68efcaa178efc/py/visdom/__init__.py#L926

example:
`vis.scatter(X=torch.randn(10,2).numpy(), opts=dict(colormap='Hot')`

**Comment by JackUrb** [comment]
Hi @hjalmarlucius - I'll take a look into this!

**Comment by JackUrb** [comment]
Turns out plotly doesn't actually accept colorscales for anything other than surfaces and heatmaps. You can use `markercolor` to handle coloring line and scatter plots. Going to update the docs.
