### ISSUE TITLE
Retain opts for image, images when updating

### ISSUE THREAD

**Issue by Bharathcjr** [facebookresearch/visdom#381]
To update images I get the image window id and then use that to update the content. However the opts  for the window are not saved and needs to be specified in every update. 

vis = visdom.Visdom()
winid = vis.image(..., opts = ...)

When I try to update, the opts specified previously are lost.  
vis.image(..., win = winid)

Is there a better way to update the window with image content without specifying opts every time?

**Comment by lvdmaaten** [comment]
I generally try to make sure I only have a single call to produce a single plot, even if I'm updating the plot. Code structure:
```
# this is run this only once:
winid = None  

# ....

# this is run each time I'm creating or updating my plot:
opts = {...}
winid = vis.image(..., opt=opts, win=winid)
```

It is not clear to me that retaining the `opts` when there is an update is the desired default behavior: users expect a plot to have default options when they don't specify the `opts`. Also, the overhead of repeatedly passing the desired `opts` seems minimal.
