### ISSUE TITLE
Thoughts on binary launcher?

### ISSUE THREAD

**Issue by malmaud** [facebookresearch/visdom#382]
Hi,
I'm wondering if it would be good idea if `pip install visdom` installed a binary that when executed is equivalent to `python -m visdom.server`. ie, a user types

```
> visdom
```

instead of 

```
> python -m visdom.server
````

Seems nice since the former is shorter and easier to remember, and more in line with how other servers are typically started (eg, `tensorboard`).

**Comment by malmaud** [comment]
It should just be a small change to your `setup.py`. 'binary' was an inaccurate word on my part- it would just be an executable python script that gets installed to a the user's python distribution's 'bin' directory.

I can submit a quick PR for discussion.

**Comment by JackUrb** [comment]
That sounds more like what I'd expect. Feel free to put it up and I'll look it over!

On Jun 18, 2018, at 6:41 PM, Jon Malmaud <notifications@github.com<mailto:notifications@github.com>> wrote:


It should just be a small change to your setup.py. 'binary' was an inaccurate word on my part- it would just be an executable python script that gets installed to a the user's python distribution's 'bin' directory.

I can submit a quick PR for discussion.
