### ISSUE TITLE
Question about how to setup Visdom inside the nginx. 

### ISSUE THREAD

**Issue by chengyangfu** [facebookresearch/visdom#383]
Just want to know does anyone have the experience to setup Visdom server inside the nginx? 

The following is my setting inside nginx.  Although I can access the Visidom(http://ip:port/visdom) now, the Visdom server keeps showing offline and no images are showed.   

```
  location /visdom/ {
      allow 192.168.1.0/24;
      proxy_pass http://192.168.1.105:8097;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Origin "";
  }

**Comment by JackUrb** [comment]
Hi @chengyangfu - I don't know how well the visdom server will support custom paths (`/visdom/`). Is it possible to have the visdom server run on root `/` on that ip/port combination? That could explain the issue. (Also any logs from your server or the javascript logs would be very useful).

**Comment by chengyangfu** [comment]
Hi @JackUrb, it works now and thanks for the suggestion. 

Previously, I ran the visdom server and other services on the same port in nginx. It seems the path causes some problems when the visdom tries to read the image path. 

 After having the visdom server run on root and port without sharing with other services, it works perfectly. The following is the setting I used now. 

```
server {
  listen 5003;
  location / {
    proxy_pass http://localhost:8097;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Origin "http://localhost:8097";
  }
}
