### ISSUE TITLE
Switch from `setattr` to decorators?

### ISSUE THREAD

**Issue by malmaud** [facebookresearch/visdom#389]
I notice in `__init__.py`, you use `setattr` metaprogramming to make `Visdom` methods work on both Torch tensors and numpy arrays. This seems to be confusing static analysis with Jedi, causing autocomplete for `Visdom` methods to fail in various IDEs. 

How would you feel about switching to using a decorator for methods that  take can a tensor or array instead of `setattr`? That would be more transparent to static analysis tools and restore autocomplete. Arguably it's also cleaner, since the annotation that a method works on tensors and arrays would be inline with the method instead of that logic happening in a seperate block. 

I can submit a PR for discussion.

**Comment by JackUrb** [comment]
I've always found our current use of `setattr` to be a rather hacky support, but I haven't been able to take the time to work through an alternate solution. If you have something else in mind that works I'd be more than happy to take a look at it!

**Comment by malmaud** [comment]
Closed by https://github.com/facebookresearch/visdom/commit/2305c7ceca35e19a4d8411556ed2f8d535a37fe8
