### ISSUE TITLE
after run viz.histogram/scatter/line, the headline buttons are disappeared

### ISSUE THREAD

**Issue by blueardour** [facebookresearch/visdom#397]
Hi, I started to use the visdom tody.
I have succecced in run textwindow = viz.text('Hello World!') to display a text window in the http://localhost:8097/ website.
However after I ran any clause in viz.histogram/viz.scatter/viz.line. the headline disappeared and nothing came out in the webiste.
![image](https://user-images.githubusercontent.com/4530223/41702270-1364e496-7562-11e8-8082-06fb29d04827.png)

When I refreshed the url. The headline appeared and then disappeared immediately. I noticed the online button was green and then became red (offline) at that sudden.

When I further execute viz.close(), the headline appeared again and the website became normal.

Does any one meet similar situation and any clue for the problem?

**Comment by JackUrb** [comment]
Hi @blueardour,

Please check the logs on the JavaScript console and on your visdom server and attach them so that we can have more context.

**Comment by blueardour** [comment]
![image](https://user-images.githubusercontent.com/4530223/41756885-665fd854-7611-11e8-8d88-4b83edcfcb12.png)

![image](https://user-images.githubusercontent.com/4530223/41756939-96906502-7611-11e8-92c3-b25d33c85cec.png)

and in chrome console, it reports
`
react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:162 ReferenceError: Plotly is not defined
    at t.a.newPlot (main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:34)
    at t.value (main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:34)
    at commitLifeCycles (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:148)
    at b (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:156)
    at t (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:167)
    at x (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:166)
    at r (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:164)
    at v (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:163)
    at Object.enqueueSetState (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:124)
    at t.production.t.env.NODE_ENV.o.setState (main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:88)
h @ react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:162
b @ react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:156
t @ react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:167
x @ react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:166
r @ react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:164
v @ react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:163
enqueueSetState @ react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:124
production.t.env.NODE_ENV.o.setState @ main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:88
e.processBatchedPanes @ main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:34
setTimeout (async)
e.addPaneBatched @ main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:34
e._handleMessage @ main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:34
11:42:01.349 react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:166 Uncaught ReferenceError: Plotly is not defined
    at t.a.newPlot (main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:34)
    at t.value (main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:34)
    at commitLifeCycles (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:148)
    at b (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:156)
    at t (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:167)
    at x (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:166)
    at r (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:164)
    at v (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:163)
    at Object.enqueueSetState (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:124)
    at t.production.t.env.NODE_ENV.o.setState (main.js?v=124cf8f8086c9ff5a483f87179d1ea8d:88)
`

**Comment by blueardour** [comment]
it seem missing download of the plotly-latest.min.js. I would have a try of manually download it and feedback here

**Comment by blueardour** [comment]
after download the files, in the python shell:
>>> vis.histogram(X=np.random.rand(10000), opts=dict(numbins=20))
'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n  <meta http-equiv="X-UA-Compatible" content="IE=7" />\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n<meta name="keywords" content="MWG,Proxy" />\n<title>Huawei Proxy Notification</title>\n<style type=text/css>\nbody {\n\tfloat: none;\n\tbackground-color: #CCCCCC;\n\ttext-align: center;\n\tfont-size: 0.75em;\n\tpadding-top: 20px;\n\tmargin: 0 auto;\n}\na:link {\n\tCOLOR: #000;\n\tTEXT-DECORATION: none;\n}\n\na:visited {\n\tCOLOR: #000;\n\tTEXT-DECORATION: none;\n}\n\na:hover {\n\tCOLOR: #900;\n\tTEXT-DECORATION: underline;\n}\n\na:active {\n\tCOLOR: #900;\n\tTEXT-DECORATIO..............

and in the chrome console: 

content.js:96 get tabId=1817,len=4
17:52:12.150 MathMenu.js?V=2.7.1:2 Uncaught SyntaxError: Unexpected number
17:52:13.188 MathZoom.js?V=2.7.1:2 Uncaught SyntaxError: Unexpected number

The headliner will not disappear anymore. However, it seems still incomplete of files.  So how /where can I make sure all necessary files are in their correct position. As I am behind a proxy and would not want the ssl check.

**Comment by JackUrb** [comment]
Please refer to the contributions guide and use the download script from the home directory.

On Jun 22, 2018, at 5:57 AM, blueardour <notifications@github.com<mailto:notifications@github.com>> wrote:


after download the files, in the python shell:

vis.histogram(X=np.random.rand(10000), opts=dict(numbins=20))
'\n\n\n \n\n\n<title>Huawei Proxy Notification</title>\n<style type=text/css>\nbody {\n\tfloat: none;\n\tbackground-color: #CCCCCC;\n\ttext-align: center;\n\tfont-size: 0.75em;\n\tpadding-top: 20px;\n\tmargin: 0 auto;\n}\na:link {\n\tCOLOR: #000;\n\tTEXT-DECORATION: none;\n}\n\na:visited {\n\tCOLOR: #000;\n\tTEXT-DECORATION: none;\n}\n\na:hover {\n\tCOLOR: #900;\n\tTEXT-DECORATION: underline;\n}\n\na:active {\n\tCOLOR: #900;\n\tTEXT-DECORATIO..............

and in the chrome console:

content.js:96 get tabId=1817,len=4
17:52:12.150 MathMenu.js?V=2.7.1:2 Uncaught SyntaxError: Unexpected number
17:52:13.188 MathZoom.js?V=2.7.1:2 Uncaught SyntaxError: Unexpected number

The headliner will not disappear anymore. However, it seems still incomplete of files. So how /where can I make sure all necessary files are in their correct position. As I am behind a proxy and would not want the ssl check.

**Comment by blueardour** [comment]
Thanks, it worked
