### ISSUE TITLE
Blue Screen Error

### ISSUE THREAD

**Issue by jjpark** [facebookresearch/visdom#404]
*Bug Description**
After running the server I only see the blue screen. Nothing else. 

I have downloaded files suggested in the CONTRIBUTION.md file but I still get errors.

The javascript console from my chrome looks like this

![screenshot from 2018-06-27 17-00-48](https://user-images.githubusercontent.com/2028613/42005902-aaa34ea6-7a2b-11e8-85d0-eaf3372800b5.png)

**Comment by hudongloop** [comment]
Hi,
    make sure you can access https://unpkg.com/react-dom@16.2.0/umd/react-dom.production.min.js and check **download_scripts** function in **server.py**, which all address can access.
    I am change **layout-bin-packer@1.2.2** to **layout-bin-packer@1.4.0** solve my problem: _https://unpkg.com/layout-bin-packer@1.2.2 Failed to load resource: the server responded with a status of 404 ()_
