### ISSUE TITLE
Don't use absolute paths in HTML

### ISSUE THREAD

**Issue by malmaud** [facebookresearch/visdom#411]
Hi,
Right now, the HTML returned from the server has elements like 

```html
<link rel="stylesheet" href=http://localhost:8097/static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219>
```

with the `href` containing an absolute path. This makes it hard to use Visdom in a reverse-proxy setting since the client will try to request those absolute URLs, which in general won't be accessible to them. If the paths were relative, however (like  `/static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219`), everything would automatically work in the proxy setting.

**Comment by JackUrb** [comment]
This is a good note - I hadn't realized this behavior was occurring.
