### ISSUE TITLE
Support WSS

### ISSUE THREAD

**Issue by malmaud** [facebookresearch/visdom#415]
**Is your feature request related to a problem? Please describe.**
When serving visdom over HTTPS (such as with a reverse proxy), the websocket connection between the client and server continues to be insecure since the `ws` instead of `wss` protocol is used. Chrome will warn you and require you to opt-in to enable the insecure websocket connection.

**Describe the solution you'd like**
A command-line option to the visdom server that causes the served javascript to replace `ws://` with `wss://`. The Python client could use `wss` instead of `ws` if it sees that the Visdom host starts with `https` instead of `http`.

**Comment by JackUrb** [comment]
Hi @malmaud - I see this as a worthwhile thing to implement. I'm unsure it's necessary to have a command line option to trigger the swap, as the https vs http prefix should be sufficient right?

**Comment by malmaud** [comment]
Like, the Tornado handler that serves the javascript file checks if the resource is being requested over https or not to make the decision of whether to modify the js to use `wss`? 
Hmm, I don't think that would work in the proxy setting since the proxy might be communicating with the Tornado server over plain http while the proxy communicates with the client over https.

**Comment by JackUrb** [comment]
I was thinking this could be potentially handled in the JS logic instead. As the web client is the endpoint that actually knows if it's communicating over http or https it would be the reasonable place to determine `ws` or `wss`. Wouldn't it be sufficient to pull `window.location.protocol` to make that decision?

**Comment by malmaud** [comment]
Oh I see. Yes, that seems like a better solution all around.
