### ISSUE TITLE
high data usage

### ISSUE THREAD

**Issue by Nintorac** [facebookresearch/visdom#416]
**Is your feature request related to a problem? Please describe.**
visdom consumes a lot of data in the background

**Describe the solution you'd like**
when visdom is not the active window it stops fetching datapoints

**Describe alternatives you've considered**
Use the online/offline button to stop visdom from fetching datapoints, unfortunately sometimes i forget

**Additional context**

**Comment by JackUrb** [comment]
Due to the behavior that is going to be added in #395 data consumption should be reduced soon, but it's possible to add an option that automatically toggles the online button when swapping tabs. I don't know where in the UI such an option would go, I need to think more on that.

**Comment by JackUrb** [comment]
Now that #395 is long in I'm de-prioritizing this issue. It's a hard trade-off between fetching in the background and fetching later as the latter requires a full load now, and the savings in bandwidth are much less substantial following #395.
