### ISSUE TITLE
How to run Visdom on colab?

### ISSUE THREAD

**Issue by ninjakx** [facebookresearch/visdom#419]

**Comment by ninjakx** [comment]
`python -m visdom.server -port=6008`

How to start visdom server using  colab ?.

I am Trying to implement this code:
`import visdom`
`import numpy as np`
`vis = visdom.Visdom(port=6008)`
`vis.text('Hello, world!')`
`vis.image(np.ones((3, 10, 10)))`

but have no idea how to implement this on colab.

**Comment by JackUrb** [comment]
Hi @ninjakx - Google colab doesn't provide direct access to content running on their cloud, so you can't run the server from them. You might be able to launch the server on a google cloud instance or ec2 instance you own, and then connect to the server using `vis = visdom.Visdom(server=<personal_server_hostname>)`

**Comment by JackUrb** [comment]
You can also connect to your local instance by tunneling to localhost using the same method one would use to use tensorboard with colab: `https://stackoverflow.com/questions/47818822/can-i-use-tensorboard-with-google-colab`

**Comment by ninjakx** [comment]
@JackUrb - I tried with tensorboard and able to do it but not with the visdom.

**Comment by JackUrb** [comment]
Do you see anything in your logs when you connect? Does the visdom client ever return from the `vis = visdom.Visdom(server='0.0.0.0', port='6006')` (using the args from the tensoboard example).

**Comment by ninjakx** [comment]
```
get_ipython().system_raw(
    'python -m visdom.server -port=6008'
    
)

get_ipython().system_raw('url.txt 2>&1 &')

! cat url.txt
```
This is what i tried by following this site .

> https://www.dlology.com/blog/quick-guide-to-run-tensorboard-in-google-colab/

 I am not getting how to execute it.

**Comment by JackUrb** [comment]
Just got it working with the below:
```
! npm install -g localtunnel
get_ipython().system_raw('/usr/local/bin/python -m pip install visdom')
get_ipython().system_raw('/usr/local/bin/python -m visdom.server -port 6006 >> visdomlog.txt 2>&1 &')
get_ipython().system_raw('lt --port 6006 >> url.txt 2>&1 &')
import time
time.sleep(5)
! cat url.txt
import visdom
time.sleep(5)
vis = visdom.Visdom(port='6006')
print(vis)
time.sleep(3)
vis.text('testing')
! cat visdomlog.txt
```
Visit the contents of `url.txt` **using `http` rather than `https`** and you should be able to access the visdom server.
![screen shot 2018-07-17 at 11 48 57 am](https://user-images.githubusercontent.com/1276867/42829315-842feaae-89b7-11e8-9ee9-f6669e4363d1.png)

**Comment by madaanpulkit** [comment]
[visdom_error_colab.txt](https://github.com/facebookresearch/visdom/files/2769424/visdom_error_colab.txt)
It still keeps throwing errors
ERROR:visdom:Handshake status 404 NOT FOUND
and a lot more errors

**Comment by JackUrb** [comment]
@madaanpulkit try launching the server with a different -port argument. 6006 is already in use for some reason.

**Comment by madaanpulkit** [comment]
> @madaanpulkit try launching the server with a different -port argument. 6006 is already in use for some reason.

You sure are fast.
Thanks a lot.
It worked.
:)

**Comment by markolonius** [comment]
@JackUrb @madaanpulkit doesn't seem to work.  All I get is connection refused on any port I try.
Similar to your log with ERROR:visdom:Handshake status 404 NOT FOUND

**Comment by madaanpulkit** [comment]
@markolonius it worked fine initially but I'm also getting CONNECTION REFUSED lately I tried switching from localtunnel to ngrok but even that didn't work.

**Comment by sravyaysk** [comment]
@JackUrb It is not working. Getting "connection refused" even after changing to many ports.

**Comment by JackUrb** [comment]
Hi @markolonius, @madaanpulkit , @sravyaysk - I don't have any additional insight into why this isn't working on colab anymore, given it was something of a hack in the first place. 

Based on the logs this likely has to do with colab more than visdom. My guess is that they've reserved all of the sockets given `Error: connection refused: localtunnel.me:34629 (check your firewall settings)` when trying to set up the tunnel and `socket.error: [Errno 98] Address already in use` when trying to launch the visdom server. 

I don't have the bandwidth to investigate this at the moment, but if anyone has success launching anything on an open port in colab and tunneling to it, whatever they've done should apply here as well.

**Comment by OlofHarrysson** [comment]
I got it working today by tweaking Jack's solution. Just changed the python to python3

```
! npm install -g localtunnel
get_ipython().system_raw('python3 -m pip install visdom')
get_ipython().system_raw('python3 -m visdom.server -port 6006 >> visdomlog.txt 2>&1 &')
get_ipython().system_raw('lt --port 6006 >> url.txt 2>&1 &')
import time
time.sleep(5)
! cat url.txt
import visdom
time.sleep(5)
vis = visdom.Visdom(port='6006')
print(vis)
time.sleep(3)
vis.text('testing')
! cat visdomlog.txt
```

**Comment by OlofHarrysson** [comment]
My localtunnel didn't stay online for very long so I switched to ngrok

```
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip
get_ipython().system_raw('python3 -m pip install visdom')
get_ipython().system_raw('python3 -m visdom.server -port 6006 >> visdomlog.txt 2>&1 &')
get_ipython().system_raw('./ngrok http 6006 &')
! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"
```

**Comment by mohammedawney84** [comment]
how I cam get my domain? "YOURDOMAINHERE"

**Comment by Robotuks** [comment]
> how I cam get my domain? "YOURDOMAINHERE"

any name you come up with works. Just tested

**Comment by OlofHarrysson** [comment]
I want to mention that the serveo server (see the previous answer) isn't always up and running

**Comment by StellaProg** [comment]
"Visit the contents of url.txt using http rather than https and you should be able to access the visdom server."
beginner here doesn't know how to visit url.txt and change contents

**Comment by yofufufufu** [comment]
@StellaProg I tried method above but my file: url.txt is empty

**Comment by yofufufufu** [comment]
@StellaProg I tried method above but my file: url.txt is empty

**Comment by jmandivarapu1** [comment]
> @StellaProg I tried method above but my file: url.txt is empty

Same here did you fix it?

**Comment by yofufufufu** [comment]
> > @StellaProg I tried method above but my file: url.txt is empty
> 
> Same here did you fix it?

use the method that @OlofHarrysson provide:
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip
get_ipython().system_raw('python3 -m pip install visdom')
get_ipython().system_raw('python3 -m visdom.server -port 6006 >> visdomlog.txt 2>&1 &')
get_ipython().system_raw('./ngrok http 6006 &')
! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

**Comment by yofufufufu** [comment]
> > @StellaProg I tried method above but my file: url.txt is empty
> 
> Same here did you fix it?

use the method that @OlofHarrysson provide:

> !wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip
get_ipython().system_raw('python3 -m pip install visdom')
get_ipython().system_raw('python3 -m visdom.server -port 6006 >> visdomlog.txt 2>&1 &')
get_ipython().system_raw('./ngrok http 6006 &')
! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

**Comment by StellaProg** [comment]
> > @StellaProg I tried method above but my file: url.txt is empty
> 
> Same here did you fix it?

No

**Comment by StellaProg** [comment]
> > > @StellaProg I tried method above but my file: url.txt is empty
> > 
> > 
> > Same here did you fix it?
> 
> use the method that @OlofHarrysson provide:
> 
> > !wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
> > !unzip ngrok-stable-linux-amd64.zip
> > get_ipython().system_raw('python3 -m pip install visdom')
> > get_ipython().system_raw('python3 -m visdom.server -port 6006 >> visdomlog.txt 2>&1 &')
> > get_ipython().system_raw('./ngrok http 6006 &')
> > ! curl -s http://localhost:4040/api/tunnels | python3 -c 
> >     "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

No

**Comment by jmandivarapu1** [comment]
Same here it(all above methods) didn't fix my issues. I finally use my server to run the visdom and passed it as an argument

```
environment='AL_Small'
cfg = {"server": "username@server.com","port": 8097}
vis = visdom.Visdom('http://' + cfg["server"], port = cfg["port"])
```

**Comment by mingmingjiang1** [comment]
> Had some connection problems, got it working today by tweaking Jack's solution. Just changed the python to python3
> 
> ```
> ! npm install -g localtunnel
> get_ipython().system_raw('python3 -m pip install visdom')
> get_ipython().system_raw('python3 -m visdom.server -port 6006 >> visdomlog.txt 2>&1 &')
> get_ipython().system_raw('lt --port 6006 >> url.txt 2>&1 &')
> import time
> time.sleep(5)
> ! cat url.txt
> import visdom
> time.sleep(5)
> vis = visdom.Visdom(port='6006')
> print(vis)
> time.sleep(3)
> vis.text('testing')
> ! cat visdomlog.txt
> ```

Is the port  arbitrary ? Should I set it ?

**Comment by RitikaAg** [comment]
> cfg = {"server": "username@server.com","port": 8097}
> vis = visdom.Visdom('http://' + cfg["server"], port = cfg["port"])

I tried following you method by hosting my localhost through ngrok and pasting the url generated by ngrok inside visdom.Visdom(), but I'm getting an error: Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`

**Comment by jmandivarapu1** [comment]
> > cfg = {"server": "[username@server.com](mailto:username@server.com)","port": 8097}
> > vis = visdom.Visdom('http://' + cfg["server"], port = cfg["port"])
> 
> I tried following you method by hosting my localhost through ngrok and pasting the url generated by ngrok inside visdom.Visdom(), but I'm getting an error: Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`

try keeping the ip address of the system and open port. Check if it is working in incognito mode.

**Comment by ahx-code** [comment]
> Just got it working with the below:
> 
> ```
> ! npm install -g localtunnel
> get_ipython().system_raw('/usr/local/bin/python -m pip install visdom')
> get_ipython().system_raw('/usr/local/bin/python -m visdom.server -port 6006 >> visdomlog.txt 2>&1 &')
> get_ipython().system_raw('lt --port 6006 >> url.txt 2>&1 &')
> import time
> time.sleep(5)
> ! cat url.txt
> import visdom
> time.sleep(5)
> vis = visdom.Visdom(port='6006')
> print(vis)
> time.sleep(3)
> vis.text('testing')
> ! cat visdomlog.txt
> ```
> 
> Visit the contents of `url.txt` **using `http` rather than `https`** and you should be able to access the visdom server. ![screen shot 2018-07-17 at 11 48 57 am](https://user-images.githubusercontent.com/1276867/42829315-842feaae-89b7-11e8-9ee9-f6669e4363d1.png)

Dear Jack, thanks for the solution.

The result of the `! cat url.txt` gives me multiple results.  Is it possible to reduce it to 1?

Regards

**Comment by JackUrb** [comment]
It will store all of the URLs passed to it given the current setup, I believe you can use `lt --port 6006 > url.txt 2>&1 &` to replace the file.

**Comment by Omloujain** [comment]
i have to use visdom to visualise outputs of this code https://github.com/JuliaWolleb/Diffusion-based-Segmentation/blob/main/scripts/segmentation_sample.py. i can't do it with google colab. Please any help as soon as possible

**Comment by JackUrb** [comment]
Sorry @Omloujain, the above discussion is the extent of support that we'll be giving for Colab. Hopefully some of the discussion above can help unblock you.

**Comment by Omloujain** [comment]
I tried it but ut didn't work Please can you help me

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JackUrb** [comment]
I don't use colab and don't have any understanding as to why it wouldn't work in general, let alone have any understanding of your specific case.
