### ISSUE TITLE
Simple way to update Images and Plots.

### ISSUE THREAD

**Issue by JackHunt** [facebookresearch/visdom#425]
**Is your feature request related to a problem? Please describe.**
When creating an image or a plot (such as a bar plot), there appears to be no simple way to update it's contents.

**Describe the solution you'd like**
A simple image.update_contents() or something similar taking a numpy array, such that a single window may be reused.

**Describe alternatives you've considered**
Destroying the old window and recreating, though this seems inefficient.

**Comment by JackUrb** [comment]
Hi @JackHunt - this should be doable already if you supply the `win=win_id` parameter to the `vis.image(...)` function. The window with that ID will be reused.

**Comment by JackHunt** [comment]
Ah! So simple. Thank you.
