### ISSUE TITLE
problem of port changed

### ISSUE THREAD

**Issue by LogWell** [facebookresearch/visdom#426]
Hi, when I changed the port to such as 8009, like `python -m visdom.server -port 8009`, then run `python demo.py`, and I get the following msg:

```
The visdom experienced an exception while running: AssertionError('No connection could be formed quickly',)
The demo displays up-to-date functionality with the GitHub version, which may not yet be pushed to pip. Please upgrade using `pip install -e .` or `easy_install .`
If this does not resolve the problem, please open an issue on our GitHub.
```

How should I solve this problem?

Thank you!

**Comment by JackUrb** [comment]
The demo is set to run on the default port. In order to connect to a different port you need to instantiate your visdom client to the new port with `viz = visdom.Visdom(port='8009')`
