### ISSUE TITLE
[Feature Request] WebGL support for line plots

### ISSUE THREAD

**Issue by oguzmann** [facebookresearch/visdom#427]
Some line plots I display are huge, making the Visdom window slow or even freeze. 

Plotly supports scattergl which is capable of displaying a huge amount of data. It would be nice to have a webGL=True kind of a flag as a parameter to Visdom.line.

**Comment by JackUrb** [comment]
Hi @oguzmann - I would love to have webGL support enabled in visdom. Do you have any context as to how this would be done?

**Comment by oguzmann** [comment]
Hi @JackUrb, on plotly, one needs to change the type of trace from 'scatter' to 'scattergl'. 
A boolean field 'WebGL' can be added to opts. Then, 
- Change line 1077 of visdom/py/visdom/__init__.py to: 
`                    'type': 'scatter3d' if is3d else ('scattergl' if opts.get('WebGL', False) else 'scatter'),`
- Change line 644 of visdom/server.py to:
`p['content']['data'][0]['type'] in ['scatter', 'scattergl', 'custom']):`

I couldn't find any other part where 'scatter' is hardcoded, so that should be enough.

**Comment by JackUrb** [comment]
Thanks for implementing this @oguzmann!
