### ISSUE TITLE
update heatmap in the same panel

### ISSUE THREAD

**Issue by ypxie** [facebookresearch/visdom#43]
How to update the image content?

**Comment by lvdmaaten** [comment]
Maybe I misunderstand your question, but doesn't something like this work for you?

```lua
local win = plot.heatmap{X = X1}
-- ...
plot.heatmap{X = X2, win = win}
```

**Comment by ypxie** [comment]
Thank you.
I mean I need to update the image being displayed in a certain window.
Could you give a python example?

**Comment by lvdmaaten** [comment]
In Python it is the same. Each plot function returns a window handle and takes as input an optional window handle `win` that can be used to overwrite the content of the corresponding window.

**Comment by ypxie** [comment]
Thank you!
