### ISSUE TITLE
change the port in visdom and get error:  'No connection could be formed quickly'

### ISSUE THREAD

**Issue by isalirezag** [facebookresearch/visdom#432]
I define a visdom visa selected port 
`python -m visdom.server -port 2002`
and then when i do 
```
viz = Visdom()
assert viz.check_connection(), 'No connection could be formed quickly'
```

I get the error that 
`AssertionError: No connection could be formed quickly`

Any suggestion

**Comment by JackUrb** [comment]
Duplicate of #426, details can be found there.
