### ISSUE TITLE
what does win does

### ISSUE THREAD

**Issue by isalirezag** [facebookresearch/visdom#433]
what happens when i do 
       
        
```

win = viz.scatter(
        X=np.random.rand(255, 2),
        opts=dict(
                markersize=10,
                markercolor=np.random.randint(0, 255, (255, 3,)),
                ),
                )
```
instead of 
```
viz.scatter(
        X=np.random.rand(255, 2),
        Y=(np.random.randn(255) > 0) + 1,
        opts=dict(
            markersize=10,
            markercolor=np.floor(np.random.random((2, 3)) * 255),
        ),
)
```

i mean what ` win = ` does basically

and also how i can show the win name  and update on the window that im showing

**Comment by OguzUzman** [comment]
@isalirezag `win` is the unique name of a window inside an environment. It is a string. In the first snippet, the string `win` will be generated automatically by the library, so in case you want to update the window, you'll need to reuse it as ` vis.scatter(..., win=win)`. You can also use this to manually set the name of your window.

**Comment by JackUrb** [comment]
Closing as @OguzUzman's answer is entirely accurate.
