### ISSUE TITLE
Is there near plan to add more documents?

### ISSUE THREAD

**Issue by ypxie** [facebookresearch/visdom#44]
Great tools!
and I have several questions.
how to create different visdom workspace programmingly?
Is it possible to make the following code work if the window 'loss' has not been initiated before. It's quite inconvenient if I have to create every window first using some dammy data and then update it.
``` 
viz.line(
    X = np.asarray([0]),
    Y= np.array([10]),
    win='loss',
    update='append'
)
```

Thank you~

**Comment by lvdmaaten** [comment]
The `win` handle should exist if you specify it. What do you need dummy data for? A code setup like this should work just fine:

```python
win = None
for n in range(N):
   data = #...
   win = viz.plot(X=data, win=win)
```

This code pattern is used in this Lua example: https://github.com/facebookresearch/visdom/blob/master/example/demo2.lua#L99-109

**Comment by ypxie** [comment]
Thank you for your reply.
But in my case, I'd prefer win be a pre-specified 'string', if I use None as Win, it will return a very complex string rather than a meaningful one.

Fot the line-plot, is there anyway to get access to the data (X, Y) stored in the figure?
Thank you!

**Comment by lvdmaaten** [comment]
You can use a pre-specified `win` string:

```python
vis = visdom.Visdom()
win = visdom.text{text = 'test', win = 'my_window'}
print(win)
```

This will print `'my_window'`.

There is currently no way to access the data on the server from the Python/Lua wrapper, but you can use the `update='append'` option to add new data to the existing data.

**Comment by ypxie** [comment]
Thank you for your answering.
For example, I have already  many  pairs of (x,y) in a plot.
But then I re-load my program and want to append new data points to the end of that plot.
But  the current x will start from 1 again and I don't actually know how many points in the original plot. so It will be hard to append to the right place.
Thank you~
