### ISSUE TITLE
How to plot two histograms in the same window ?

### ISSUE THREAD

**Issue by aelnouby** [facebookresearch/visdom#453]
Hi, 

I need to compare two histograms together, I would like to plot them in the same window. When I pass legend option Visdom crashes.

**Comment by JackUrb** [comment]
Visdom histograms currently do not support more than one entry at a time. You can directly display plotly figures if you use the feature introduced in #402, which will let you display any kind of histogram offered by the [Plot.ly Python Library](https://plot.ly/python/histograms/)

**Comment by aelnouby** [comment]
I see. Thank you.

**Comment by JackUrb** [comment]
Of course, it'd be possible to more natively support this feature in the same way we do for line and scatter plots. Feel free to open a feature request if you find that the Plot.ly version doesn't suit your use case.
