### ISSUE TITLE
[Feature Request] base url parameter

### ISSUE THREAD

**Issue by PVShutov** [facebookresearch/visdom#464]
When configuring the server with several webapps, parameter for setting base url for visdom server would be very useful. Also, I have not found a temporary solution to this issue at this time.

**Comment by JackUrb** [comment]
Hi @PVShutov - I'm fairly sure that Tornado doesn't have native support for doing this, so adding a base URL would essentially amount to additional path manipulation. You may have luck directly editing the server file to add your prefix to all of the paths here:
https://github.com/facebookresearch/visdom/blob/1edf5829ee20b79f7230a63ecae3d74e83f616eb/py/visdom/server.py#L147
You would then need to update the visdom python client to be able to target a new hostname, which would include parsing out the components of the url here: https://github.com/facebookresearch/visdom/blob/1edf5829ee20b79f7230a63ecae3d74e83f616eb/py/visdom/__init__.py#L409
as well as here:
https://github.com/facebookresearch/visdom/blob/1edf5829ee20b79f7230a63ecae3d74e83f616eb/py/visdom/__init__.py#L450

If you do get this working I'd be happy to help generalize it as a feature if you open a PR.

**Comment by PVShutov** [comment]
Hi @JackUrb! Thanks for your answer! It seems to work, but for full resolve this problem, it's need also to change the static and extensions url.

**Comment by JackUrb** [comment]
Ah good point, the static path is set up here currently: https://github.com/facebookresearch/visdom/blob/1edf5829ee20b79f7230a63ecae3d74e83f616eb/py/visdom/server.py#L93
Extensions however is currently a bug though, we don't actually have the extension files set up.
