### ISSUE TITLE
Subplots/Multiple plots in the same window

### ISSUE THREAD

**Issue by marcociccone** [facebookresearch/visdom#465]
Hi, is it possible creating subplots or having multiple separate plots in the same window?

**Comment by JackUrb** [comment]
Right now this is only supported by using plotly's python library to create the figure and then using visdom's plotlyplot function. It isn't supported using the regular plotting functions.

Plotly docs here:
https://plot.ly/python/subplots/

**Comment by marcociccone** [comment]
that's perfect I can use that. Thank you for your help.
