### ISSUE TITLE
'>' not supported between instances of 'float' and 'NoneType'

### ISSUE THREAD

**Issue by TJJTJJTJJ** [facebookresearch/visdom#467]
When I tries to init vis = Visdom(env='default') and has start Visdom like python -m Visdom, it always says that
 " INFO:root:Opened visdom socket from ip: 127.0.0.1
                                  '>' not supported between instances of 'float' and 'NoneType'",
and I have located it witch is at line 429 "self.socket_thread.start()" in the __init__.py. I don't know why.
Because if I use another computer, it works well, but it could't works  at this compouter.
Thank you.

**Comment by JackUrb** [comment]
#450. Please install visdom from source or dosncrade websocket client to resolve.
