### ISSUE TITLE
Attribute error: nonetype object has no group

### ISSUE THREAD

**Issue by JustianJK** [facebookresearch/visdom#474]
Hi, I'm new to this Program Python / Instagram Bot
I'm getting this message .
Is there anyhelp i can use? 
 
![41520228_279042582820240_5460013918485217280_n](https://user-images.githubusercontent.com/43218342/45446203-98539c00-b6cc-11e8-8ef9-591c0305feb7.png)

**Comment by JackUrb** [comment]
Hi @JustianJK, visdom is not an instagram bot. Are you sure you're posting in the right place? `instabot` doesn't exist anywhere in our codebase.
