### ISSUE TITLE
Adjusting hyperparameters on the fly

### ISSUE THREAD

**Issue by tobyclh** [facebookresearch/visdom#475]
Hello, I am trying to see whether anyone tried to adjust hyperparameters on the fly with wisdom.
Currently, the way I handle it is 
1. obtain the new value of the hyperparameter through the callback
2. put the value in a queue
3. update the all hyperparameters changed after each training loop, after optim.step() before the next optim.zero_grad()  

However, even when I do so, it raises RuntimeError

>   File "/models/TrainModel.py", line 96, in train
    loss.backward()
  File "/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function ExpandBackward returned an invalid gradient at index 0 - expected shape [] but got [1]

EDIT:
I understand this would raise error when done inside the training loop (since the change cannot be differentiated), that is why I separated it outside the training loop.

**Comment by JackUrb** [comment]
Hi @tobyclh - based on the error it would seem there's an issue with something being passed in, namely that there's a difference between scalars (`torch.Size([])` tensors) and size 1 tensors (`torch.Size([1])`). Is there anything that you're setting that could match this description?
