### ISSUE TITLE
[Errno 97] Address family not supported by protocol python socket

### ISSUE THREAD

**Issue by skyoung** [facebookresearch/visdom#478]
**Environment:** Ubuntu 16.04.4 LTS, python-3.5.2

When I run the latest visdom, I got the following error:
`[Errno 97] Address family not supported by protocol python socket` consistently. Then I downgrade the visdom to 0.1.7, the error disappears. 

Could anyone fix this?

**Comment by JackUrb** [comment]
Is this an issue launching the visdom server or trying to use the python client? Have you tried using the `-port` argument to use a different port?

**Comment by skyoung** [comment]
It happens when I add the line `self.viz = Visdom()` in my code. But the program runs without stop, but keep printing the error message. When I remove this line, i.e. not using visdom. the error disappears.

**Comment by JackUrb** [comment]
But you are able to run the server with no problems? Have you tried using a different port?

**Comment by skyoung** [comment]
When the server starts, everything is ok. Seems like in 0.1.7. visdom does not print error message without starting server. Thanks for helping.

**Comment by JackUrb** [comment]
If trying a different port doesn't work, you can also try to instantiate a client with `vis = visdom.Visdom(use_incoming_socket=False)`
