### ISSUE TITLE
Allow scatter plots with more legend items than number of classes

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [facebookresearch/visdom#480]
This line forces the number of items in the legend to be the same as the number of classes.

https://github.com/facebookresearch/visdom/blob/master/py/visdom/__init__.py#L1140

In my case, not all the classes can be sampled in a particular batch. `len(opts['legend'])` becomes greater than `K`.

**Describe the solution you'd like**
Allow number of legend items *at least* the number of classes 

**Describe alternatives you've considered**
I can manually remove legend items not used in this particular batch, but this is cumbersome.

**Comment by JackUrb** [comment]
Seems like a reasonable change to me, I'd be happy to accept a PR that implements a solution that makes sense to you, though I imagine it'd need to take in a list of mappings, considering [this line](https://github.com/facebookresearch/visdom/blob/2ef12d43536360405c5a065e9f3eed282b8a76bf/py/visdom/__init__.py#L1149) just indexes into the legend items directly. You could make an optional `legendmap` opt that has to be the length of `K`, mapping entries in order in K to their values in the legend, and then default that to the array `[0 ... K-1]` if it's not provided.

**Comment by JackUrb** [comment]
Ah right right - Y is supposed to serve this purpose in scatter
