### ISSUE TITLE
Can Visdom update its graph in a live way for incoming data?

### ISSUE THREAD

**Issue by hsluoyz** [facebookresearch/visdom#483]
At most times, the model training process can be very slow. I don't want to see all the results when the training ends.

I want to see graphs (like loss) in a dynamic manner when the data still come in, just like a monitoring dashboard. So I can terminate my model immediately when the result doesn't seem right at some point. Can Visdom fulfill my requirement?

**Comment by JackUrb** [comment]
This is one of the things visdom was built for. You can do all of your plotting using the `update=append` functionality to see curves in real time. Look at the related cases in `examples/demo.py` that use the append argument.
