### ISSUE TITLE
Deploy visdom server and client on two different machines

### ISSUE THREAD

**Issue by everglory99** [facebookresearch/visdom#493]
Hi, 
I am wondering if it is possible that visdom client and server are on two different boxes. For example, I want to deploy visdom server in one box but have multiple boxes for model training and each of them will use visdom client to connect to server. Thanks for the help!

**Comment by JackUrb** [comment]
This is visdom's primary use case - set one machine as the server and then have all the training machines log to a `visdom.Visdom()` object with the correct arguments for hostname and port

**Comment by kidconan** [comment]
@JackUrb 
Suppose that I have two machine A and B as well as two python script P1.py on A and P2.py on B.  
Both P1.py and P2.py have the function to plot figure by visdom. 
If I set machine A as the server and run run P1.py , and then run P2.py when P1.py is still running. 
Will P2.py rewrite or clean up the figures which are created by P1.py

**Comment by JackUrb** [comment]
Unless both are supplying the same window name to the `win` argument, both should be able to plot at the same time into two different panes. If you'd like you can also set each to use different values for the `env` argument so that you end up separating figures from each run into two separate environments.

**Comment by kidconan** [comment]
@JackUrb  I run P1.py at fisrt , and then run P2.py. 
However, I found the `env`  of P2.py is the subdirectory of the `env` of P1.py. But I hope both are in the same directory. What should I do?

**Comment by JackUrb** [comment]
Sorry I'm having a tough time telling what you're trying to do. Env is not relating to subdirectories, it's a parameter you pass to your visdom calls. 

Give me examples of `vis.<>` calls from P1.py and P2.py.
