### ISSUE TITLE
Plots Do Not Append in Torch

### ISSUE THREAD

**Issue by mdushkoff** [facebookresearch/visdom#494]
**Bug Description**
When trying to append plots in Torch7, the rendered plots replace data instead.

**Reproduction Steps**
Execute the following script in the Torch7 environment:
```lua
vis = require 'visdom'()
x = torch.linspace(1, 10, 10)
y = torch.randn(10)
win = vis:line{X=x, Y=y}
vis:line{X=x+10, Y=y, update='append', win=win}
```

To demonstrate that it is indeed the update behavior and not just the line plot:
```lua
vis = require 'visdom'()
x = torch.linspace(1, 10, 10)
y = torch.randn(10)
win = vis:scatter{X=torch.cat(x, y, 2)}
vis:scatter{X=torch.cat(x+10, y, 2), update='append', win=win}
```

**Expected behavior**
The plots should append to the previously plotted data.

**Screenshots**
Before append:
![screenshot from 2018-10-21 17-45-26](https://user-images.githubusercontent.com/1088699/47272842-25ee9b00-d559-11e8-9bd9-de5b1bace3da.png)

After _"append"_:
![screenshot from 2018-10-21 17-44-00](https://user-images.githubusercontent.com/1088699/47272843-2ab34f00-d559-11e8-9e66-321a3c88cda9.png)

**Additional context**
Applies to the current version `0.1.8.5` cloned from GitHub.  Previous versions did not experience this issue, although the cutoff point is currently unknown.

**Comment by JackUrb** [comment]
Thanks for flagging @mdushkoff - I'll investigate

**Comment by JackUrb** [comment]
Unfortunately we will be abandoning torch support - `0.1.8.4` has been marked as the last version with stable support, and a [release](https://github.com/facebookresearch/visdom/releases/tag/v0.1.8.4) has been created for it.
