### ISSUE TITLE
Support Horovod ?

### ISSUE THREAD

**Issue by AmberCheng** [facebookresearch/visdom#501]
Horovod is a frame which mixes pytorch with tensorflow, I wonder can visdom be used in Horovod?

**Comment by JackUrb** [comment]
@AmberCheng - I haven't used Horovod myself, however it appears to just be the distributed framework. Visdom is able to receive plot data from multiple locations, so I'd assume there's a way to get the two to work together, however I don't have the context on what you're trying to accomplish.

**Comment by AmberCheng** [comment]
> @AmberCheng - I haven't used Horovod myself, however it appears to just be the distributed framework. Visdom is able to receive plot data from multiple locations, so I'd assume there's a way to get the two to work together, however I don't have the context on what you're trying to accomplish.

I did realize the test of combine visdom and horovod. Thank you ~~

**Comment by AmberCheng** [comment]
@JackUrb I did realize the test of combining visdom with horovod. Thank you ~~
