### ISSUE TITLE
Don't zoom out when a value is appended to a line chart

### ISSUE THREAD

**Issue by Vermeille** [facebookresearch/visdom#503]
Hi!

When appending to a line chart, whatever state was the view in is discarded.
That prevents from observing closely the evolution of the line chart whenever the amplitude of the variation diminishes, for instance.

Thanks!

**Comment by JackUrb** [comment]
Hi @vermeille - this is one of our longest open issues (#171) as there is no clean solution to the problem currently. #395 is a core implementation change that would enable this to be solved cleanly, however we're missing one piece of that currently (a json diff format that works in both python and JavaScript). Once that comes together a number of open issues become unblocked. If you're interested in helping out, check out #395

**Comment by Vermeille** [comment]
Apologies for the redundancy.

I might def try and contribute if work gets less busy, thank you for the pointer :)
