### ISSUE TITLE
How to draw 2 lines with different lengths in the same window?

### ISSUE THREAD

**Issue by Mactarvish** [facebookresearch/visdom#504]
I've found that the viz.line can draw many lines with the same lengths in a window, but if there is a method to draw lines with different lengths in the same window? Thanks in advance~

**Comment by JackUrb** [comment]
You can append new lines of different lengths by using the `update='append'` argument and `name='trace-name'` for any trace name that isn't already in the plot. That will create a new line with that name.

**Comment by Mactarvish** [comment]
Thank you very much! I've solved it.~
