### ISSUE TITLE
Bad handling of corrupt json environment files

### ISSUE THREAD

**Issue by amitibo** [facebookresearch/visdom#507]
**Bug Description**
On startup Visdom loads all json environment files available in `~/.visdom/`. If one of the json files is corrupted, Visdom will crash without a helpful traceback, i.e. it doesn't state which json file crashed the server.

**Reproduction Steps**
A corrupted json file can happen when the the server crashes in the middle of updating a json file, or in the case of storage device failure.

**Expected behavior**
This situation can be handled in several ways:
1. re-raise an exception stating the faulty json file.
2. throw a warning and skip the faulty environment file.
3. move the faulty file to a `trash` folder and throw  a warning.
3. skip the faulty environment file but create a corresponding visdom environment with a text pane stating the error.

**Additional context**
The faulty line is the following:
https://github.com/facebookresearch/visdom/blob/13f179d7acdb638c260779a53ad1f32195b24915/py/visdom/server.py#L150

I can create a PR once a solution is decided upon.

**Comment by JackUrb** [comment]
Thanks for isolating the issue and providing some potential solutions here @amitibo - I think options 2 or 3 are the best, likely 2 (as it prevents additional complexity of dealing with moving files).

**Comment by JackUrb** [comment]
Fixed in #508
