### ISSUE TITLE
How can I use visdom on HPC?

### ISSUE THREAD

**Issue by curry111** [facebookresearch/visdom#509]
Hi guys :sweat_smile: :sweat_smile:  I read some issues that are related to that but I still can't make it work. I want to see the visualization that are produced in the compute cluster nodes.
I am using SLURM job scheduler, where I submit a job by creating a `.sh` file and then submit a job.
Example of job script (`job.sh`)
`
#!/bin/bash      
`
`
#SBATCH --job-name=visdom_example 
`
`    
#SBATCH --partition=gpu   
`
`
#SBATCH --gres=gpu:2   
`
`
#SBATCH --nodes=2 
`
`
python example.py
`
And then I run the command `sbatch job.sh`.
How can I use visdom in this setup?
Any help will be really really appreciated :sweat_smile: .

**Comment by JackUrb** [comment]
As long as you have your visdom server running on some machine that is accessible from the other nodes at `<server_hostname>:<server_port>`, you can simply have all of the other nodes connect to it using `visdom.Vidsom(server=<server_hostname>, port=<server_port>)`

**Comment by curry111** [comment]
@JackUrb I'm sorry, I am not very knowledgeable about networking and those stuff. I understood your answer. You want me to start the server (e.g. using `python -m visdom.server -port 9999`) at node A(that has a web browser on it) and then use visdom's functions on the other nodes (i.e. `visdom.Vidsom(server=<The IP address of node A>, port=9999)` and `vis.text('Hello, world!')`), So that I can see the visualizations on node A's web browser, right? Is that what you meant? :sweat_smile:. but the compute nodes in the HPC don't have web browser to show visdom visualization. I want to use visdom's functions on the compute nodes (e.g. `vis.text('Hello, world!')`) and see the visualizations on my web brower.

**Comment by curry111** [comment]
@JackUrb Thank you so much. I will try those things. Just one last thing please, should I run this line `python -m visdom.server -p 9964` on my laptop or on the HPC node?

**Comment by JackUrb** [comment]
That should be run on the node (a location that all the other nodes have access to)

**Comment by curry111** [comment]
@JackUrb yes I did it. Thank you so much :smile:

**Comment by KnightOfTheMoonlight** [comment]
@JackUrb  what if there is some node that is not accessible by the non-intranet. My server has one node which is the login-in node, other nodes can only be shared by intranet. the login-in can only run 30-mins jobs, which is not practice. So I need to run the code in the intranet nodes. But that node can not be accessed by my local machine. Do you have any suggestions?

**Comment by JackUrb** [comment]
Sorry @KnightOfTheMoonlight, I don't have any good guidance on being able to run something like that. If you're logged into the network from the login node, are you able to remain doing things? If so there's likely a shell process that can run longer than the 30 mins? But yeah I don't actually have any strong understanding of your network configuration, and may not be able to help even if I did.

**Comment by KnightOfTheMoonlight** [comment]
@JackUrb 
I tried to restart visdom server on the login node. But then I can not see the plots. I have no idea why yet.
