### ISSUE TITLE
Any command to shut down or restart visdom server?

### ISSUE THREAD

**Issue by luzhilin19951120** [facebookresearch/visdom#512]
I would like to ask if there exist any command like "python -m visdom" that restart or kill certain visdom server?

And besides:

Are there any way we can print the current visdom version?

Are there any way we can print the current visdom env_save_path?

**Comment by JackUrb** [comment]
As of now we don't have a specific kill or restart command for the server, but I'd be happy to accept a PR that introduces support for anything better than the `CTRL-C` approach we currently have.

`visdom.__version__` should show the version.

I don't believe we have a command for showing the `env_save_path` other than directly accessing the variable on your `Visdom` instance

**Comment by luzhilin19951120** [comment]
@JackUrb  actually, I encounter two problem when using visdom:

1. I can't find any of the json files which supposed to be in ~/.visdom according to your readme description. On the same server I start several visdom.server using different ports, and none of their json file is found.

2. The reason that problem 1 troubles me is that I tried to kill visdom env using code instead of GUI. 
 - Based on visdom 0.1.8.5 that installed with "pip install visdom", the only thing I find is Visdom.delete_env(). However, this function need all envs' names. And I didn't find any way to get it.
- Based on up-to-date visdom version installed with "pip install -e visdom", I even failed to start any visdom.server. And the Visdom().get_env_list() function can work properly as well. It returns an empty string, causing JSON ERROR.

So how would I gracefully manage all my envs according to your design?

**Comment by JackUrb** [comment]
The env list issues have been pushed to the pip version a while ago. To the point of having commands to shutdown the visdom server, the below snippet can be adapted to scripts that launch a visdom server and shut it down when desired:

```
from visdom import server
import threading
from zmq.eventloop import ioloop
ioloop.install()  # Needs to happen before any tornado imports!
import tornado.ioloop      # noqa E402: gotta install ioloop first
import tornado.httpserver  # noqa E402: gotta install ioloop first

my_loop = None

def instance_runner(port, base_url):
    global my_loop
    my_loop = ioloop.IOLoop()
    app = server.Application(
        port=port,
        base_url=base_url,
        env_path=env_path,
        readonly=False,
        user_credential=None,
        # desired kwargs
    )
    http_server = tornado.httpserver.HTTPServer(
        app, max_buffer_size=1024 ** 3)
    http_server.listen(port)
    logging.info("Application Started")
    my_loop.start()
    http_server.stop()
    logging.info("Application Ending")

def launch_instance(port):
    server_thread = threading.Thread(
        target=instance_runner,
        args=(port,))
    server_thread.start()

def shutdown_instance(port):
    global my_loop
    def stop_and_free():
        my_loop.stop()

    my_loop.add_callback(stop_and_free)
```
