### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by JohannaSpr** [facebookresearch/visdom#513]
Is the data (images and grafics) visualized via visdom sent somewhere? It seems like only the grafics are created with plotly... I am working with a sensible dataset and would like to use offline mode if possible!

**Comment by JackUrb** [comment]
You should be able to run visdom perfectly fine on a device with no external internet connection once the required packages are downloaded. Visdom itself is not sending any data anywhere.

**Comment by refaev** [comment]
Is there a way to download the required packages and burn them for an offline computer?
How would I tell visdom where to look for them once it was installed on the offline computer?

Thanks!

**Comment by JackUrb** [comment]
You can run the `./download.sh` script on a machine that is connected to the internet, and then copy what it downloads onto the offline computer into the same location that they were after the download. (can just copy the whole `visdom` directory over)
