### ISSUE TITLE
Where is envs buffers?

### ISSUE THREAD

**Issue by luzhilin19951120** [facebookresearch/visdom#514]
I encounter a problem when trying to find the JSON files of all the visdom envs.

First of all, I can not find where the visdom server save all the envs buffer path. I use buffer path" referring to the path where all the __unsaved envs__  are kept. This buffer seems to be automatically cleared when the visdom server is shut down. However I need to find and use it when the server is still on. 

__Its path is definitely not "~/.visdom", and I would like to know where it is__

The other thing is that I need to save some of the good envs and reload them freely. So far, the save button can save the envs file to "~/.visdom", but I can not find anyway to use these JSON files other than simply reboot the server. 

__How can I use another server (That say new IP new port) to load all the JSON file I pick(I would get the file from save button and move them elsewhere) from any path I set?__

**Comment by JackUrb** [comment]
This 'buffer' is entirely in the server's python local memory in `self.state[eid]`, it doesn't exist as a file. Hard saves are the only thing that push data to a file.

For the latter question you can move the files to a different folder and start the server with the `-env_path <directory>` option to point to that folder.

**Comment by luzhilin19951120** [comment]
@JackUrb Thanks~ This is what we are doing now. ^_^
