### ISSUE TITLE
How to set up visdom server when only have access to one of the server's ports over ssh?

### ISSUE THREAD

**Issue by 12cheny** [facebookresearch/visdom#517]
**Bug Description**
Please enter a clear and concise description of what the bug is.

**Reproduction Steps**
Enter steps to reproduce the behavior:

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Screenshots**

**Client logs:**
For issues that make it to the point of reaching the frontend in a browser, please include the javascript logs from that browser. In Chrome, javascript logs can be found via View -> Developer -> JavaScript Console.

**Server logs:**
For any issues, please include the server logs. These are printed directly to stdout on the machine running `visdom` (`python -m visdom.server`).

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by JackUrb** [comment]
Hi @12cheny - you've provided no details as to the steps you've taken to try to connect, so I can only guess. 

Do you have the server running in the background? (`python -m visdom.server`)

Have you set the hostname and port arguments of your `visdom.Visdom` instance to point to wherever your server is running?

**Comment by 12cheny** [comment]
I'm sorry that I didn't describe my question clearly, I run (python -m visdom.server) in my server(1.1.1.1:1011), and I can't open 1.1.1.1:8097 in my own computer. And 1011 is the port of my gpu server account.

**Comment by JackUrb** [comment]
On Dec 4, 2018, at 10:43 AM, 12cheny <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm sorry that I didn't describe my question clearly, I run (python -m visdom.server) in my server(1.1.1.1:1011), and I can't open 1.1.1.1:8097 in my own computer. And 1011 is the port of my gpu server account.

**Comment by JackUrb** [comment]
Right I understood - if you're running the visdom server process on a server in which your access port is restricted to 1011, you won't have the access to connect over port 8097 (which is what is happening when you use 1.1.1.1:8097). I'm unsure what the rest of your network setup is like though, do you have direct access to the rest of the ports on the 1.1.1.1 domain? If not it's likely that 1011 is bound so you won't be able to run the visdom server on that port directly. You'll likely need to set up an ssh tunnel.

**Comment by 12cheny** [comment]
I have solved this problem, maybe I can share my solution to those who are't also the root account of their server, I use mobaxterm to set up the sshtunnel, It's very convenient.
