### ISSUE TITLE
Visdom posts to localhost server failed connect via proxy status 407 when not root usr

### ISSUE THREAD

**Issue by HugoAutumn1024** [facebookresearch/visdom#518]
hello
I have run visdom server (python3 -m visdom.server)on my server. and i can open the link "http://localhost:8097".
but i try to excute python demo like:
```
import  visdom
import torch as t
vis = visdom.Visdom()
x = t.arange(0,30,0.01)
y = t.sin(x)
vis.line(X=x,Y=y,win='sinx')
```
i got this error from python running time:
```
failed CONNECT via proxy status: 407
failed CONNECT via proxy status: 407
Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.
```
I tried to use_incomming_socket=False option,but  when i refresh browser ,its still empty.
I guess python can not connect to visdom server. 
Hope someone can help.Thanks

**Comment by 12cheny** [comment]
Oh, I can't open the link...

**Comment by JackUrb** [comment]
Are you running the demo on the same machine that you're running the server on? Do you have any errors in your javascript console?

**Comment by HugoAutumn1024** [comment]
Yes.i m running the demo on the same machine which i m  running the server on.
i do have some error in js console like follows, but i dont think thats the problem:
![image](https://user-images.githubusercontent.com/45255374/49483393-edd3bb00-f86d-11e8-9f13-1018d141a3ac.png)
And if i run the demo with root usr, it works fine,i can see the visualization in browser. but if i run the demo with normal usr , i get the proxy error.

**Comment by JackUrb** [comment]
It's possible you need to specify username and password authentication into your session when not running as the root user, according to the [requests](http://docs.python-requests.org/en/master/user/advanced/#session-objects) library. Relevant code location for that would be here: https://github.com/facebookresearch/visdom/blob/db27b3483e118d76c320a7817b10c2f60e38b774/py/visdom/__init__.py#L405

**Comment by sljh0214** [comment]
I had a similar situation.
You need to specify a server.
Do not enter localhost, change it to enter ip.
vis = visdom(server='http://X.X.X.X')

**Comment by JackUrb** [comment]
This is properly supported with proper proxy handling since #538.
