### ISSUE TITLE
Error related to Json while starting wisdom

### ISSUE THREAD

**Issue by beenazing1** [facebookresearch/visdom#519]
**Bug Description**
Please enter a clear and concise description of what the bug is.

**Reproduction Steps**
Enter steps to reproduce the behavior:

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Screenshots**

**Client logs:**
For issues that make it to the point of reaching the frontend in a browser, please include the javascript logs from that browser. In Chrome, javascript logs can be found via View -> Developer -> JavaScript Console.

**Server logs:**
For any issues, please include the server logs. These are printed directly to stdout on the machine running `visdom` (`python -m visdom.server`).

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by beenazing1** [comment]
Hi,

Im running into an error:

decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

everytime I start json from python with the command python -m visdom.server

I have ensured I have the latest version of visdom installed.
Any help with this error will be appreciated.

**Comment by JackUrb** [comment]
Hi @beenazing1 - the information you've provided is not enough for me to know what's going on, I would need the full stack trace as we don't have any `decoder.py` files in this repo, and I don't know what's calling that.

**Comment by JackUrb** [comment]
Closing as there still aren't enough details for me to know what's going on here. Feel free to reopen with details.
