### ISSUE TITLE
Load replay_log file on the web interface directly

### ISSUE THREAD

**Issue by memray** [facebookresearch/visdom#520]
Hi,

Now we can let server load a previous visdom log by running `vis.replay_log(replay_log_file)` in a script, but I wonder if we can implement a drag-and-drop feature on the web interface to load a log directly. It would be very handy if we run many experiments offline and want to compare them later on.

Thanks,
Rui

**Comment by JackUrb** [comment]
Hi @memray - this idea is the right kind of thinking, however I don't see a clear way to implement this specific interaction that makes sense in the current system. Log files include writing to specific (and potentially multiple) envs, which drag and drop wouldn't really provide expected functionality. This behavior is likely more suited as the 'import' functionality for a specific env once we have in browser import/export. Import/export env is something we're very interested in having however.

**Comment by memray** [comment]
Hi @JackUrb - Yes you are right. What I was proposing is just an import/export functionality on the browser end. The drag-and-drop may make it easier to operate.

**Comment by JackUrb** [comment]
Thanks for the suggestion - I'm definitely going to consider adding drag and drop functionality when we get around to implementing env import/export
