### ISSUE TITLE
How to resize/change scale of plotly plot

### ISSUE THREAD

**Issue by richardrl** [facebookresearch/visdom#524]
My plot looks like this:
https://i.snag.gy/sjzNfF.jpg

It's really hard to see the curve in the early stages when the axis scale is like this. Tensorboard has a button that fits the plot, does visdom have a similar UI tool?

Click or dragging just moves the image around.

**Comment by JackUrb** [comment]
Are you providing axis bounds in your opts? Plots should auto scale by default and I'd only expect to see this if auto scale was manually overridden. What args are you passing to the `line` function?

**Comment by JackUrb** [comment]
Oh wait it seems you're plotting using the `matplotlib` backend, which doesn't have any interactive features.

**Comment by JackUrb** [comment]
Closing as I have no additional context and the issue hasn't been updated in a while. @richardrl if you're having difficulty using the `line` function rather than `matplotlib` feel free to reopen and ask for more context.
