### ISSUE TITLE
Chrome Image Resize

### ISSUE THREAD

**Issue by dzimmerer** [facebookresearch/visdom#525]
**Bug Description**
Under Chrome when resizing the image with scrolling the scaling is quite harsh, it somehow either makes the image quite big or very small (~ 1/8 of the size)

**Reproduction Steps**
1. Open visdom with image pane in chrome
2. Ctrl + Scroll on image

**Expected behavior**
Smoother resizing of an image (with factor ~0.8 or so instead of ~0.1)

**Comment by JackUrb** [comment]
Feel free to tweak the settings and open up a PR with something that works well. The code is in `ImagePane`. I believe panning could also use a better method that scales with image size as scroll corresponding to a fixed pixel offset is a huge jump on low resolution photos.

**Comment by JackUrb** [comment]
@dzimmerer Thanks for fixing this in #526!
