### ISSUE TITLE
Visdom will raise Proxy Error if a network proxy is used 

### ISSUE THREAD

**Issue by huguyuehuhu** [facebookresearch/visdom#528]
Visdom version:  0.1.8.5. 
The netork of my compture is obtained by another computer via a network Proxy (i.e, I added two command `export http_proxy="http://IP:port"` and `export https_proxy="https://IP:port"` in my `.bashrc`;
1. With this Poxy,  when run code contains visdom will raise an proxy related error in the below:
![image](https://user-images.githubusercontent.com/25881545/50165455-00df9400-0320-11e9-9220-7a66875656cb.png)
2. when cancelling the proxy by removing the two commands, visdom will works.
3. I think this is maybe related to the issuses #515  and #518 .
4. So, how could I use Visdom compatiblly with a network Proxy ? Thank you in advance!

**Comment by JackUrb** [comment]
Ultimately visdom has incomplete proxy support. You can help us out with this by adding proxy support to the session that is established between the python visdom client and the server here: https://github.com/facebookresearch/visdom/blob/bdbed59a2ec469ae61d74d4c94c50d5ae0e8629d/py/visdom/__init__.py#L419

This [answer](https://stackoverflow.com/a/30839005) describes how to add proxies to a session. If you get it working I'd be happy to accept the fix!

**Comment by JackUrb** [comment]
Proxy support has been added in #538. Thanks @suvrat96!
