### ISSUE TITLE
Programatically create an env

### ISSUE THREAD

**Issue by emanjavacas** [facebookresearch/visdom#53]
In the docs it's said that it's possible to programatically create envs. However, I haven't been able to find an example of this in the python example, nor did it become evident after checking the source code.
Could anyone give a hint?

**Comment by hashbangCoder** [comment]
You can just pass the `env` argument to the figure like in #26 and it creates a new `env`. 
You have to refresh the browser to view the updated envs

**Comment by emanjavacas** [comment]
Thanks!

The refreshing part was the tricky one in my case :-) Seeing all this reactivity in the front-end I wasn't gonna think that I would have to refresh the browser at all...
