### ISSUE TITLE
After running python -m visdom.server,some scripts can't download

### ISSUE THREAD

**Issue by XiaolinDeng** [facebookresearch/visdom#532]
After running python -m visdom.server
It shows:
Downloading scripts. It might take a while.
ERROR:root:Error 404 while downloading https://unpkg.com/layout-bin-packer@1.4.0
It's Alive!

And after it done, it seem working well,but after i enter the localhost:8888,
i found it has warning:
WARNING:tornado.access:404 GET /static/fonts/layout_bin_packer (::1) 0.64ms
i has tried to uninstall the package,and delete file in sitepackge root,then using porxy to download it
but just fail.

i wanna ask if i can download this file from other site,or can you guys can give me some sugession to solve this problem.

**Comment by JackUrb** [comment]
Hi @XiaolinDeng - See #529. It seems unpkg changed some of their routing in the last week.

**Comment by XiaolinDeng** [comment]
Thanks,i have solved this problem by coping script from friend who has install visdom and work correctly
