### ISSUE TITLE
* in filter window removes everything from the webpage

### ISSUE THREAD

**Issue by Maocx** [facebookresearch/visdom#535]
**Bug Description**
When entering * in the filter text window, all the elements on the window disappear, including the filter text window. To get out of this state I had to clear the local storage.

**Reproduction Steps**
Enter steps to reproduce the behavior:
(Note: I use Firefox)
1. Open visdom
2. Enter * in filter text window
3. Hit the erasor
4. When the page is refreshed, the problem persists
5. When the server is restarted, the problem persist

**Expected behavior**
I wanted to close all windows, but not get stuck in an infinite loop :)

**Screenshot**
![image](https://user-images.githubusercontent.com/7448312/50698849-6df46880-1046-11e9-8b5c-3bf3c5b5b267.png)

**Comment by huguyuehuhu** [comment]
Visdom 0.1.8.5 & chrome

I have met a similar problem about 20 days ago, when enter` [` or` \` in the filter text window.  
I temporarily get it work by the following solution:
1. Use F5 on your keyboard to refresh the browser, did you see the window will  recover, and disappear again immediately?
2. If so, you can continually  hit  F5 on your keyboard, at the same time, use  your mouse to click the eraser which is behind the filter text window. 
3. Once you successfully click on the eraser, the inputted text will be removed, then the window will recover.

**Comment by JackUrb** [comment]
Hi @Maocx - this error (invalid pattern parsing) has been solved in the source version of visdom, but hasn't yet been pushed to PyPI. If you install from source it should resolve the issue

**Comment by JackUrb** [comment]
Version `0.1.8.6` has been pushed to PyPI, so this issue should no longer persist. Try upgrading your visdom version.
