### ISSUE TITLE
Independently add two lines to plot

### ISSUE THREAD

**Issue by emanjavacas** [facebookresearch/visdom#54]
I am trying to send data to a line plot from two different processes, each of which is responsible for a single line. Currently I do this by keeping in memory the last point for each line so that when data comes for one line I can redundantly overwrite the last point assigned to the other.
While this works (with limitations), I'd like to implement a method that allows me to update a line in a plot independently any other possible lines in the plot.
Is something like this possible with the current version of the library?

**Comment by ajabri** [comment]
Hi @emanjavacas ,

Have you tried the `updateTrace` method? https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L394

You can specify the `name` of a trace and whether to `append` or `replace`. If you give a new `name`, a new trace will be added (as in the example here: https://github.com/facebookresearch/visdom/blob/master/example/demo.py#L172).

**Comment by emanjavacas** [comment]
Oh thanks, 
Somehow I hadn't checked updateTrace yet.
