### ISSUE TITLE
Feature Request: Image zooming

### ISSUE THREAD

**Issue by cpdurham** [facebookresearch/visdom#55]
Heatmap has a nice way to zoom around and scale, was wondering about getting this into the image plot

**Comment by lvdmaaten** [comment]
Good suggestion! (We actually had this in an earlier implementation of visdom.)

As a quick work-around, you can use the zoom functionality of your browser (press Command and + in Chrome / OS X) to zoom in on an image.

**Comment by cpdurham** [comment]
Cool! Really liking this tool a lot!

I noticed that the zoom persists between tabs, so I have chrome zoomed out to fit the pictures and firefox for charts lol

**Comment by shubhamjain0594** [comment]
@lvdmaaten is anyone working on this or is it up for grabs?

**Comment by lvdmaaten** [comment]
It's up for grabs!

**Comment by lvdmaaten** [comment]
Solved by https://github.com/facebookresearch/visdom/commit/ff379c05c00ca3f91e3787880b731bd07aa6c620
