### ISSUE TITLE
ERROR:visdom:failed CONNECT via proxy status: 403

### ISSUE THREAD

**Issue by chandrakant-sonawane** [facebookresearch/visdom#553]
When I run the code:

import visdom
import numpy as np
vis = visdom.Visdom(server='http://10.8.0.1/', port=8080)
#visdom.Visdom(use_incoming_socket=False)
#vis = visdom.Visdom()
vis.text('Hello, world!')
vis.image(np.ones((3, 10, 10)))
#################################################################

Ouput on terminal:

WARNING:root:Setting up a new session...
ERROR:visdom:failed CONNECT via proxy status: 403
ERROR:visdom:failed CONNECT via proxy status: 403
ERROR:visdom:failed CONNECT via proxy status: 403
WARNING:visdom:Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.
#########################################################
How to fix this proxy problem and what are the commands for using visdom since I am using firefox of the same server as a screen for visualization?

**Comment by JackUrb** [comment]
You'll need to configure visdom to use your system's proxy settings using the `proxies` argument as described in the README

**Comment by JafferWilson** [comment]
I guess if you try changing the server ip as 0.0.0.0, then it might be able to take the proxies.

**Comment by JafferWilson** [comment]
Try this:  
Run the steps:  
1) `python -m visdom.server --hostname 0.0.0.0`
2) Try to run the example from the demo: https://github.com/facebookresearch/visdom/blob/master/example/demo.py
Before running change the line number: 24 from the code which says: `DEFAULT_HOSTNAME = "http://localhost"` to `DEFAULT_HOSTNAME = "10.8.0.1"`
3) Save it and run `python demo.py`
Thats it.

**Comment by JafferWilson** [comment]
Share snapshot of this command please:
`python -m visdom.server --hostname 0.0.0.0`
Is it running? Because it is working fine on my side. Tell me where your server is? Are you in the same network?

**Comment by chandrakant-sonawane** [comment]
> Share snapshot of this command please:
> `python -m visdom.server --hostname 0.0.0.0`
> Is it running? Because it is working fine on my side. Tell me where your server is? Are you in the same network?

![1](https://user-images.githubusercontent.com/44409458/51379069-94310280-1b34-11e9-8644-0201504d12a0.png)
![2](https://user-images.githubusercontent.com/44409458/51379070-94c99900-1b34-11e9-94c4-3e0f7a567490.png)
![3](https://user-images.githubusercontent.com/44409458/51379071-94c99900-1b34-11e9-83ce-d6b3b39dbd05.png)
![4](https://user-images.githubusercontent.com/44409458/51379072-94c99900-1b34-11e9-9152-0a63e117ae02.png)
![5](https://user-images.githubusercontent.com/44409458/51379073-94c99900-1b34-11e9-83ab-08e6e65c3eb6.png)
#######################################
Yes, I am in the same server of GPU. 
I access this GPU through `ssh -X chandu@10.8.10.13`, then it asks for password so that I get the access of GPU.
After that I use the firefox from same GPU server in which I have to set the proxy as shown in 1st snapshot so that I can access the internet.
so this is how I utilize this GPU.
Now I have installed `pip install visdom` then `luarocks install visdom` then `python -m visdom.server` then I git clone `https://github.com/facebookresearch/visdom.git` then ran the code `/visdom/example/
demo.py` 
I have attached all screenshots of terminal output and firefox proxy setting.
Now please suggest how can I fix this problem.

**Comment by JafferWilson** [comment]
Ah.. You missed that.. You have to run the browser with the ip and port and not 0.0.0.0: port. That's it. It will show up.

**Comment by JafferWilson** [comment]
Is your issue resolved...? Please close this issue if it is.

**Comment by JackUrb** [comment]
Hi @chandrakant-sonawane - in your most recent message it appears you're able to connect to the server correctly (as you can POST from the python client and view the webpage) so I find it strange that none of the windows are appearing. Do you see any errors in your JavaScript logs? You shouldn't have needed to set proxy settings in Firefox for this to work, and it's possible that is making the socket behave strangely. Let me know what your current status is.

**Comment by OlofHarrysson** [comment]
I sit behind a proxy due to company reasons. Since I'm running everything on my own computer I don't know how this would work with ssh but I managed to get around the problem by running my script that was connecting to the Visdom server via the no proxy command eg. -> no_proxy=localhost python train.py

The visdom server was started like normal

**Comment by wjbKimberly** [comment]
> I sit behind a proxy due to company reasons. Since I'm running everything on my own computer I don't know how this would work with ssh but I managed to get around the connection problem by running my script that was connecting to the Visdom server via the no proxy command eg. ->` no_proxy=localhost python train.py`
> 
> The visdom server was started like normal

Thanks so much for your suggestions! I solve my problem. I meet the same problem when I run scripts on remote server.

**Comment by HarmanDotpy** [comment]
> I sit behind a proxy due to company reasons. Since I'm running everything on my own computer I don't know how this would work with ssh but I managed to get around the connection problem by running my script that was connecting to the Visdom server via the no proxy command eg. ->` no_proxy=localhost python train.py`
> 
> The visdom server was started like normal

great comment!

**Comment by tuyunbin** [comment]
> I sit behind a proxy due to company reasons. Since I'm running everything on my own computer I don't know how this would work with ssh but I managed to get around the connection problem by running my script that was connecting to the Visdom server via the no proxy command eg. ->` no_proxy=localhost python train.py`
> 
> The visdom server was started like normal

Thanks, great solution.
