### ISSUE TITLE
Use scoped logger

### ISSUE THREAD

**Issue by 0phoff** [facebookresearch/visdom#555]
**Bug Description**  
Some packages I use have custom log-handlers (pretty printing log messages).
However, because Visdom uses the Root logger, it enables a default handler for that logger and thus all messages from those packages get printed twice.

This behaviour was not happening before today, but I havent been using visdom in a couple weeks, so not sure when it changed.

**Reproduction Steps**  
1. Use a package/file that has a custom logging handler.
2. import visdom and create a Visdom object (aka generate a log message from visdom)
3. log something with the logger of that package/file and see it printed twice.

**Expected behavior**  
Use a dedicated 'visdom' logger in your codebase.  
I'm pretty sure that is the problem, as I could see a handler in the root logger was being created after running visdom code, but I might be mistaken.  
Anyway, this is how the logging mechanism was intended to be used imo...
Using the root logger is never a good idea as it influences every single logger from all packages used!  
A stupid example is if you set the logging level on the root logger, every logger will be affected (unless you reset them specifically afterwards, which is what I think you are currently doing with Tornado :clown_face:)

**Example fix code** (in case you never worked with custom loggers)  

setting up the logger (in init or dedicated file)
```python
import logging

log = logging.getLogger('visdom')
log.setLevel(...)
log.addHandler(...)   # Only if you want custom handler, otherwise default is used
```

using logger in any file
```python
log = logging.getLogger(__name__)
# This will create a logger based on filename (eg. 'visdom.server') 
# and thus all loggers in your package will automatically inherit from the 'visdom' logger 
# and have the same behaviour and settings

# alternative
log = logging.getLogger('visdom')
# Now all your logging messages get formatted as comming from visdom
# The solution above however allows to see which file generated the (error) msg -> easier debugging
```

You can probably read the documentation on the logging module if my explanation is unclear :innocent:

---

To anyone having the same problem (which I doubt, as there are not many packages creating custom logging handlers), a temporary quickfix.  
After running something from visdom that uses the root logger (eg. visdom.Visdom()), run the following snippet:
```python
import logging
logging.handlers = []  # <- deleting the root logger handlers 
# if you have eg. a filehandler to write all log messages to a file,
# you would not want to delete that one of course!
```

**Comment by JackUrb** [comment]
Hi @0phoff - custom logging would be a great thing to have for sure! It's not currently on our short term roadmap as we push through some other problems, but we'd be happy to have the change if someone gets to it before us.

**Comment by 0phoff** [comment]
Im quite busy atm, but if it starts annoying me enough I might write a small patch!
(No promises though... :innocent:)

**Comment by ArcherC521** [comment]
https://github.com/facebookresearch/visdom/blob/master/py/visdom/__init__.py#L432-L448
```python
    @property
    def session(self):
        if self._session:
            return self._session
        #logging.warning("Setting up a new session...")
        logger.warning("Setting up a new session...")
        sess = requests.Session()
        if self.proxies:
            sess.proxies.update(self.proxies)
        if self.username:
            resp = sess.post("%s:%s" % (self.server, self.port), json=dict(
                username=self.username,
                password=self.password))
            if resp.status_code != requests.codes.ok:
                raise RuntimeError("Authentication failed")
            #logging.info('Authentication succeeded')
            logger.info('Authentication succeeded')
        self._session = sess
        return sess
```
Using `logger` instead of `logging` solves it.

**Comment by 0phoff** [comment]
> Using `logger` instead of `logging` solves it.

Ha, I didn't even see they already created a logger object...  
That would indeed fix it!
