### ISSUE TITLE
How to collect window from different envs and redraw the windows on the same new env

### ISSUE THREAD

**Issue by laoreja** [facebookresearch/visdom#562]
This feature would be useful for monitoring multiple training programs: each training has its own env with losses and visualizations and etc., while all the training can be monitored through the same env.

I tried to use `vis.get_window_data` to collect data from different windows and problems occurs during redrawing them. The data format collected seems to be not consistent with the format needed by `vis._send`.

I could write the data obtained from `vis.get_window_data` to a new environment json file located on `~/.visdom/xxx.json`, then start a new Visdom session. It seems a bit complicated. Is there more elegant way to do so?

And I could not find a way to refresh the current session to make it load the modified jason file.

**Comment by JackUrb** [comment]
Hi @laoreja - right now we don't have any elegant out-of-the-box way to support this, as the task of collating data across multiple environments is rather complicated (as we've experienced in the Compare Environments feature). One way to handle this is having your separate experiments log certain important data to two envs at the same time, allowing you to customize an "overview" environment that you can even plot multiple experiments on the same plot in.

**Comment by laoreja** [comment]
It works! Thank you so much!
