### ISSUE TITLE
Visdom crashes when given window title is None

### ISSUE THREAD

**Issue by ohwi** [facebookresearch/visdom#563]
**Bug Description**

OS: Ubuntu 16.04
Browser: Chrome / Safari
Visdom version: 0.1.8.8

If the "title" opts passed to a visdom audio is None, the client crashes without an error message and displays only the background.

**Reproduction Steps**

```{.python}
v = Visdom()

def visdom_audio(audio, env="test", disc=None):
	v.audio(
		audio,
		env=env,
		opts=dict(
			sample_frequency=args.sample_rate,
			title=disc,
		)
	)

visdom_audio(path)
```

**Client logs:**

> main.js?v=4316a77ded15b92b6e884b60b72f6513:11 Warning: Each child in an array or iterator should have a unique "key" prop.
> 
> Check the top-level render call using <ul>. See https://fb.me/react-warning-keys for more information.
>     in li
> a @ main.js?v=4316a77ded15b92b6e884b60b72f6513:11
> :8097/extensions/MathMenu.js?V=2.7.1:2 Uncaught SyntaxError: Unexpected number
> :8097/extensions/MathZoom.js?V=2.7.1:2 Uncaught SyntaxError: Unexpected number
> react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:162 TypeError: Cannot read property 'match' of null
>     at main.js?v=4316a77ded15b92b6e884b60b72f6513:35
>     at Array.map (<anonymous>)
>     at t.value (main.js?v=4316a77ded15b92b6e884b60b72f6513:35)
>     at h (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:130)
>     at beginWork (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:134)
>     at d (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:158)
>     at f (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:159)
>     at g (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:159)
>     at t (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:167)
>     at x (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:166)
> h @ react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:162
> react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:166 Uncaught TypeError: Cannot read property 'match' of null
>     at main.js?v=4316a77ded15b92b6e884b60b72f6513:35
>     at Array.map (<anonymous>)
>     at t.value (main.js?v=4316a77ded15b92b6e884b60b72f6513:35)
>     at h (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:130)
>     at beginWork (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:134)
>     at d (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:158)
>     at f (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:159)
>     at g (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:159)
>     at t (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:167)
>     at x (react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3:166)

**Server logs:**

> INFO:tornado.access:200 POST /update (127.0.0.1) 0.74ms
> INFO:tornado.access:200 POST /events (127.0.0.1) 4.56ms
> INFO:tornado.access:200 POST /events (127.0.0.1) 6.50ms
> INFO:tornado.access:200 POST /events (127.0.0.1) 5.13ms
> INFO:tornado.access:200 POST /events (127.0.0.1) 4.96ms
> INFO:tornado.access:200 POST /events (127.0.0.1) 55.28ms
> INFO:tornado.access:200 POST /events (127.0.0.1) 1.08ms
> INFO:tornado.access:200 POST /events (127.0.0.1) 0.55ms
> INFO:tornado.access:200 POST /events (127.0.0.1) 41.08ms
> INFO:tornado.access:200 POST /events (127.0.0.1) 0.55ms

I think this can be solved by changing None to empty string

**Comment by JackUrb** [comment]
Generally the correct behavior would be to ensure that the title is only set and propagated forward when it is not `None`. It would make sense to handle this in `_assert_opts` in dropping the title field out of the `opts` dict with a warning when this occurs. I wouldn't want to silently ignore as I feel like generally we should not be expecting `None` arguments in the `opts` dict as they are more likely to represent a bug in understanding or implementation than an intentional attempt to set something as `None`.

**Comment by pringshia** [comment]
Aside from what ever behavior we choose here, it would be nice to have a React ErrorBoundary on a pane level capture these exceptions and display them in a user-friendly way, instead of just silently failing and spitting out to console.

**Comment by JackUrb** [comment]
@pringshia that would save a whole lot of headache when it comes to the fact that right now anything can cause a blue screen bug.
