### ISSUE TITLE
where is my saved json file?

### ISSUE THREAD

**Issue by ming71** [facebookresearch/visdom#567]
I have click save button to save env to a json file , but  I can not find where it is  on my computer....
The only json file I can find is env main.

**Comment by ming71** [comment]
![image](https://user-images.githubusercontent.com/43720092/53250292-1775e300-36f5-11e9-8dcf-0ca4170e1556.png)

and it does response to my click ,but where to save????

**Comment by JackUrb** [comment]
Hi @ming71, currently it saves envs at `<env_name>.json` in your `~/.visdom` folder.

**Comment by ming71** [comment]
> Hi @ming71, currently it saves envs at `<env_name>.json` in your `~/.visdom` folder.

Thanks for your reply~
