### ISSUE TITLE
visdom always display blue screen

### ISSUE THREAD

**Issue by felixx** [facebookresearch/visdom#573]
python -m visdom.server
/home/felix/work/python_exec/visdom/server.py:30: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
  ioloop.install()  # Needs to happen before any tornado imports!
Checking for scripts.
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:8097
INFO:tornado.access:101 GET /vis_socket (::1) 0.84ms
INFO:root:Opened visdom socket from ip: ::1
INFO:tornado.access:101 GET /vis_socket (::1) 0.68ms
INFO:root:Opened visdom socket from ip: ::1
INFO:tornado.access:200 GET /env/main (::1) 16.30ms
WARNING:tornado.access:404 GET /static/fonts/layout-bin-packer.js.map (::1) 0.73ms
INFO:tornado.access:101 GET /socket (::1) 0.66ms
INFO:root:Opened new socket from ip: ::1
WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map (::1) 1.02ms
INFO:tornado.access:200 POST /env/main (::1) 1.11ms
INFO:tornado.access:200 POST /env/main (::1) 1.66ms
INFO:tornado.access:200 GET /env/favicon.png (::1) 3.38ms
INFO:tornado.access:304 GET /extensions/MathMenu.js?V=2.7.1 (::1) 5.73ms
INFO:tornado.access:304 GET /extensions/MathZoom.js?V=2.7.1 (::1) 5.77ms

I captured the screen:
![2019-03-05 11-38-39](https://user-images.githubusercontent.com/961257/53779731-3b7ac500-3f3c-11e9-981c-d2f4124ac54e.png)

I installed visdom using pip and I checked whether the scripts are downloaded:
(py3) felix@FelixLinux:~/anaconda3/envs/py3/lib/python3.7/site-packages$ ls visdom/static/fonts
classnames                        glyphicons-halflings-regular.svg#glyphicons_halflingsregular  glyphicons-halflings-regular.woff   layout_bin_packer
glyphicons-halflings-regular.eot  glyphicons-halflings-regular.ttf                              glyphicons-halflings-regular.woff2
(py3) felix@FelixLinux:~/anaconda3/envs/py3/lib/python3.7/site-packages$ ls visdom/static/css
bootstrap.min.css  login.css  react-grid-layout-styles.css  react-resizable-styles.css  style.css
(py3) felix@FelixLinux:~/anaconda3/envs/py3/lib/python3.7/site-packages$ ls visdom/static/js
bootstrap.min.js  jquery.min.js  main.js  mathjax-MathJax.js  plotly-plotly.min.js  react-dom.min.js  react-modal.min.js  react-react.min.js  sjcl.js
(py3) felix@FelixLinux:~/anaconda3/envs/py3/lib/python3.7/site-packages$ 

then I write some code to test, it cannot show the message, please help
from visdom import Visdom
viz = Visdom()
viz.text("Hello Pytorch")

OS: ubuntu 1804
brower: chromium & firefox
visdom version: 0.1.8.8
ps: my mac book has no issue with it

**Comment by JackUrb** [comment]
Hi @felixx - The errors that appear in your console are warnings that we are aware of that aren't actually preventing the visdom pane from loading. On the other hand, the content on the left (visdom loading in a strange green background, no top nav bar) seems to suggest that you are missing some scripts (though you suspect otherwise). Can you try running the `./download.sh` script and seeing if anything fails to load?

**Comment by felixx** [comment]
@JackUrb 
thanks for quick reply, I've found the root cause which is the local proxy prevents the connections, when I disable the proxy, it works now.
