### ISSUE TITLE
line() got an unexpected keyword argument 'name' in 0.1.8.8

### ISSUE THREAD

**Issue by odie2630463** [facebookresearch/visdom#578]
Hi , I install visdom from source , version is 0.1.8.8 , Python 3.7
But , I run demp.py

```
viz.line(
        X=np.arange(21, 30),
        Y=np.arange(1, 10),
        win=win,
        name='2',
        update='append'
    )
```

got TypeError: line() got an unexpected keyword argument 'name'

**Comment by odie2630463** [comment]
Sorry it a stupid question , can close, I think maybe my environment has some problem , I reinstall it and fixed.

**Comment by JackUrb** [comment]
No worries - feel free to open a new issue if you run into any other problems!
