### ISSUE TITLE
Matplot resizable flag

### ISSUE THREAD

**Issue by paland3** [facebookresearch/visdom#579]
**Bug Description**
When sending matplot to visdom, the resizable flag is not parsed.

`self.losswin = self.vis.matplot(mplot, opts=dict(resizable=True),  win=self.losswin)`

gives me:
```
Exception has occurred: AttributeError
'str' object has no attribute 'group' 
```

**Reproduction Steps**
Create a matplot figure called mplot, and send it to visdom.
vis.matplot(mplot, opts=dict(resizable=True))

**Expected behavior**
I expect to get the same figure but resized when the window is resized.

Sorry if I missed something trivial. I would like to have matplots in visdom, possible as interactive as the originals. Is that possible?

**Comment by JackUrb** [comment]
Hi @paland3 - matplots are rendered using a base svg backend, and don't have any interactive features besides resizability. Interactive plots are only supported using the plotly-backed functions. That being said, `resizable` should be working so I can try to debug that specifically. Is the exception you listed the only content that is printed?

**Comment by paland3** [comment]
Hi, thanks for looking into this. Yes this is the only related log I got. Because matplot renders are not interactive, I now convert them to plotly and send that to get interactive figures as a workaround (And as you saw in my other ticket :) ).
