### ISSUE TITLE
Plotly figure kills server if has title

### ISSUE THREAD

**Issue by paland3** [facebookresearch/visdom#581]
**Bug Description**
I create a plot in matplotlib, convert it to plotly, and send it to visdom. (I convert it because just sending matplot won't let me zoom and interact(

**Reproduction Steps**
The following code runs, but if you take out the comment it fails.
```
mplot = plt.figure()
ax = mplot.add_subplot(111)
#ax.set_title("train loss function")
line = ax.plot(self.train_step, self.train_loss)
plt.setp(line, 'color', 'r', 'linewidth', 2.0)
plotly_fig=tls.mpl_to_plotly(mplot, resize=True)
vis.plotlyplot(plotly_fig)
```

**Expected behaviour**
I expect to see a plot with a title. Instead, the website behave strangely, the environment selector is gone, basically it is empty blue.

**Comment by JackUrb** [comment]
Hi @paland3 - are you running from source? This sounds related to #561, which hasn't been pushed to PyPI yet.

**Comment by paland3** [comment]
> Hi @paland3 - are you running from source? This sounds related to #561, which hasn't been pushed to PyPI yet.

That seems like the same issue, yes, thanks. (#565) I did not look in closed issues. And no, I did not run it from source. Sould I change to that or just wait a couple of days?

**Comment by defaultUser3214** [comment]
This bug still appears in version 0.1.8.8 of visdom and plotly 3.10.0 if you use it via Pycharm on Os X. Could you please fix it in the stable release?
