### ISSUE TITLE
Error when running demo.py

### ISSUE THREAD

**Issue by drorata** [facebookresearch/visdom#59]
When I run `demo.py` I get the following error:

```python
Traceback (most recent call last):
  File "visdom/example/demo.py", line 232, in <module>
    viz.mesh(X=X, Y=Y, opts=dict(opacity=0.5))
AttributeError: 'Visdom' object has no attribute 'mesh'
```

What's the problem?

**Comment by lvdmaaten** [comment]
Are you using the latest version of visdom? The pip install may be lagging
behind (the mesh function was recently added).

**Comment by drorata** [comment]
Indeed, installing from the source solved the problem. Thanks.

I documented my test [here](http://drorata.github.io/posts/2017/Apr/04/running-visdom-examples-within-a-docker-container/)

**Comment by meetshah1995** [comment]
@lvdmaaten  - Any plans to update visdom on pypi for the same?

**Comment by ajabri** [comment]
@meetshah1995 sorry for the delay, I'll take care of this today.
