### ISSUE TITLE
How to export the plot into text ?

### ISSUE THREAD

**Issue by AndrewXWei** [facebookresearch/visdom#591]
Could I export the original data of the plot into text by visiting the database or some other easy ways?

**Comment by JackUrb** [comment]
Hi @weixiao917 - at the moment you can access the underlying plot representation by looking at the `<env_name>.json` file present in your `~/.visdom` directory.

**Comment by weixiao917** [comment]
> Hi @weixiao917 - at the moment you can access the underlying plot representation by looking at the `<env_name>.json` file present in your `~/.visdom` directory.

Hi @JackUrb , but at the moment of showing, there's only an empty json file(main.json) in my `~/.visdom` directory , which is '{"reload": {}, "jsons": {}}'. 
could you show more details? thanks !

**Comment by JackUrb** [comment]
Is this from the location you're running the visdom server or the python client? If you're still not seeing it, try to use the save button from the frontend to force a dump to this file.

**Comment by wyessen** [comment]
> Is this from the location you're running the visdom server or the python client? If you're still not seeing it, try to use the save button from the frontend to force a dump to this file.

And what if we have no access to the frontend? Say it is running in a docker container somewhere in the cloud? Is there an API to force the dump?

**Comment by wyessen** [comment]
I see that in the web UI, there is the save button on each window (the down arrow icon). When I push that, the image is downloaded. Is there a way to invoke this process via API? Again, I have Visdom running somewhere where I have no access to the UI.

**Comment by jramapuram** [comment]
@wyessen : check https://github.com/jramapuram/visdom_to_csv for some example code regarding the API. I have scripts to grab data to CSV and to images.

**Comment by JackUrb** [comment]
The repo @jramapuram provides shows some demo code on how you can use existing visdom functions to pull data saved to a visdom instance without having any access to the frontend.
