### ISSUE TITLE
Stem plot doesn't show (on python)

### ISSUE THREAD

**Issue by mehdi-shiba** [facebookresearch/visdom#6]
Hi all and thanks for the great work on this library.
I am still getting familiarized with the API using the Python demo code, but I am having problem getting the stem plot to work.
I am using the exact code from `demo.py`:
```
# stemplot
Y = np.linspace(0, 2 * math.pi, 70)
X = np.column_stack((np.sin(Y), np.cos(Y)))
viz.stem(
    X=X,
    Y=Y,
    opts=dict(legend=['Sine', 'Cosine'])
)
```
But nothing shows up on the client. There is no output error either (running on iPython the result from running that black is `u'pane_34ecea25d1...` so it seems to be correctly creating a pane, but it's just not showing.
(I am running Python 2.7.12 btw)

**Comment by j-min** [comment]
same here with python 3.6

**Comment by lvdmaaten** [comment]
The equivalent code in Lua works correctly:
```
viz = require 'visdom'()
Y = torch.range(0, 2 * math.pi, 2 * math.pi / 70)
X = torch.cat(torch.sin(Y), torch.cos(Y), 2)
viz:stem{X = X, Y = Y, options = {legend = {'Sine', 'Cosine'}}}
```
I'm looking into the Python wrapper to see what is happening.

**Comment by lvdmaaten** [comment]
The underlying issue is that the data generated by the stem plot creates NaNs, which aren't turned into `null` by the JSON decoder. I will send out a fix soon.

**Comment by lvdmaaten** [comment]
Solved by https://github.com/facebookresearch/visdom/commit/930f7802e5214535da1cf46b01b961313813e1c4.
