### ISSUE TITLE
CV2 Version 3 support

### ISSUE THREAD

**Issue by bfortuner** [facebookresearch/visdom#60]
I got this error running demo.py. Perhaps explain somewhere that its not compatible with the latest version of cv2?
http://stackoverflow.com/questions/15584608/python-opencv2-cv2-cv-fourcc-not-working-with-videowriter

bfortuner@bfortuner-MS-7A71:~/workplace/ml-study$ python visdom_demo.py
Traceback (most recent call last):
  File "visdom_demo.py", line 16, in <module>
    viz.video(tensor=video)
  File "/home/bfortuner/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 346, in video
    fourcc = cv2.cv.CV_FOURCC(
**AttributeError: module 'cv2.cv2' has no attribute 'cv'**

>>> import cv2
>>> cv2.__version__
'3.2.0'

**Comment by bfortuner** [comment]
Saw an existing issue that was closed with no reply. 
https://github.com/facebookresearch/visdom/issues/45

**Comment by scientist1642** [comment]
and you close it as well? :)
