### ISSUE TITLE
add lines on the same window after restart the server

### ISSUE THREAD

**Issue by nuomizai** [facebookresearch/visdom#601]
It bothers me that every time I restart the visdom server，the window will clear up the history lines and then plot a new line(when I use visdom.line(...)). But I want to compare these results when the hyper-parameters changed. So, does anyone know how to add a new line on an exist window after restart the visdom server? Thank u very much!

**Comment by nuomizai** [comment]
Well, it seems I find the reason. My code is as follows:
self.vis.line(X=np.array([episode]), Y=np.array([self.completion_ratio]), win='completion_ratio',
                      update='append' if episode > 0 else None, opts=dict(title='completion_ratio'))
The problem is 'None' ! If I change the code to :
self.vis.line(X=np.array([episode]), Y=np.array([self.completion_ratio]), win='completion_ratio',
                      update='append' , opts=dict(title='completion_ratio'))
then I can plot a new line on the old window!

**Comment by JackUrb** [comment]
Hi @nuomizai - indeed if you don't set the `update` flag, `visdom` will wipe the contents of a window when you re-plot to it. I'm glad you fixed the issue. Thanks for reaching out!
