### ISSUE TITLE
Got error when running visdom on server

### ISSUE THREAD

**Issue by ky66111** [facebookresearch/visdom#608]
Hi, I have run the listening process via shell and type code below in python
`import visdom
vis = visdom.Visdom()`
then I got
`ERROR:visdom:scheme http is invalid`
The server is running on Ubuntu 16.04 but I'm not familiar with how it configures. Does it mean that my server disable http protocol?

Thank you!

**Comment by JackUrb** [comment]
Hi @ky66111 - I haven't run into this issue before. It very well could be related to your server's configuration, but I really don't have enough context to know one way or another.
