### ISSUE TITLE
matplotlib backend's imshow not respecting interpolation='none'

### ISSUE THREAD

**Issue by SsnL** [facebookresearch/visdom#612]
I draw the following grid with nearest neighbor interpolation:
![Screenshot 2019-04-26 12 41 59](https://user-images.githubusercontent.com/5674597/56823013-c2536c00-6820-11e9-9a2a-de6e1ec6b63a.png)

But got the following bilinearly interpolated result in visdom.
![Screenshot 2019-04-26 12 42 03](https://user-images.githubusercontent.com/5674597/56823072-e2832b00-6820-11e9-98c2-1bfb12bac982.png)

**Comment by SsnL** [comment]
Oh okay. Looks like an svg issue. https://stackoverflow.com/questions/38535459/matplotlib-stores-svg-different-than-what-is-show-on-screen

**Comment by JackUrb** [comment]
Looks like you should be able to use `interpolation=nearest` to get the desired effect, but that's just coming from the link you posted. Leaving it here in case anyone runs into this.

**Comment by SsnL** [comment]
Yes, `interpolation=nearest` solved it for me :)
