### ISSUE TITLE
Pane not resized according to the image of varying size. Any quick solution?

### ISSUE THREAD

**Issue by nrupatunga** [facebookresearch/visdom#615]
**Pane not resized according to the image of varying size**
When I try to visualize images of different size as below 

**Reproduction Steps**
```
for img_file in image_files:
    img = cv2.imread(img_file)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    # img = image_resize(img, width=200)
    img = np.transpose(img, axes=(2, 0, 1))
    env_name = img_file.strip().split('/')[-2]
    win_name = img_file.strip().split('/')[-1]
    viz.image(img, win=win_name, env=env_name, opts=dict(caption='image', store_history=True, title=win_name))
```

**Screenshots** (on the right bottom half of the screen this issue is seen)
![issue_visdom](https://user-images.githubusercontent.com/980580/56864499-c7f7b000-69e0-11e9-8364-8bb2b68dcfdc.png)

**Comment by JackUrb** [comment]
Hi @nrupatunga - does this issue still occur without `store_history`? There are size issues with that pane type as it defaults to the size of the first image sent to the pane.

**Comment by nrupatunga** [comment]
Sorry for the late reply, 

The same code started working fine after I rebooted my PC. Possible causes for the issue might be 
I tried to resize certain pane during the visualisation while the program was still running, and probably I messed up something. I'm not very sure.
