### ISSUE TITLE
Some figures disappear when restarting the server

### ISSUE THREAD

**Issue by erakra** [facebookresearch/visdom#619]
I have a job generating figures in a certain env of my visdom server. When i restart the server and refresh the browser visdom page, some figures just disappear.

Everything looks fine before and after restarting the server in the logs. Any clue for why this is happening ? Someone already had similar issue ?

**Comment by erakra** [comment]
I have checked the .json files, it seems like the env where i have this issue i can't find data related to the disappearing figures (even before restarting the server).

**Comment by JackUrb** [comment]
Hi @erakra - the server doesn't save environments by default, you'll have to use the save button as described in the docs. As for the mathmenu/mathzoom issue, this is a known problem that just hasn't been solved yet, but it has no impact on the functionality of visdom.

**Comment by erakra** [comment]
Thanks @JackUrb ! My environment was being saved actually. The error might have been coming from several jobs interacting with several environments. I fixed it by resetting these and well aligning them to different environments.
