### ISSUE TITLE
Is there any limit on number of images that can be logged on Visdom server?

### ISSUE THREAD

**Issue by nrupatunga** [facebookresearch/visdom#621]
**_Task_**: 

Given a machine learning dataset (consider dog vs cat dataset on Kaggle), I want to visualise all the images with two environments say one named '**_dog_**' and another named '**_cat_**'

There are in total **25k** images. 

**_Problem_**

- As I started logging these images, at a certain point of time as we log more number of images, the browser hangs (on certain system 32GB RAM) and system hangs (system with 24GB RAM)

**_Question_**

- Is there any limit on the number of images that can be visualized?
- Is this problem due to the amount of RAM available on my system? 
- Any solution for this? 

Thank you for your time, hoping for your reply soon

**Comment by JackUrb** [comment]
Hi @nrupatunga - this is a tricky one. At 25K images I'm not sure whether you're more likely to be running into ram issues, google chrome optimization issues when it comes to caching large numbers of images, or react issues relating to having too many managed image components. The image viewing components aren't really built for something like this. Before I try to offer a solution, I have to ask: why is it you want to visualize all of the images at the same time?

**Comment by nrupatunga** [comment]
@JackUrb 

> why is it you want to visualize all of the images at the same time?

That's a good question.

My intention here is: 
whenever **_I get new data_** (say in this case, images) to train any machine learning model, I want to **_spend some time looking at the images and get the idea of the composition of the data_**. In order to do this, browsing through folders on my PC felt like a painful process, so **_I thought I would use Visdom for this purpose_**. Do you have any _**alternative**_ to do this in an easier way?

**Comment by JackUrb** [comment]
Ah yes potentially you can create a workflow that will let you tab through the panels of the photos without needing to scroll or render them all at once:

First render enough image panes to fill up your viewable space, saving their window ids to an array. Then you can attach a text callback to the first (or any) image pane (such as is done on the text pane in the visdom demo). When this callback is triggered, you can fetch new images to plot to the the existing set of image panes. Thusly, by pressing any text key after having clicked (and this selected) the pane you register the callback on, you can 'scroll' through the data. You can even pre-populate the list of locations to load the images from and order them however you like depending on what your requirements are towards understanding the complete composition. (As a caveat this will require plotting all image panes to the maximum height and maximum width of the images in your dataset if they have varying sizes).

**Comment by nrupatunga** [comment]
@JackUrb That sounds like a fair idea. Thank you.
