### ISSUE TITLE
legend does not display

### ISSUE THREAD

**Issue by czqaihshyeah** [facebookresearch/visdom#622]
**my code:**
`viz.line(Y=np.column_stack((np.array([p1_avg_rl_loss]),np.array([p2_avg_rl_loss]))),X=np.column_stack((np.array([frame_idx]), np.array([frame_idx]))),win=rl_loss_win, update='append',opts=dict(legend=['p1_rl_loss', 'p2_rl_loss']))`
`viz.line(Y=np.column_stack((np.array([p1_avg_sl_loss]), np.array([p2_avg_sl_loss]))),
                         X=np.column_stack((np.array([frame_idx]), np.array([frame_idx]))),
                         win=sl_loss_win, update='append',
                         opts=dict(legend=['p1_sl_loss', 'p2_sl_loss']))`
`viz.line(Y=np.column_stack((np.array(p1_avg_reward), np.array(p2_avg_reward))),
                         X=np.column_stack((np.array([frame_idx]), np.array([frame_idx]))),
                         win=reward_win, update='append',
                         opts=dict(legend=['p1_reward', 'p2_reward']))`
`viz.line(Y=np.array([(frame_idx - prev_frame)/(i_episode - prev_episode)]),
                         X=np.array([frame_idx]),
                         win=livetime_win, update='append',
                         opts=dict(legend=['avg_livetime']))`
**and it shows:**
![visdom_eg](https://user-images.githubusercontent.com/20008405/57345169-68d23200-717c-11e9-8438-0ce577eb67fb.png)
**why legends disappear? And the version is: 0.1.8.8.**

**Comment by JackUrb** [comment]
Hi @czqaihshyeah, sorry but I'm unable to reproduce this behavior using the below script:
```
import visdom
import numpy as np
myline = vis.line(np.array([[1,2],[6,7]]), opts={'legend': ['first', 'second']})
vis.line(np.array([[9,9]]), np.array([[2,2]]), win=myline, opts={'legend': ['first', 'second']}, update='append')
```
You can try manually setting `showlegend=True` in opts, but I don't have confidence that will resolve your issue. Does anything appear in your server logs or javascript console logs (other than the MathMenu and similar errors).

**Comment by czqaihshyeah** [comment]
@JackUrb Thanks,the problem has been resolved.
