### ISSUE TITLE
cannot remove grid and line in scatter

### ISSUE THREAD

**Issue by Colin97** [facebookresearch/visdom#627]
I do not want to show the grid and the line, but the code below doesn't work.

`vis.scatter(X = data, opts = dict(layoutopts = {'plotly': {'xaxis': {'showgrid':False, 'showline':False, 'showticklabels':False}}}))`

**Comment by JackUrb** [comment]
Hi @Colin97, what version of visdom are you running? I cannot produce your problem with exactly the below code:
```
import visdom
vis = visdom.Visdom()
vis.scatter(X = [[1,1],[2,2],[3,3]], opts = dict(layoutopts = {'plotly': {'xaxis': {'showgrid':False, 'showline':False, 'showticklabels':False}}}))
```
Output plot:
![Screen Shot 2019-06-03 at 11 27 49 AM](https://user-images.githubusercontent.com/1276867/58813928-c7ab8f80-85f2-11e9-92d4-63f66e325e2e.png)

**Comment by Colin97** [comment]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/16759292/58928135-e1301100-8783-11e9-90ef-2a365e53c53f.png">
Yes, it works for 2D points, but not for 3D points.
My visdom is 0.1.8.8.

**Comment by JackUrb** [comment]
HI @Colin97: [plotly](https://plot.ly/python/3d-axes/) itself doesn't have the ability to remove grids and lines from 3d plots.

**Comment by JackUrb** [comment]
Closing as this is a plotly issue and not a visdom issue.
