### ISSUE TITLE
 In the browser shows that mathmenu is not loaded

### ISSUE THREAD

**Issue by Eyshika** [facebookresearch/visdom#629]
@JackUrb 
**Bug Description**
Gettting Error 
>File failed to load: /extensions/MathZoom.js

**Reproduction Steps**
1. Run `python -m visdom.server` on ec2
2. connect local machine port to local host of ec2 instance
3. Run `https://localhost:8000/tree` on local machine

It gives error 
>File failed to load: /extensions/MathZoom.js
and doesnt display anything

Getting same error if running on linux system even

**Screenshots**
![Screen Shot 2019-06-06 at 1 54 03 PM](https://user-images.githubusercontent.com/25290579/59065868-976a2800-8862-11e9-9a59-b178e036bbff.png)

**Comment by JackUrb** [comment]
Hi @Eyshika, the mathmenu issue is a known problem that doesn't actually have any impact on the running program, and thus I haven't gotten around to fixing it. If you're having logging problems, what are you trying to log and are you getting any errors in the visdom console?
