### ISSUE TITLE
[JSON file] Figure title saved in content field rather than title field

### ISSUE THREAD

**Issue by hashbangCoder** [facebookresearch/visdom#63]
Title field in saved json file is not getting populated
Sample Code : 

```python
v = visdom.Visdom()
v.line(np.random.randn(100),opt=dict(title='sample_title'), env = 'sample_env')
v.save(['sample_env'])

with open('~/.visdom/sample_env','r') as f:
    json_data = json.load(f)
assert json_data['jsons'].values()[0]['title'] ==  ''    #True
```

Edit - I found the figure title buried in the `content` field. Is this to be expected? If so, what is the `title` field for?
```python
json_data['jsons'].values()[0]['content']['layout']['title'] == 'sample_title'
```

**Comment by JackUrb** [comment]
Sorry for the incredibly late reply here. In case you or anyone is still wondering:
The title in this case is the pane title, as rendered within a window externally to the plotly title. 
https://github.com/facebookresearch/visdom/blob/c1f5904834cf45b140d757abdfc0c6450fde2b4c/js/Pane.js#L78
