### ISSUE TITLE
"Invalid Login Information" message when visdom is started with -enable_login and -base_url options at the same time

### ISSUE THREAD

**Issue by kimchitsigai** [facebookresearch/visdom#630]
**Bug Description**
When I start visdom with -enable_login and -base_url options at the same time, I get the error message "Invalid Login Information" 

**Reproduction Steps**
Enter steps to reproduce the behavior:
1. Start visdom : visdom -base_url /server4 -enable_login
2. Startup messages:
    $ visdom -base_url /server4 -enable_login
    Checking for scripts.
    Please input your username: tom
    Please input your password: 
    It's Alive!
    INFO:root:Application Started
    You can navigate to http://localhost:8097/server4
3. On the browser, after I input username/password I get "Invalid Login Information"
4. On the visdom server side, I get :
    "WARNING:tornado.access:404 POST / (127.0.0.1) 1.68ms"

**Expected behavior**
I expect to login successfully.

**Additional context**
When I start visdom with only one of the 2 options, it works:
visdom -enable_login => I login successfully, I have access to visdom web page and I can run example Python programs.
visdom -base_url /server4 => I have access to visdom web page and I can run example Python programs.
I'm running Ubuntu 18.04. I've downloaded and installed visdom yesterday.

**Comment by JackUrb** [comment]
Hi @kimchitsigai - this is a bug in the redirect for the login page as seen here: https://github.com/facebookresearch/visdom/blob/b085c76d13f6a26bb438df1c9b4975a757df2836/py/visdom/static/login.html#L52
A fix would involve replacing the redirect with one to a templates `base_url` and sending the correct `base_url` to the template here:
https://github.com/facebookresearch/visdom/blob/b085c76d13f6a26bb438df1c9b4975a757df2836/py/visdom/server.py#L1260
This would make the flow work as intended. I'll be able to get to it mid-next week, but feel free to submit a PR sooner.

In theory and as a temporary workaround, after logging in and being redirected, you should be able to navigate to the correct url by typing it into your browser.

**Comment by kimchitsigai** [comment]
Thanks a lot.
I'll be waiting for the fix.
