### ISSUE TITLE
How to get/set Cursor Position

### ISSUE THREAD

**Issue by pebauer** [facebookresearch/visdom#632]
Use this to open other questions or issues, and provide context here.
Is it possible to get or set the cursor position? 

That means, when I have two visdom windows open, each with one plot of the same data, but different views (e.g. window 1: x and y coordinates; window 2: x coordinate and time), I would like to get the x value in window 1 of the current cursor position and simultaneously display the time value in window 2 (by the same x coordinate value).

**Comment by JackUrb** [comment]
Hi @pierbauer - sorry we don't at the moment have any implementation of something that would operate like this. In theory it could be doable by utilizing the event system of both plotly and visdom, but we don't even have a specific wrapper for broadcasting plotly events to other windows. I'm interested in doing more in this space as cross-window event communication is going to be an important part of enhancing one of visdom's primary differentiating factors, but I don't have any short term solutions for this.

If you're only working on 3 axes right now I'd suggest using the 3d plots in the meantime.
