### ISSUE TITLE
vis._send to specific environment

### ISSUE THREAD

**Issue by GrumpyZhou** [facebookresearch/visdom#642]
Hi,

What should i do if i want to send customised plotly data to a specified environment.
Just like in your Generic plot example, 
````
vis._send({'data':` [trace], 'layout': layout, 'win': 'mywin'})
````
One can easily specify the target window, but not sure where to specify the environment, now everything is sent to `main` environment.
While other wrapped methods such as `vis.line`, it can also be specified in the arguments.

**Comment by JackUrb** [comment]
Hi @GrumpyZhou. Sorry for the delay here, if you want to send to a specific env use `'eid': <env>` in the dict you send
