### ISSUE TITLE
Aligning text and images

### ISSUE THREAD

**Issue by shubhamagarwal92** [facebookresearch/visdom#644]
Hi, I am trying to display text and images side by side for a particular epoch run of the model. Currently, they are not being aligned; texts collate together while images are shown else where.

```
vis = visdom.Visdom()
vis.images(img_vis.cpu().detach().numpy(), nrow=4, opts=dict(title='original'))
vis.text(raw_text, opts=dict(title='text'))
```

- Is it possible to align them in some kind of frame while visualizing. 
- Also, the text is in a list. But, while displaying, the text comes out to be comma separated and not as a list.

**Comment by shubhamagarwal92** [comment]
@JackUrb @temporaer 

Currently the text and image boxes are floating; though can be arranged by drag and drop but not programatically.

For 1, I tried to align them in same win using `append`

```
    updatetextwindow = viz.text('Hello World! More text should be here', env="debug")
    assert updatetextwindow is not None, 'Window was none'
    viz.text('And here it is', win=updatetextwindow, env="debug", append=True)
```
However I cant append images to the same text box
```
Traceback (most recent call last):
  File "test_visdom.py", line 88, in <module>
    main(args)
  File "test_visdom.py", line 59, in main
    viz.images(imgs, opts=dict(title='original'), nrow=4, win=updatetextwindow, env="debug", append=True)
  File "/home/shubhama0/anaconda3/envs/tagan/lib/python3.6/site-packages/visdom/__init__.py", line 335, in wrapped_f
    return f(*args, **kwargs)
TypeError: images() got an unexpected keyword argument 'append'
```

Is there any other way that I could display the corresponding text and images together?

**Comment by JackUrb** [comment]
Hi @shubhamagarwal92 - unfortunately at the moment there is no really good way to do what you're attempting here. We have exact positioned layout (and programmatic control of it) on the roadmap, and there could be a way to manage adding arbitrary text to image fields by extending upon the 'widget' feature introduced alongside image history, but what you're trying above with append is not supported (text, image, and plot panes are handled differently, and you can't append from one to another). The best you can do is put titles on images, or render images via html directly in your text panes.

**Comment by shubhamagarwal92** [comment]
Thanks @JackUrb for your suggestion. Could you point me to any piece of code which I could take help from for "render images via html directly in your text panes".

**Comment by JackUrb** [comment]
This sort of flow occurs in the existing `audio` implementation:
https://github.com/facebookresearch/visdom/blob/ddf7cd2cc522635f8a86b243d0f26f13980d9b89/py/visdom/__init__.py#L1278

**Comment by shubhamagarwal92** [comment]
Cool. Thanks. I will try that out. 

One last question: 

Also, the text is in a list. But, while displaying, the text comes out to be comma separated and not as a list. Any easy hack?

**Comment by JackUrb** [comment]
I'm not exactly sure what you mean by "the text is in a list".

**Comment by shubhamagarwal92** [comment]
like the list here:

```
    raw_text = [
        "This is first line \n",
        "This is second line \n",
        "This is third line \n",
        "This is fourth line \n"
    ]

    viz.text(raw_text, opts=dict(title='input text'))
```

I tried to append `\n` in every element of the list. so I guess this is not managed by python but html instead?

**Comment by JackUrb** [comment]
Ah I added context here in an edit:
The input to the text function should be a string. If you pass something that isn't a string the behavior isn't well defined. If you want you can use html formatting however you see fit. (You might want to make a helper that produces an html string for a bulleted list from your string list)

**Comment by satwikkottur** [comment]
@shubhamagarwal92 Did you figure out a way to embed images in html format for the text window?Identifying the `src` field of the `<img>` tag seems like the crucial step.

**Comment by JackUrb** [comment]
Closing as no new problems have been risen since the given solution was proposed.

**Comment by shubhamagarwal92** [comment]
@satwikkottur sorry for the late reply. Somehow I missed this. In the end I used jupyter notebooks for my work. Did you find a nice clean solution?
