### ISSUE TITLE
store_history for image() does not create a slider in the image pane

### ISSUE THREAD

**Issue by Ceveloper** [facebookresearch/visdom#645]
When I run the demo.py example, the image pane generated with

`    viz.image(
        np.random.rand(3, 512, 256),
        win='image_history',
        opts=dict(caption='Second random!', store_history=True),
    )`

has no slider. I cannot see the image with `caption='First random'`. 
It looks like this:

![image](https://user-images.githubusercontent.com/38587456/60625222-6c361280-9de7-11e9-92d3-519f293c53bd.png)

The slider is not there. I suppose the slider should look like this:
![image](https://user-images.githubusercontent.com/38587456/60625292-a30c2880-9de7-11e9-848e-7690435edb40.png)

I have visdom version 0.1.8.8 downloaded with anaconda.

**Comment by JackUrb** [comment]
Hi @Ceveloper, do you see anything in your javascript console? This seems strange, as this is how the unit renders on a fresh build from my machine:
<img width="272" alt="Screen Shot 2019-07-03 at 5 13 57 PM" src="https://user-images.githubusercontent.com/1276867/60625515-0a10e980-9db6-11e9-933d-1d5f9170fa7a.png">

**Comment by Ceveloper** [comment]
Hi @JackUrb, if with javascript console you mean my linux terminal, then nothing is there.

**Comment by JackUrb** [comment]
I'm referring to the developers tools in your browser. In chrome you can open this with right click -> inspect.

**Comment by Ceveloper** [comment]
Thanks. You mean this?
![image](https://user-images.githubusercontent.com/38587456/60626176-3e9e9880-9dea-11e9-99aa-f74a02c4e2c3.png)

**Comment by JackUrb** [comment]
Ah wait I missed a key detail from your initial post:
"I have visdom version 0.1.8.8 downloaded with anaconda."

Image histories are only available when installing from source at the moment, and are slated for inclusion in the 0.1.9 release.
