### ISSUE TITLE
how to remove an env from drop down menu?

### ISSUE THREAD

**Issue by Wakeupbuddy** [facebookresearch/visdom#65]
First thanks for the team for the great tool!

I've tried deleting the json file from ~/.visdom/,  but the env name still shows in the drop down menu. I also tried hard refresh the page cache (i am using chrome), but still no luck.  Any clues? Thanks!

**Comment by ajabri** [comment]
Hi @Wakeupbuddy ,

Did you restart the visualization server? I think that's the only way currently for the changes to take effect. I agree that this is not desirable and I'd like to eventually make it more reactive.

**Comment by Wakeupbuddy** [comment]
@ajabri  
yeah this works. Thanks for the reply:)

**Comment by zengyu714** [comment]
Hey, @ajabri 
Restart is not very convenient indeed. 
: P

**Comment by ajabri** [comment]
Hi @zengyu714,

Thanks for your message. Yea :/ I realize it's not super convenient. Feel free to submit a pull request :) It should be a pretty simple commit.

**Comment by QuantScientist** [comment]
Is it possible to programmatically delete an env?

**Comment by JackUrb** [comment]
hi @QuantScientist - there is! Just realized it's not properly represented in the docs: https://github.com/facebookresearch/visdom/blob/d5dc9fbf1703b7ef3adc0ddf6bee2e136407429d/py/visdom/__init__.py#L462

**Comment by MartSlaaf** [comment]
Hello, @JackUrb !
Please, can you tell, where can I find some documentation or example of how delete_env works?
I've expected, that after call vis.delete_env('envname') it will disappear.  But right now nothing changes after this call. I can empty environment with vis.close(env='envname'), but it still in dropdown list.

**Comment by JackUrb** [comment]
Turns out I forgot to commit registering the delete env endpoint in https://github.com/facebookresearch/visdom/commit/4cbe32f740f2b09980c834f39d4da779ba5c4cf3, and so delete_env won't actually work until the handler is registered. Would be happy to accept a PR but I'll be OTG for the next week

**Comment by JackUrb** [comment]
Hey @QuantScientist @MartSlaaf - the fix for `visdom.delete_env` is landing in #372. Once that's in you should be able to use `delete_env` if you install from source (`pip install -e .` from the source directory).
