### ISSUE TITLE
Scatter plot labels have to be greater than 0

### ISSUE THREAD

**Issue by defaultUser3214** [facebookresearch/visdom#652]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to have negative labels /z-Values in scatter plots.
**Describe the solution you'd like**
The visdom experienced an exception while running: AssertionError('labels are assumed to be between 1 and K')

**Describe alternatives you've considered**

**Additional context**

**Comment by JackUrb** [comment]
Closing this into #651 as it's ultimately the same issue, labels are indices into an array, so the values cannot be negative in the current implementation.
