### ISSUE TITLE
Surf plot and heatmap seem to ignore y values and set them to discrete values 0,1,2 instead

### ISSUE THREAD

**Issue by defaultUser3214** [facebookresearch/visdom#653]
**Bug Description**
Please enter a clear and concise description of what the bug is.
The surface plot seems to ignore the y values from a 3D-input tensor array and instead always plots values from 0 to 2.

**Reproduction Steps**

a=[1,2,3,4,5,6]
b = [10,11,12,13,14,15]
c= [22,33,44,55,66,77]

A = np.array((a,b,c), dtype=float)
viz.surf(X=A, opts=dict(colormap='Hot'))

If you execute the upper example code you might be able to see the bug.
![Bildschirmfoto 2019-08-07 um 15 43 32](https://user-images.githubusercontent.com/31352443/62627677-290d1900-b92a-11e9-8a4a-5863eda3629c.png)
![Bildschirmfoto 2019-08-07 um 15 43 32](https://user-images.githubusercontent.com/31352443/62627712-375b3500-b92a-11e9-9d32-175f4e02d052.png)

**Expected behavior**
I would expect that the vis.surf function plots a surfaceplot where the x-axis is A[0], the y-axis is A[1] and the surface values are the A[2] values.
**Screenshots**

**Comment by JackUrb** [comment]
Hi @defaultUser3214 - the plotting methodology of the surface plot isn't necessarily following what you believe it to be:
```
This function draws a surface plot. It takes as input an `NxM` tensor
`X` that specifies the value at each location in the surface plot.
```
Here you've provided a 6x3 tensor, thus you're defining a surface over the plane of size 6x3. Your x values are then `range(0, 6)`, and your y values are `range(0, 3)`. Your z values are what you've provided at those x/y locations.
