### ISSUE TITLE
store_history

### ISSUE THREAD

**Issue by xuzhongyou** [facebookresearch/visdom#658]
![image](https://user-images.githubusercontent.com/16487416/63009141-80753100-beb6-11e9-834e-275ddf6b2945.png)
i have not found the store_history work when i run the demo.py

**Comment by JackUrb** [comment]
Hi @xuzhongyou - have you built locally? `store_history` hasn't yet been released in the version made available on PyPI or through pip.

**Comment by neka-nat** [comment]
I hope I can use the latest version via PYPI.
When will it be updated?

**Comment by JackUrb** [comment]
`0.1.8.9` is now live on PyPI.
