### ISSUE TITLE
Need help in installation of visdom

### ISSUE THREAD

**Issue by tsuttaket2** [facebookresearch/visdom#663]
Hi,

I am newbie here trying to install visdom. I am using Windows 10 on my machine which is installed with python 3.7.3.
Following the instruction 
1. pip install visdom <- This is fine.
2. luarocks install visdom <- I am stuck at this point.
    2.1 I already installed lua and luarocks

<img width="361" alt="Capture" src="https://user-images.githubusercontent.com/29170484/64033192-876e9580-cb7e-11e9-8f29-ff27983886de.PNG">

Can you please suggest how can I fix this. Thanks.

**Comment by JackUrb** [comment]
Hi @tsuttaket2 - if you're only intending on using visdom from python environments, you don't need to install the Lua version. We're deprecating that implementation soon as no development has been made on it in a long time.

**Comment by tsuttaket2** [comment]
Thank you
