### ISSUE TITLE
How to display the repeated labels?

### ISSUE THREAD

**Issue by lrh000** [facebookresearch/visdom#680]
When using heatmap to capture relevance between words, I found duplicated words are displayed only once, and corresponding values are missing

**Comment by JackUrb** [comment]
Hi @lrh000 - this issue has existed since #21, and a workaround is discussed there. There's potentially a hacky longer-term solution listed in the plotly issue (using `tickvals`) which I'd be happy to accept as an improvement in a PR that updates the heatmap code.

**Comment by lrh000** [comment]
@JackUrb Thx for your reply! I will check the #21 and try with matplotlib
