### ISSUE TITLE
blue screen and nothing in the screen

### ISSUE THREAD

**Issue by yanhuanhuanyy** [facebookresearch/visdom#681]
start the visdom server before starting the training network:
python -m visdom.server , and create a second terminal and type the training command. 
But I still see a blue screen in localhost:8097, nothing in the screen, just an message "file failed to load:/extension/MathZoom.js" and "file failed to load:/extension/MathMenu.js" in the lower left corner. Could you give me some advice? thanks a lot!
![1](https://user-images.githubusercontent.com/36001989/66809002-09642380-ef5f-11e9-9e04-4bda029205a2.png)

**Comment by JackUrb** [comment]
Hi @yanhuanhuanyy - this is usually a problem related to downloading the server resources, but you'd need to check your browsers JavaScript console to see if there are any additional errors. If it is a resource issue, please refer to the contributing guide for instructions on how to resolve it.

**Comment by yanhuanhuanyy** [comment]
Hi, @JackUrb , I check my browsers JavaScript console, the result is: 
![1](https://user-images.githubusercontent.com/36001989/66882299-7679c680-effc-11e9-8220-62a80c9df0c6.png)
Is this a resources issue ??

I read visdom/CONTRIBUTING.md, navigate to /public/myenvs/lib/python3.6/site-packages/visdom-0.1.8.9.dist-info (I install visdom in a virtual environment created under anaconda), download the download.sh script and execute it to automatically download the resources(command: bash download.sh). But, I get some error, download.sh: line 7: syntax error near unexpected token `newline'
download.sh: line 7: `<!DOCTYPE html>'
What should I do?

**Comment by JackUrb** [comment]
This appears to be a browser compatibility problem - your version of Firefox may be unsupported. Perhaps try a more modern version, or another browser?

**Comment by yanhuanhuanyy** [comment]
thanks a lot!!!!  I reinstalled firefox(a more modern version), it works!  I'm sorry to bother you.
