### ISSUE TITLE
How to save a fixed-size svg or png?

### ISSUE THREAD

**Issue by lrh000** [facebookresearch/visdom#683]
I have adjust the width(1000) and height(400) of the pane in chrome, but still get 700*450 svg or png when saving the pane.

**Comment by JackUrb** [comment]
Interacting with the pane doesn't actually resize the svg, just the view of it. Thus saving it with the download link isn't modifying your uploaded svg at all.

**Comment by lrh000** [comment]
> Interacting with the pane doesn't actually resize the svg, just the view of it. Thus saving it with the download link isn't modifying your uploaded svg at all.

Thx. So how to get the fixed-size svg since there are some labels that need to be displayed but are omitted

**Comment by JackUrb** [comment]
You will have to use an svg editor of some sort? I'm not really sure what you're trying to accomplish.

**Comment by lrh000** [comment]
> You will have to use an svg editor of some sort? I'm not really sure what you're trying to accomplish.

I mean how to download a  svg as the view of its pane? 

For example, I want to save a svg with 1000*400 instead of 700*400 because I want its x-axis to display more columnnames.
