### ISSUE TITLE
How to maintain it rotatable and interchangeable angle, when downloading 3D Scatter?

### ISSUE THREAD

**Issue by shirui-japina** [facebookresearch/visdom#684]
I think the 3D Scatter is a great function. But after I saved the image in the browser, the image can't be **rotatable** and **interchangeable angle** any more. Is there any great method to keep the image **rotatable** and **interchangeable angle** when downloading/saving the 3D scatter?

**Comment by JackUrb** [comment]
Unfortunately there's no real way we can support this directly without violating plotly terms of service - you can follow through to the "view plot on plotly" link, and then download the interactive version from there if you have a license with them, but otherwise we can't support this.

**Comment by shirui-japina** [comment]
I got it, thanks for your reply.

**Comment by shirui-japina** [comment]
> Unfortunately there's no real way we can support this directly without violating plotly terms of service - you can follow through to the "view plot on plotly" link, and then download the interactive version from there if you have a license with them, but otherwise we can't support this.

I got it, thanks for your reply.
