### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by mrrw3** [facebookresearch/visdom#687]
I used a server in experiment .And I am not administrator of the server.I always have this problem,As below:

requests.exceptions.ProxyError: HTTPConnectionPool(host='192.168.36.158', port=808): Max retries exceeded with url: http://localhost:8097/env/test1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe43848cb00>: Failed to establish a new connection: [Errno 110] Connection timed out',)))

**Comment by mrrw3** [comment]
this is my code:
import torch
import visdom
vis=visdom.Visdom(env='test1')
And then,error appeared.

**Comment by JackUrb** [comment]
Hi @mrrw3, sorry for the delay. Unfortunately I don't have enough information about your network architecture to know what might be going on. You may need to ask an administrator about what proxy settings are required to use your server, and then use the `proxy` argument as documented in our `README`.
