### ISSUE TITLE
Boxplot cannot handle boxes contain different number of data points?

### ISSUE THREAD

**Issue by xuehy** [facebookresearch/visdom#689]
Currently, the `boxplot` function takes a tensor of size **N by M** as input, where **M** is the number of boxes and **N** is the number of data points in each box. However, if I want to draw boxplot with each box containing different number of data points, current` boxplot` seems to not support this.

**Comment by JackUrb** [comment]
Hi @xuehy, at the moment we don't support this kind of behavior at all, you are correct. If you're interested in extending boxplot to have this functionality, we'd be happy to accept a PR.

**Comment by xuehy** [comment]
Thanks for your response. I'll try if I have time.
