### ISSUE TITLE
Select different port

### ISSUE THREAD

**Issue by pedropgusmao** [facebookresearch/visdom#69]
Hi, is it possible to select a different port for Visdom server?

**Comment by lvdmaaten** [comment]
Yes!

The server takes as input an optional argument `-port`: https://github.com/facebookresearch/visdom/blob/master/py/server.py#L36

When you create the Visdom object on the client side, you can similarly specify the port to which to connect: https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L196

**Comment by ypxie** [comment]
Hi,  how to specify port number in command line? 'python -m visdom.server' Thank!

**Comment by isalirezag** [comment]
the links you provided aint working

**Comment by JackUrb** [comment]
All of this info is in the docs now.
[Specifying port usage for the server](https://github.com/facebookresearch/visdom#usage)
[Specifying port usage for the python client](https://github.com/facebookresearch/visdom#visdom-arguments-python-only)
