### ISSUE TITLE
Visualization of hidden layer output

### ISSUE THREAD

**Issue by CBD88** [facebookresearch/visdom#697]
Is there any feature available to visualize the hidden layer output during training? Please share the sample code. If it is not possible then should i visualize the hidden layer output of trained model?

**Comment by JackUrb** [comment]
Generally you can observe hidden layer outputs by plotting them to an image, but we don't natively support this with a direct implementation yet. Actually figuring out what you should be visualizing is partially an open research question, but after you decide what channels you should be plotting (perhaps the weights? The neuron activations given a specific image? up to you to determine what makes most sense for your application) you can use `vis.image` to display them. Tooling for this is tracked in #510.
