### ISSUE TITLE
visdom starting error

### ISSUE THREAD

**Issue by aamirk5** [facebookresearch/visdom#711]
Hi guys... I'm new to visdom. Please help me out. I'm getting this error while i'm just running demo code... I have run the command "python -m visdom.server" before running my code and opened in browser getting. see the attachment. 
code is:
![visdom](https://user-images.githubusercontent.com/22737972/77257216-e7a95e00-6cad-11ea-8b4c-081ded32bb45.png)
![visdom](https://user-images.githubusercontent.com/22737972/77257260-2dfebd00-6cae-11ea-8308-58626ba0ff6c.png)
![visdom_connection_error](https://user-images.githubusercontent.com/22737972/77257261-2fc88080-6cae-11ea-9a14-6741c6713979.png)
 
import visdom
import numpy as np
vis = visdom.Visdom()
vis.text('Hello, world!')
vis.image(np.ones((3, 10, 10)))

WARNING:root:Setting up a new session...
ERROR:visdom:Connection is already closed.
ERROR:visdom:Connection is already closed.
ERROR:visdom:Connection is already closed.
WARNING:visdom:Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.

**Comment by JackUrb** [comment]
Hi @aamirk5 - do you still have the issue if you update the code and set `use_incoming_socket` to `False` as suggested? It's possible you need to update some packages (request, websockets) as I tend to only see this failing over localhost when an underlying package is out of date and the system perceives it as a security issue.

**Comment by aamirk5** [comment]
Hi @JackUrb..... thanks for your help... yes, i updated the packages you mentioned but still the same error...and when i did this vis = visdom.Visdom(use_incoming_socket=False) i got the below warning and still no display.... 


import visdom
import numpy as np
vis = visdom.Visdom(use_incoming_socket=False)
# vis = visdom.Visdom()
vis.text('Hello, world!')
vis.image(np.ones((3, 10, 10)))


WARNING:root:Setting up a new session...
WARNING:visdom:Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.



second try...


import visdom
import numpy as np
# vis = visdom.Visdom(use_incoming_socket=False)
vis = visdom.Visdom()
vis.text('Hello, world!')
vis.image(np.ones((3, 10, 10)))

Setting up a new session...
Connection is already closed.
Connection is already closed.
Connection is already closed.
Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.



I'm using python==3.6.5, visdom==0.1.8.9 websockets==8.1 and requests=2.23.0...

**Comment by JackUrb** [comment]
What does it say on the process that's running `visdom.server`?

**Comment by aamirk5** [comment]
@JackUrb this 

![visdom2](https://user-images.githubusercontent.com/22737972/77391497-d8bccb80-6dd3-11ea-87a0-ee69aacc967f.png)

**Comment by JafferWilson** [comment]
@aamirk5 Why it is Offline?

**Comment by aamirk5** [comment]
@JafferWilson i don't know... is there any problem with offline? how to make it online?

**Comment by JafferWilson** [comment]
@aamirk5 Just click on the offline button and check if it becomes online. If not then please remove the visdom and reinstall it once again. I guess it will help you. Sometimes moving a step back helps a lot.

**Comment by aamirk5** [comment]
@JafferWilson no,, button isn't working.... and i reinstall as you said but still not working,,, it's still offline........

**Comment by JackUrb** [comment]
> @JackUrb this
> 
> ![visdom2](https://user-images.githubusercontent.com/22737972/77391497-d8bccb80-6dd3-11ea-87a0-ee69aacc967f.png)

Sorry, this isn't the console that's running the server - in order to see what's going on I need to see the process (in a terminal window or somewhere) that is hosting this page.

**Comment by JafferWilson** [comment]
@aamirk5 What @JackUrb  want to see is how you have started this page. You might have tried `visdom` on your command prompt or `python -m visdom.server`.
Just run any of the above an show the command window.
There are certain logs, that will make sense.

**Comment by JackUrb** [comment]
Closing as I don't have enough information to move forward and I never saw the server console output.

**Comment by aamirk5** [comment]
yeah thank you so much, my problem has been solved... that was because of some malware in my computer preventing the http connections...
