### ISSUE TITLE
`opts` vs. `options`

### ISSUE THREAD

**Issue by spro** [facebookresearch/visdom#72]
The true name of the options dictionary is `opts` but it is referred to as `options` in the Readme.

**Comment by lvdmaaten** [comment]
Yeah, this is due to a discrepancy in the naming between the Lua and the Python wrapper. It may be hard to fix now without breaking things in people's code?

**Comment by spro** [comment]
Would it be worth overloading with `options` for the sake of consistency (and documentation), and gradually deprecating the opts version? It might be a heavy change looking at the code, but better now than later.

**Comment by ajabri** [comment]
IMO, we should actually change `options` to `opts` :)

**Comment by spro** [comment]
Either sound good as long as they're the same

**Comment by spro** [comment]
I'd be down to change that on the Lua side - it doesn't look as heavily used by Github search. Or even just the docs.

**Comment by JackUrb** [comment]
moved from options to opts in 135525a224fe4b7bf859768517ef7e9344c0b570
