### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by dizcza** [facebookresearch/visdom#723]
Will visdom support latex?

Currently, the command

```python
viz.line(Y=np.random.rand(10), opts=dict(title=r"$\alpha \sim \beta$"))
```

fails to render latex.

**Comment by JackUrb** [comment]
Hi @dizcza - Visdom used to have this support, but it broke when `MathJax`'s import suddenly stopped working. @ubaidsworld is working on a fix for this in #726.

**Comment by dizcza** [comment]
Nice!
Please close the issue once it's merged.

**Comment by ubaidsworld** [comment]
@dizcza  You can see this PR: #728 
It is not yet merged, but it works. Hope it will help.
