### ISSUE TITLE
'markersize' has no effect on visdom.line

### ISSUE THREAD

**Issue by dizcza** [facebookresearch/visdom#725]
**Bug Description**
`markersize` has no effect on `visdom.line()` - it acts as if `markersize` is always None.

**Reproduction Steps**
```python
viz.line(Y=np.random.rand(10), opts=dict(markersize=20))
```

**Expected behavior**
A line that connects 10 points each of radius/diameter equals 20 (equivalent to matplotlib).

If it's expected behavior, please remove `markersize` from the list of available options of visdom.line.

**Comment by JackUrb** [comment]
@dizcza `markersize` will only have an effect if you set `markers` to `True`, as the default is to not show markers on lines.
This should have the effect you want:
```
viz.line(Y=np.random.rand(10), opts=dict(markersize=20, markers=True))
```
Arguably `_assert_opts` could warn if a `marker`-option is set, but `markers` is not to prevent this kind of confusion, but it is in the docs.

**Comment by dizcza** [comment]
Sorry, I overlooked it.
