### ISSUE TITLE
visdom shows nothing nor env label in 'environment' when starting

### ISSUE THREAD

**Issue by 300LiterPropofol** [facebookresearch/visdom#736]
Hi, 

The environment that I use: Windows 10, python 3.7, visdom 0.1.8.9

I have installed visdom and typed python -m visdom.server in a terminal, it said 'It's alive'.

However, when I start using it in the code using 
self.vis = visdom.Visdom(env='env-test', use_incoming_socket=False, **kwargs)
and try to plot something in the server,
it neither shows the 'env-test' name label in the environment area, nor show any images.
There is only blue screen.

The log in the terminal is as below:
C:\Users\d84153606\.conda\envs\py37\lib\site-packages\visdom\server.py:39: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
  ioloop.install()  # Needs to happen before any tornado imports!
Checking for scripts.
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:8097
INFO:tornado.access:304 GET / (127.0.0.1) 18.92ms
INFO:tornado.access:101 GET /socket (127.0.0.1) 0.00ms
INFO:root:Opened new socket from ip: 127.0.0.1
INFO:tornado.access:200 POST /env/faster-rcnn-caffe (127.0.0.1) 47.80ms
INFO:tornado.access:200 POST /env/faster-rcnn-caffe (127.0.0.1) 46.80ms
INFO:tornado.access:304 GET /extensions/MathMenu.js?V=2.7.1 (127.0.0.1) 17.92ms
INFO:tornado.access:304 GET /extensions/MathZoom.js?V=2.7.1 (127.0.0.1) 23.90ms
INFO:tornado.access:200 POST /env/main (127.0.0.1) 1.00ms
INFO:tornado.access:304 GET / (127.0.0.1) 16.93ms
INFO:tornado.access:304 GET /static/js/bootstrap.min.js?v=5869c96cc8f19086aee625d670d741f9 (127.0.0.1) 140.40ms
INFO:tornado.access:304 GET /static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219 (127.0.0.1) 2.99ms
INFO:tornado.access:304 GET /static/css/react-grid-layout-styles.css?v=7dc8934d2f9ac5303b8f0bb1148152a0 (127.0.0.1) 4.98ms
INFO:tornado.access:304 GET /static/js/react-react.min.js?v=bca103da5b5404d93783ccf73e0e9d1e (127.0.0.1) 6.97ms
INFO:tornado.access:304 GET /static/js/mathjax-MathJax.js?v=49565b9ce89c64da075a5a39969b366e (127.0.0.1) 8.96ms
INFO:tornado.access:304 GET /static/js/main.js?v=47fc3afa811b358b354df09184e392e7 (127.0.0.1) 10.95ms
INFO:tornado.access:304 GET /static/js/jquery.min.js?v=e071abda8fe61194711cfc2ab99fe104 (127.0.0.1) 8.96ms
INFO:tornado.access:304 GET /static/js/plotly-plotly.min.js?v=04dc3d6ed4e183246cd3ad70e259fcee (127.0.0.1) 12.94ms
INFO:tornado.access:304 GET /static/js/react-dom.min.js?v=950495cc51ccb90612cf0fe0bb44f8f3 (127.0.0.1) 3.98ms
INFO:tornado.access:304 GET /static/css/style.css?v=fb4729780f2360ef5d3dba13f8ff2873 (127.0.0.1) 4.98ms
INFO:tornado.access:304 GET /static/css/react-resizable-styles.css?v=9f91a8dbf4d8f7ef1399e625660405f4 (127.0.0.1) 5.98ms
INFO:tornado.access:304 GET /static/js/layout_bin_packer.js?v=6c46683ed70fbb1443caf3531243836d (127.0.0.1) 6.97ms
INFO:tornado.access:304 GET /static/fonts/glyphicons-halflings-regular.woff2 (127.0.0.1) 1.00ms
INFO:tornado.access:101 GET /socket (127.0.0.1) 0.99ms
INFO:root:Opened new socket from ip: 127.0.0.1
INFO:tornado.access:200 POST /env/main (127.0.0.1) 1.00ms
INFO:tornado.access:200 POST /env/main (127.0.0.1) 1.99ms
INFO:tornado.access:304 GET /extensions/MathMenu.js?V=2.7.1 (127.0.0.1) 22.90ms
INFO:tornado.access:304 GET /extensions/MathZoom.js?V=2.7.1 (127.0.0.1) 16.93ms
INFO:tornado.access:101 GET /socket (127.0.0.1) 1.00ms
INFO:root:Opened new socket from ip: 127.0.0.1
INFO:tornado.access:200 POST /env/main (127.0.0.1) 1.00ms
INFO:tornado.access:200 GET /static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219 (127.0.0.1) 43.81ms
INFO:tornado.access:200 GET /static/css/react-resizable-styles.css?v=9f91a8dbf4d8f7ef1399e625660405f4 (127.0.0.1) 45.80ms
INFO:tornado.access:200 GET /static/css/react-grid-layout-styles.css?v=7dc8934d2f9ac5303b8f0bb1148152a0 (127.0.0.1) 47.80ms
INFO:tornado.access:200 GET /static/css/style.css?v=fb4729780f2360ef5d3dba13f8ff2873 (127.0.0.1) 48.79ms
INFO:tornado.access:200 GET /static/css/bootstrap.min.css?v=ec3bb52a00e176a7181d454dffaea219 (127.0.0.1) 51.78ms
INFO:tornado.access:200 GET /static/css/react-grid-layout-styles.css?v=7dc8934d2f9ac5303b8f0bb1148152a0 (127.0.0.1) 52.78ms
INFO:tornado.access:200 GET /static/css/react-resizable-styles.css?v=9f91a8dbf4d8f7ef1399e625660405f4 (127.0.0.1) 1.99ms
INFO:tornado.access:200 GET /static/css/style.css?v=fb4729780f2360ef5d3dba13f8ff2873 (127.0.0.1) 3.98ms
WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map (127.0.0.1) 2.99ms
WARNING:tornado.access:404 GET /static/css/bootstrap.min.css.map (127.0.0.1) 3.98ms
WARNING:tornado.access:404 GET /static/js/layout-bin-packer.js.map (127.0.0.1) 2.99ms
WARNING:tornado.access:404 GET /static/js/layout-bin-packer.js.map (127.0.0.1) 1.99ms
INFO:root:comparing envs
INFO:tornado.access:200 POST /compare/faster-rcnn-caffe+main (127.0.0.1) 35.85ms
INFO:tornado.access:200 POST /env/faster-rcnn-caffe (127.0.0.1) 74.68ms

**Comment by 300LiterPropofol** [comment]
The screenshot is as below, there is no 'test-env' label in the environment, all shown names are previous work
[https://imgur.com/yJoje3i](url)

**Comment by 300LiterPropofol** [comment]
It seems like I can not upload any image due to firewall limitation, sorry about that.

**Comment by JackUrb** [comment]
There are no posts to `test-env` in your server log, only lines like `INFO:tornado.access:200 POST /env/main`. If you manually set the `env` in your log call (`vis.line(..., env='test-env')`) does it work? The fact that you're posting to main at all would mean that the `Visdom` object is pulling `'main'` from here:
https://github.com/facebookresearch/visdom/blob/7b1203a0aa43a72a6e3dc2271ddba41f9cc960ce/py/visdom/__init__.py#L667
But we only ever set it here, which should have it be `'test-env'`:
https://github.com/facebookresearch/visdom/blob/7b1203a0aa43a72a6e3dc2271ddba41f9cc960ce/py/visdom/__init__.py#L408

**Comment by 300LiterPropofol** [comment]
Thank you for your reply. I will close this because it seems to be a firewall proxy issue which can not be solved by changing visdom configurations.
