### ISSUE TITLE
Run visdom without Internet Access

### ISSUE THREAD

**Issue by xiaoleihuang** [facebookresearch/visdom#738]
I am running the visdom on a server without Internet access, when I start visdom, it just stays and stops at the following steps:

Checking for scripts.
Downloading scripts, this may take a little while

How can I setup for the server without the Internet access?

**Comment by JackUrb** [comment]
You can run the download script on a machine with internet access, and then copy the `py/static` directory over manually.

**Comment by xiaoleihuang** [comment]
Yes, I have downloaded files under the `py` directory. I find the visdom is installed under `~/anaconda3/lib/python3.7/site-packages/visdom`, and I overwrite the  `~/anaconda3/lib/python3.7/site-packages/visdom/static` by the `py/static/`, but the progress does not proceed to next steps.

**Comment by xiaoleihuang** [comment]
@JackUrb Thanks for your help. After copying the web pages, I comment out `download_scripts()` in the `server.py`, and it works well.

**Comment by da-h** [comment]
Hey @theneao,
this is something several people have noted.
Please follow #907 for a discussion on this topic.
Best,
*da-h*

**Comment by rayquazaMega** [comment]
For visdom 0.2.4, I uploaded a static folder archive:https://onedrive.live.com/?authkey=%21AFh%5FzYrcxVHPJBI&id=A5F4AF7B624C0331%211985&cid=A5F4AF7B624C0331
