### ISSUE TITLE
Feature Request: Subfolder/project support

### ISSUE THREAD

**Issue by Florian-Roessler** [facebookresearch/visdom#75]
Hello,

I really like this project and have started to use it with multiple projects. However, this can quickly lead to a drop-downs with a considerable number of different environments from different projects. A colleague and myself have started a slightly hacky approach in implement subfolder support which works for viewing and loading files from different subfolders. Before we continue implementing support for saving into subfolders we thought we ask if something like this already exists or is under development?

Currently we created a second drop down that allows the selection of folders as well as linking that back to server.py to change the PATH in which the server is looking for JSON files.

For me this seems to be a critical feature when used with multiple people/projects so I would be curious to hear what solutions other people have found. I guess another one could be to start different visdom servers for each project with different ports?

Best wishes,
Florian

**Comment by ajabri** [comment]
Hi @Florian-Roessler !

I agree that this can be annoying.

One option (as you suggest) is to start a different server; you can actually specify the `port` as well as the `env_path` from which to load envs. Doesn't this basically allow you to achieve the same thing as subfolders? I agree it is not as nice though...

Another feature that might help with a related problem is pane filtering, by which I mean having a text input bar that you can use to filter by title (by regex) which panes are visible in the env. This would help with indexing into visualizations in existing envs. I have implemented this locally but have not yet pushed it out.

**Comment by Florian-Roessler** [comment]
Hi @ajabri,

Yes in theory the port/env_path thing works, but running a server per project seems a bit overkill. I am thinking along the lines of adding a "project" option when sending a new graph and executing a save directly. The project variable could then be used together with the knowledge of the relative path to write the JSON.

I like the pane filtering as a general feature! This would be very handy in general and I would love to see it pushed to the github. However I am thinking also along the lines of using different env of the same graphs produced by a pipeline that has different inputs into the same "function" but producing the same type of plots. Having all this in one env could lead to longer loading times as one might wish O_o.

**Comment by JackUrb** [comment]
The experience for dealing with multiple environments is likely much improved since the introduction of views #237. One environment can be used for each experiment, and then multiple views can be saved for each environment, thus allowing better organization within each experiment without needing many environments for it.
