### ISSUE TITLE
change visdom to an open source license?

### ISSUE THREAD

**Issue by pabs3** [facebookresearch/visdom#759]
I note that visdom is released under the Creative Commons Attribution-NonCommercial 4.0 International Public License.

This license is not compatible with the Open Source Initiative's [Open Source Definition](https://opensource.org/osd), the GNU Project's [Free Software Definition](https://www.gnu.org/philosophy/free-sw.en.html) nor the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines) because it discriminates against potential commercial users of the software.

The definition of non-commercial purposes is [unclear](https://en.wikipedia.org/wiki/Non-commercial_license#Defining_%22Noncommercial%22), with a wide range of expectations on what it means.

The Creative Commons licenses are not often used for software as they are more suitable for cultural works like photography or movies.

The Facebook CLA gives Facebook additional privileges on the contributions of other contributors over and above the license the contributors place on their work. Many potential contributors will prefer that everyone using or contributing to the project gets an equal footing, especially wrt relicensing the codebase.

These issues are likely to discourage potential users from using the project and potential contributors from taking over the project and I note that Facebook is actively looking for more contributors (#753).

I propose to switch the license to another open source license that is commonly used for software. Examples include the MIT, BSD, Apache 2.0 and GNU GPL licenses. I propose that after the license is changed, the Facebook CLA is removed as a requirement for contributing.

This change could potentially grow the user and contributor base. Facebook doesn't appear to be offering paid licenses to folks who want to use visdom for commercial purposes, so there should be no financial downside from this change.

**Comment by lvdmaaten** [comment]
Thanks for your feedback, @pabs3!

We are fully aware of the limitations of the Creative Commons Attribution-NonCommercial 4.0 International Public License. We are unable to change the license of visdom at this point. However, as part of https://github.com/facebookresearch/visdom/issues/753 we are happy to transition the project to a non-Facebook organization and grant that new organization the right to re-license the project, which I think will address your concerns.

**Comment by pabs3** [comment]
Thank you for providing a potential path towards re-licensing visdom.

I will do some research on the potentially appropriate organisations
and present my results here.

I would propose that recent contributors could be surveyed in order to
choose an appropriate org.

I would propose that once an organisation is chosen, that org would
survey all previous contributors to visdom in order to come up with a
rough consensus on which license to choose.

If the Facebook CLA transferred copyright from the contributors to
Facebook and Facebook transferred that copyright to the new org, then
potentially the new org could transfer copyright back to the previous
contributors but this could be a fair bit of work. Projects with a
diverse set of copyright holders tend to be more resilient and more
likely to survive as open source projects in the long term.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I've done some research on potentially appropriate organisations
related to the users of visdom and the technology it uses and I found
that NumFocus, LF AI, FOSSASIA, PSF or SFC are potentially appropriate
organisations.

NumFocus is a non-profit supporting open source code for better science
and is strongly related to the NumPy project, which visdom uses.

https://numfocus.org/

The Linux Foundation's AI Foundation is a trade association that
supports open source work in artificial intelligence, machine learning,
and deep learning.

https://lfai.foundation/

FOSSASIA is an organisation doing open source development, advocacy and
conferences in Asia. One of their projects is SUSI.AI, an AI based
personal assistant.

https://fossasia.org/
https://susi.ai/

The Python Software Foundation stewards the Python programming
language, which visdom is written in.

https://www.python.org/psf/

Software Freedom Conservancy is a non-profit steward of various open
source projects, including git.

https://sfconservancy.org/

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
Did you get a chance to research the organisations I found? If it helps to make a decision, I would recommend NumFocus. I'm happy to approach them if you don't have time to do that.

**Comment by JackUrb** [comment]
Hi @pabs3 - we're in the final steps of transferring ownership to one of these groups. Thanks for the possible connections, and more news to come soon.

**Comment by pabs3** [comment]
Excellent, I look forward to hearing which organisation was chosen.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by JackUrb** [comment]
The license has been updated to Apache 2 in #767

**Comment by pabs3** [comment]
Excellent, thanks for relicensing.

Was there a decision about which organisation will take over visdom?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by JackUrb** [comment]
Yes, details to come soon!

**Comment by pabs3** [comment]
Looks like FOSSASIA was chosen as the organisation to take over the visdom project, congrats to the @fossasia folks, even though I felt NumFocus was the better choice.

**Comment by mariobehling** [comment]
Thanks a lot for making this possible! @JackUrb 

@pabs3 I think transitioning the repo here is not a decision against another organisation. Actually it would be great if we could work together with different orgs to bring this project forward. The info on the NumFocus website seems outdated and parts of their site is broken though. So, not sure what is the status.

I think a community meeting online would be great to collect ideas for the roadmap and gain interested devs. Please give us a few days to come up with a date.

In the meantime please join the Gitter channel as well for chat communication https://gitter.im/fossasia/visdom

And there is a tweet from Facebook AI here https://twitter.com/facebookai/status/1346506640699355142.

**Comment by pabs3** [comment]
Another announcement of the change:

https://www.facebook.com/FacebookAI/photos/a.360372474139712/1739843239525955/?type=3&theater
