### ISSUE TITLE
Number of Frames Per Second in Video

### ISSUE THREAD

**Issue by shubhamjain0594** [facebookresearch/visdom#77]
[Here](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L419) 25 is explicitly used as number of frames per second. Ideally it must be a parameter given by the user.

**Comment by ajabri** [comment]
Hi @shubhamjain0594

Good catch! Would you like to submit a pull request? It should be quite simple, just something like `opts.get('fps', 25)`.

**Comment by shubhamjain0594** [comment]
Onto it.

**Comment by shubhamjain0594** [comment]
@ajabri Check our PR #79

**Comment by ajabri** [comment]
Solved in #79 -- Thanks @shubhamjain0594 !
