### ISSUE TITLE
Feature request: Online rendering service

### ISSUE THREAD

**Issue by bodokaiser** [facebookresearch/visdom#78]
Something like nbviewer for visdom .jsons would be really great so that you can share your work publicly. Any plans on that?

**Comment by ajabri** [comment]
Hi @bodokaiser 

Thanks for your message! I agree. We don't have something like that yet. It would also be nice to have a way to: 1) nicely serialize the dashboard to something viewable later offline, 2) make locally hosted dashboards viewable by the public. I've been thinking that `ngrok` might be a way to solve the latter.

**Comment by bodokaiser** [comment]
Hi @ajabri 

I agree with your ideas! However I think the main problem is if FB would pay server bills + admin hours to get this up and running.

**Comment by ajabri** [comment]
Since this is an open-source project aimed at supporting the research community and not a product, FB would not be able to support any hosting. That said, with something like ngrok, as long as you have a public endpoint, you can access something like visdom running locally.

**Comment by JackUrb** [comment]
Closing as technically one could share their visdom `.json`'s for others to view simply by loading them up on their own local visdom server, and we aren't going to be setting up hosting for this project.
