### ISSUE TITLE
Feature Request: pie chart?

### ISSUE THREAD

**Issue by tengr** [facebookresearch/visdom#8]
awesome library btw

**Comment by lvdmaaten** [comment]
It is not implemented right now, but Plotly does support pie charts so it should be very easy to expose this functionality in the Lua and Python clients.

https://plot.ly/python/pie-charts/

**Comment by tengr** [comment]
Thanks! 

Our requirement is a drill-down pie chart, something like this http://www.highcharts.com/demo/pie-drilldown Unfortunately I don't think we can use visdom for our visualisation for now. It would be nice if there's a feature like this so that we don't have to pipe the nested json to another javascript library. Probably not a common use case though.

**Comment by lvdmaaten** [comment]
Closed by https://github.com/facebookresearch/visdom/commit/91105e40bd0f71ba64e4bd6c21f1fcf2b8a0ac1b.
