### ISSUE TITLE
X and Y in scatter: not x and y as in y=f(x)

### ISSUE THREAD

**Issue by hsclouse** [facebookresearch/visdom#86]
Just wanted to mention that as someone not familiar with plotly (I suppose that's where it comes from), the use of `X` and `Y` in the [python examples](https://github.com/facebookresearch/visdom/blob/master/example/demo.py#L48) kept me confused as to how to produce a scatter plot for several hours.

My goal was to plot a single variable with markers, not a line (i.e. with `scatter` not with `line`). I set up my problem thus:

    >>> import numpy as np
    >>> import visdom
    >>> viz = visdom.Visdom()
    >>> x = np.arange(0, 100, 1)
    >>> y = x ** 2

Thinking of `X` as the independent variable and skimming the examples, I tried the following with included errors:

    >>> viz.scatter(x, y)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/anaconda2/anaconda/lib/python2.7/site-packages/visdom/__init__.py", line 179, in result
        return fn(*args, **kwargs)
      File "/anaconda2/anaconda/lib/python2.7/site-packages/visdom/__init__.py", line 508, in scatter
        assert X.ndim == 2, 'X should have two dims'
    AssertionError: X should have two dims

... and then this, in case it would work with a tuple:

    >>> viz.scatter((x, y))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/anaconda2/anaconda/lib/python2.7/site-packages/visdom/__init__.py", line 179, in result
        return fn(*args, **kwargs)
      File "/anaconda2/anaconda/lib/python2.7/site-packages/visdom/__init__.py", line 508, in scatter
        assert X.ndim == 2, 'X should have two dims'
    AttributeError: 'tuple' object has no attribute 'ndim'

Once I finally figured it out this worked):

    >>> viz.scatter(np.column_stack((x, y)))

I don't suppose this is really an issue but, I wanted to point out my confusion in case someone else ran across this later: `Y` is the class label data and `X` can't have less than two "samples." If there's a better place for me to post this, please let me know.

**Comment by ajabri** [comment]
Hi @hsclouse , 

Thanks for your message! I totally see how this API initially seems unintuitive. When we implemented the plotting wrapper, we did indeed discuss the pros and cons of using `X` to contain both dependent and independent variables. In the end, we hoped that the documentation (https://github.com/facebookresearch/visdom#visscatter) would be enough to get people on the right track.

Note that the plotting wrapper is totally optional, though -- ultimately, if it's easier for you, you can follow https://plot.ly/python/line-and-scatter/ and use the generic plotting API https://github.com/facebookresearch/visdom#generic-plots.
