### ISSUE TITLE
feature request: allow plot request over network

### ISSUE THREAD

**Issue by episodeyang** [facebookresearch/visdom#87]
Dear Maintainers,

I would love to setup a visdom plotting server, and have all of my cluster machines access the plotting server over the network using an access token.

Would this be considered for the roadmap?

**Comment by ajabri** [comment]
Hey @episodeyang !

By 'access the plotting server', do you mean plotting remotely over a network? Yes, this kind of support is implicitly built in (we actually use it this way already), though the access token authentication hasn't really been implemented yet (#85). Did you mean something more elaborate?

Allan

**Comment by episodeyang** [comment]
@ajabri I just found out about this in the source code:) Closing since this feature is already implemented.
