### ISSUE TITLE
how to plot figures of different projects in different workspaces?

### ISSUE THREAD

**Issue by ypxie** [facebookresearch/visdom#88]
Currently, there are all showing in one page, which makes it look really crowed.
Thanks!

**Comment by lvdmaaten** [comment]
Each plotting function has an `env` input variable, which specifies the
environment ("workspace") in which the plot gets added. You can use the
dropdown menu in the top bar to select the environment you're viewing.

Note that you may have to reload your page whenever you add a new
environment in visdom.
