### ISSUE TITLE
call to write_message slowing down training

### ISSUE THREAD

**Issue by karandwivedi42** [facebookresearch/visdom#89]
While training, if I plot a line graph and update it after each iteration, as the number of points increases, the call to updateTrace begins slowing down the entire training (by 3-4x).

On digging inside visdom, I found that the call to `write_message` [here](https://github.com/facebookresearch/visdom/blob/master/py/server.py#L221) is the culprit. To avoid this slowdown in training, my current fix is to comment this and then refresh periodically. 

I think there should be some solution like:
1. Pass small amount of data in `write_message` or
2. Do the message passing without blocking the main thread or
3. Keep a checkbox on top bar for "render real time"

**Comment by ajabri** [comment]
Hi @karandwivedi42 

Thanks for your message. If the data grows quickly, this can indeed slow things down. The problem with passing a small amount of data in write_message is that effectively means that the state will be maintained on the browser end, which has drawbacks. IMO, the best solution may be to do the message passing without blocking the main thread. This could amount to making the visdom client asynchronous, with it's own subprocess.

**Comment by karandwivedi42** [comment]
I agree. I didn't know how to implement it without adding extra
dependencies though. Any plans regarding this?

**Comment by ajabri** [comment]
I think the simplest way is to add an option to make the request sending asynchronous (e.g., modify the `send` method). I can probably get to this in the next few weeks!

In the meantime, a simple temporarily solution may be to send plotting updates less frequently, and to subsample the plotting data.
