### ISSUE TITLE
TypeError: _send() got an unexpected keyword argument 'data'

### ISSUE THREAD

**Issue by ankoorb** [facebookresearch/visdom#91]
- Python 2.7.6
- I am getting TypeError when I use the code provided in the [Generic Plots](https://github.com/facebookresearch/visdom#generic-plots) section of README. Here is the exact error `TypeError: _send() got an unexpected keyword argument 'data'`. 
- I have checked the [source code (line: 226)](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py) and found that the args/kwargs used by the function `_send` are "msg" and "endpoint='events'", however the README code snippet uses args/kwars as data=[trace], layout=layout, win='Test'. I think that README is not updated to reflect changes in the source code.

**Comment by Varal7** [comment]
Fixed by #90

**Comment by ajabri** [comment]
Thanks @ankoorb and @Varal7 !
