### ISSUE TITLE
Unable to write data into visdom web

### ISSUE THREAD

**Issue by zizhaozhang** [facebookresearch/visdom#92]
Hi
Probably this issue is not because of problems of visdom itself, but I do not know whereelse to ask.
When I run the toy example
```
import visdom
import numpy as np
vis = visdom.Visdom()
vis.text('Hello, world!')
vis.image(np.ones((3, 10, 10)))
```
I got errors like the following. The visom pane at webpage of localhost:8097 shows nothing. How to solve this issue? Is there anyway to set the ip to 0.0.0.0? THX!

`u'<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html><head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"><!--\n /*\n Stylesheet for Squid Error pages\n Adapted from design by Free CSS Templates\n http://www.freecsstemplates.org\n Released for free under a Creative Commons Attribution 2.5 License\n*/\n\n/* Page basics */\n* {\n\tfont-family: verdana, sans-serif;\n}\n\nhtml body {\n\tmargin: 0;\n\tpadding: 0;\n\tbackground: #efefef;\n\tfont-size: 12px;\n\tcolor: #1e1e1e;\n}\n\n/* Page displayed title area */\n#titles {\n\tmargin-left: 15px;\n\tpadding: 10px;\n\tpadding-left: 100px;\n\tbackground: url(\'http://www.squid-cache.org/Artwork/SN.png\') no-repeat left;\n}\n\n/* initial title */\n#titles h1 {\n\tcolor: #000000;\n}\n#titles h2 {\n\tcolor: #000000;\n}\n\n/* special event: FTP success page titles */\n#titles ftpsuccess {\n\tbackground-color:#00ff00;\n\twidth:100%;\n}\n\n/* Page displayed body content area */\n#content {\n\tpadding: 10px;\n\tbackground: #ffffff;\n}\n\n/* General text */\np {\n}\n\n/* error brief description */\n#error p {\n}\n\n/* some data which may have caused the problem */\n#data {\n}\n\n/* the error message received from the system or other software */\n#sysmsg {\n}\n\npre {\n    font-family:sans-serif;\n}\n\n/* special event: FTP / Gopher directory listing */\n#dirmsg {\n    font-family: courier;\n    color: black;\n    font-size: 10pt;\n}\n#dirlisting {\n    margin-left: 2%;\n    margin-right: 2%;\n}\n#dirlisting tr.entry td.icon,td.filename,td.size,td.date {\n    border-bottom: groove;\n}\n#dirlisting td.size {\n    width: 50px;\n    text-align: right;\n    padding-right: 5px;\n}\n\n/* horizontal lines */\nhr {\n\tmargin: 0;\n}\n\n/* page displayed footer area */\n#footer {\n\tfont-size: 9px;\n\tpadding-left: 10px;\n}\n\n\nbody\n:lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; }\n:lang(he) { direction: rtl; }\n --></style>\n</head><body id=ERR_ACCESS_DENIED>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p>The following error was encountered while trying to retrieve the URL: <a href="http://localhost:8097/events">http://localhost:8097/events</a></p>\n\n<blockquote id="error">\n<p><b>Access Denied.</b></p>\n</blockquote>\n\n<p>Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.</p>\n\n<p>Your cache administrator is <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_ACCESS_DENIED&amp;body=CacheHost%3A%20usmlva1006csrv%0D%0AErrPage%3A%20ERR_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Wed,%2031%20May%202017%2021%3A48%3A55%20GMT%0D%0A%0D%0AClientIP%3A%20129.73.12.124%0D%0A%0D%0AHTTP%20Request%3A%0D%0APOST%20%2Fevents%20HTTP%2F1.1%0AHost%3A%20localhost%3A8097%0D%0AConnection%3A%20keep-alive%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0AAccept%3A%20*%2F*%0D%0AUser-Agent%3A%20python-requests%2F2.12.4%0D%0AContent-Length%3A%201000%0D%0A%0D%0A%0D%0A">root</a>.</p>\n<br>\n</div>\n\n<hr>\n<div id="footer">\n<p>Generated Wed, 31 May 2017 21:48:55 GMT by usmlva1006csrv (squid/3.1.23)</p>\n<!-- ERR_ACCESS_DENIED -->\n</div>\n</body></html>\n'`

**Comment by lvdmaaten** [comment]
It's difficult to say, but this looks to me like a firewall / proxy / VPN issue. Something on your server is preventing you from accessing port 8097 on localhost. Did you try using an SSH tunnel?

```README.md
If the above does not work, try using an SSH tunnel to your server by adding the following line to your local ~/.ssh/config: LocalForward 127.0.0.1:8097 127.0.0.1:8097
```

**Comment by zizhaozhang** [comment]
Hi 
Thanks for your reply. I tried this. Still not working.
But I am fine of using Tensorboard which use ip of 0.0.0.0. If this ip works, i think localhost should work based on my understanding. Right?
Is there any way to edit the IP of visdom to 0.0.0.0(in Pytorch not Torch)?

**Comment by lvdmaaten** [comment]
The visdom client lets you specify the server you want to connect to, so if your server is running at 0.0.0.0 then you can connect to that: https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L205

**Comment by DonYum** [comment]
@zizhaozhang Is that work?

**Comment by zizhaozhang** [comment]
Hi DonYum, I realized that is because the authority limitation of the proxy of my machine. You should check you proxy of you machine. 
Not the problem of visdom.
