### ISSUE TITLE
Does not work with Numpy 1.7

### ISSUE THREAD

**Issue by abeschneider** [facebookresearch/visdom#93]
I get an error resulting from a change to how `numpy.take` operates. It looks like the older version requires a tuple to be passed as the indices, whereas newer versions (tested with version 1.12.1) do not. This causes operations like `line` and `scatter` to fail.

I haven't submitted a PR as there are two potential solutions (not sure which is preferred):
1. Change how `numpy.take` (in particular `X.take(...)`) is being called.
2. Set a required version number in `install_requires` for `setup.py`.

**Comment by ajabri** [comment]
Hi @abeschneider ,

Thanks for your message! Option 1 sounds fine to me -- as long as it doesn't break compatibility. Feel free to submit a PR!

A
