### ISSUE TITLE
updateTrace does not plot lines with NaNs

### ISSUE THREAD

**Issue by aosokin** [facebookresearch/visdom#94]
Hi,
currently, updateTrace does not plot lines containing NaNs.
Code below produces just one line instead of two:
```
import numpy as np
from visdom import Visdom
viz = Visdom()
win = viz.line(Y=np.array([1, 2]), X=np.array([1, 2]), opts={'legend': ['a']})
viz.updateTrace(X=np.array([1, 2, 3]), Y=np.array([2, 1, float('nan')]),
                win=win, name='b')
```

**Comment by lvdmaaten** [comment]
This looks like a bug, indeed. It is presumably related to this functionality: "Trace update data that is all NaN is ignored; this can be used for masking update." Will investigate...

**Comment by lvdmaaten** [comment]
Note: I think you can replace `float('nan')` by `None` to "ignore" the point when plotting. Does this solve your issue?

**Comment by aosokin** [comment]
@lvdmaaten Thanks, that works!
