### ISSUE TITLE
quiver doesn't exist

### ISSUE THREAD

**Issue by lixiao89** [facebookresearch/visdom#95]
Hi,

I can't seem to find the quiver function in python. Any help would be great. Thanks

**Comment by ajabri** [comment]
Hi @lixiao89 !

You're right, it looks like the quiver function is currently only implemented in lua. The python feature should be added within the next few weeks. You're also welcome to submit a pull-request for it, if you want!

**Comment by lvdmaaten** [comment]
I will push a commit implementing this.

**Comment by lvdmaaten** [comment]
Added in https://github.com/facebookresearch/visdom/commit/b850bf4330732d0b1d73d3240012b6f809c98a19
