### ISSUE TITLE
updateTrace error

### ISSUE THREAD

**Issue by xjtu-zeng** [facebookresearch/visdom#99]
when I plot multiple lines in the same **_win_**, the **_updateTrace_** method seems awkward.

`
vis_line = vis.line(X = np.array([1,2,3]), Y = np.array([[1,1,1],[2,2,4],[3,4,7]]),  win="mywin")
 vis.updateTrace(X = np.array([4,4,4]), Y = np.array([5, 6, 7]), win="mywin", name=vis_line)
`

can anyone clarify what wrong with the code?

**Comment by lvdmaaten** [comment]
The `name` argument in `updateTrace` selects a trace to update. Since there is no trace called `vis_line`, your code is creating a new trace.

Your input arrays need to be transposed if you want to update all traces simultaneously:
```
>>> vis_line = vis.line(X = np.array([1,2,3]), Y = np.array([[1,1,1],[2,2,4],[3,4,7]]), win="mywin")
>>> vis.updateTrace(X = np.array([[4,4,4]]), Y = np.array([[5, 6, 7]]), win="mywin")
```
